(function(){
  "use strict";
  const root=document;
  const API=(window.BD_BOOKING_CONFIG?.apiBaseUrl||"").replace(/\/$/,"");
  const SESSION_KEY="bd_admin_session_v1";
  const LIFECYCLE_KEY="bd_crm_lifecycle_v1";
  const SETTINGS_KEY="bd_crm_settings_v1";
  let session=sessionStorage.getItem(SESSION_KEY)||"";
  let data=null,currentRecordEmail="",currentRecordTab="overview",editCtx=null,offerCtx=null;
  const $=s=>root.querySelector(s), $$=s=>[...root.querySelectorAll(s)];
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const normEmail=s=>String(s||"").trim().toLowerCase();
  const money=(cents,currency="EUR")=>new Intl.NumberFormat("de-AT",{style:"currency",currency:currency||"EUR"}).format(Number(cents||0)/100);
  const euro=n=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(Number(n||0));
  const dt=x=>x?new Intl.DateTimeFormat("de-AT",{timeZone:"Europe/Vienna",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(x)):"—";
  const dateOnly=x=>{if(!x)return"—";const s=String(x).slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[y,m,d]=s.split("-");return `${d}.${m}.${y}`}return dt(x).split(",")[0]};
  const now=()=>Date.now();
  const uid=()=>"p_"+Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const statusLabel=s=>({paid:"Bezahlt",open:"Offen",overdue:"Überfällig",test:"Test",void:"Storniert",cancelled:"Storniert",refunded:"Erstattet"})[s]||s;
  const lifecycleLabel=s=>({active:"Aktiv",paused:"Pausiert",completed:"Abgeschlossen",prospect:"Interessent:in"})[s]||s;

  function loadLifecycle(){
    try{const x=JSON.parse(localStorage.getItem(LIFECYCLE_KEY)||"{}");return {byEmail:x.byEmail||{},prospects:Array.isArray(x.prospects)?x.prospects:[],activities:Array.isArray(x.activities)?x.activities:[],offers:Array.isArray(x.offers)?x.offers:[]}}catch(e){return{byEmail:{},prospects:[],activities:[],offers:[]}}
  }
  function saveLifecycle(x){localStorage.setItem(LIFECYCLE_KEY,JSON.stringify(x));}
  function loadSettings(){try{return {...{dormantDays:60,renewalRemaining:1,discount:0},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")}}catch(e){return{dormantDays:60,renewalRemaining:1,discount:0}}}
  function saveSettings(x){localStorage.setItem(SETTINGS_KEY,JSON.stringify(x));}
  function logLocal(email,type,summary,detail=""){
    const x=loadLifecycle();x.activities.unshift({id:uid(),email:normEmail(email),type,summary,detail,at:new Date().toISOString()});x.activities=x.activities.slice(0,1200);saveLifecycle(x);
  }
  function setLifecycle(email,patch,reason=""){
    email=normEmail(email);if(!email)return;const x=loadLifecycle(),old=x.byEmail[email]||{};x.byEmail[email]={...old,...patch,updatedAt:new Date().toISOString()};saveLifecycle(x);
    const before=old.clientStatus||old.journeyStage||"—",after=patch.clientStatus||patch.journeyStage||before;
    if(before!==after) logLocal(email,"status",`Status geändert: ${lifecycleLabel(before)} → ${lifecycleLabel(after)}`,reason);
  }

  async function api(path,opts={}){
    const headers={...(opts.headers||{})}; if(session)headers.Authorization="Bearer "+session;
    const r=await fetch(API+path,{...opts,headers});const type=r.headers.get("content-type")||"";const body=type.includes("application/json")?await r.json():await r.text();
    if(r.status===401){session="";sessionStorage.removeItem(SESSION_KEY);showLogin();throw new Error("Sitzung abgelaufen. Bitte erneut einloggen.")}
    if(!r.ok||body?.ok===false)throw new Error(body?.error||"Die Anfrage konnte nicht verarbeitet werden.");return body;
  }
  async function post(path,body){return api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}
  function message(el,text,kind="ok"){el.className="notice "+kind;el.textContent=text}
  function showLogin(){$("#loginView").classList.remove("hidden");$("#appShell").classList.add("hidden")}
  function showApp(){$("#loginView").classList.add("hidden");$("#appShell").classList.remove("hidden")}

  $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("#loginBtn"),email=$("#loginEmail").value.trim();btn.disabled=true;btn.textContent="Sende …";try{const r=await fetch(API+"/admin/request-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Login-Link konnte nicht versendet werden.");message($("#loginMsg"),x.message||"Wenn diese Adresse freigeschaltet ist, wurde ein Login-Link versendet.")}catch(err){message($("#loginMsg"),err.message,"err")}finally{btn.disabled=false;btn.textContent="Login-Link senden"}});
  async function consumeMagicLink(){const u=new URL(location.href),token=u.searchParams.get("login");if(!token)return false;history.replaceState({},document.title,location.pathname);try{const r=await fetch(API+"/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"Login-Link ungültig.");session=x.sessionToken;sessionStorage.setItem(SESSION_KEY,session);return true}catch(err){showLogin();message($("#loginMsg"),err.message,"err");return false}}
  $("#logoutBtn").addEventListener("click",async()=>{try{await api("/admin/logout",{method:"POST"})}catch(e){}session="";sessionStorage.removeItem(SESSION_KEY);showLogin()});
  $("#refreshBtn").addEventListener("click",()=>load());

  const viewMeta={
    dashboard:["Praxis-Cockpit","Dashboard","Was heute Aufmerksamkeit braucht – und was als Nächstes kommt."],
    journey:["Client Journey","Klientenreise","Vom ersten Kontakt bis zur abgeschlossenen Begleitung."],
    clients:["Client Records","Kund:innen","Vollständiger administrativer Kontext pro Klient:in."],
    bookings:["Kalender","Termine","Buchungen verwalten, verschieben und nachvollziehen."],
    packages:["Begleitpakete","Packages","Einheiten, Gültigkeit und Fortsetzung im Blick."],
    invoices:["Finanzen","Rechnungen","Zahlungsstatus und Fristen auf einen Blick."],
    settings:["Praxis-CRM","Einstellungen","Lifecycle-Regeln und Datensicherung."]
  };
  function switchView(name){
    $$(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));
    const m=viewMeta[name]||viewMeta.dashboard;$("#viewEyebrow").textContent=m[0];$("#viewTitle").textContent=m[1];$("#viewSubtitle").textContent=m[2];
    $("#newInquiryBtn").style.display=(name==="journey"||name==="dashboard")?"":"none";
  }
  $$(".nav-item[data-view]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));

  async function load(){
    if(!session){showLogin();return}$("#appShell").classList.add("loading");
    try{data=await api("/admin/dashboard");showApp();$("#adminIdentity").textContent=data.admin?.email||"Administrator";renderAll()}catch(err){if(session)alert(err.message)}finally{$("#appShell").classList.remove("loading")}
  }

  function customerUniverse(){
    const map=new Map();const add=(email,name,id=null,backend=true)=>{const key=normEmail(email);if(!key)return;const old=map.get(key)||{email:key,name:name||email,id:null,backend:false};map.set(key,{...old,name:name||old.name,id:id||old.id,backend:old.backend||backend})};
    (data?.customers||[]).forEach(x=>add(x.email,x.name,x.id,true));(data?.bookings||[]).forEach(x=>add(x.email,x.name,null,true));(data?.packages||[]).forEach(x=>add(x.customerEmail,x.customerName,x.customerId,true));(data?.invoices||[]).forEach(x=>add(x.customerEmail,x.customerName,x.customerId,true));
    const life=loadLifecycle();life.prospects.forEach(p=>{if(!map.has(normEmail(p.email)))add(p.email,p.name,p.id,false)});return [...map.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name),"de"));
  }
  function clientData(email){email=normEmail(email);return {bookings:(data?.bookings||[]).filter(x=>normEmail(x.email)===email),packages:(data?.packages||[]).filter(x=>normEmail(x.customerEmail)===email),invoices:(data?.invoices||[]).filter(x=>normEmail(x.customerEmail)===email)}}
  function lifecycleOf(client){
    const life=loadLifecycle(),manual=life.byEmail[client.email]||{},prospect=life.prospects.find(p=>normEmail(p.email)===client.email),cd=clientData(client.email),t=now();
    if(!client.backend){return {journeyStage:prospect?.stage||manual.journeyStage||"inquiry",clientStatus:"prospect",manual:true}}
    if(manual.clientStatus==="completed")return {...manual,journeyStage:"completed",clientStatus:"completed"};
    if(manual.clientStatus==="paused")return {...manual,journeyStage:"paused",clientStatus:"paused"};
    if(["inquiry","consultation","waiting"].includes(manual.journeyStage))return {...manual,clientStatus:"prospect"};
    const upcoming=cd.bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()>=t);const past=cd.bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()<t);const activePkg=cd.packages.some(x=>Number(x.remaining)>0&&(!x.expiresAt||new Date(x.expiresAt).getTime()>t));
    if(upcoming.length===1&&!past.length&&!activePkg)return {...manual,journeyStage:"consultation",clientStatus:"prospect"};
    if(upcoming.length||activePkg)return {...manual,journeyStage:"active",clientStatus:"active"};
    if(past.length||cd.packages.length)return {...manual,journeyStage:"paused",clientStatus:"paused"};
    return {...manual,journeyStage:"inquiry",clientStatus:"prospect"};
  }
  function boardBucket(client){const l=lifecycleOf(client);if(l.clientStatus==="completed")return"completed";if(l.clientStatus==="paused")return"paused";return l.journeyStage||"inquiry"}

  function renderAll(){renderStats();renderAttention();renderRenewals();renderNext();renderJourney();renderClients();renderBookings();renderPackages();renderInvoices();renderSettings()}
  function renderStats(){
    const o=data.overview||{},clients=customerUniverse(),counts={active:0,paused:0,completed:0,prospect:0};clients.forEach(c=>counts[lifecycleOf(c).clientStatus]=(counts[lifecycleOf(c).clientStatus]||0)+1);
    $("#statToday").textContent=o.todayBookings??0;$("#statWeek").textContent=o.next7Bookings??0;$("#statActiveClients").textContent=counts.active;$("#statLifecycle").textContent=`${counts.paused} pausiert · ${counts.completed} abgeschlossen`;$("#statOpen").textContent=money(o.openInvoicesCents||0);$("#statOverdue").textContent=`davon ${money(o.overdueInvoicesCents||0)} überfällig`;$("#statTest").textContent=`Sandbox/Test: ${money(o.testInvoicesCents||0)}`;$("#navJourneyCount").textContent=clients.length;
  }
  function lastPastBooking(email){return clientData(email).bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()<now()).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]}
  function nextBooking(email){return clientData(email).bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()>=now()).sort((a,b)=>new Date(a.start)-new Date(b.start))[0]}
  function activePackage(email){return clientData(email).packages.filter(x=>Number(x.remaining)>0&&(!x.expiresAt||new Date(x.expiresAt).getTime()>now())).sort((a,b)=>Number(a.remaining)-Number(b.remaining))[0]}
  function renderAttention(){
    const items=[],settings=loadSettings();
    (data.invoices||[]).filter(x=>x.status==="overdue").forEach(x=>items.push({kind:"red",title:`${x.invoiceNumber} · ${x.customerName}`,text:`${money(x.totalCents,x.currency)} · fällig seit ${dateOnly(x.dueDate)}`,action:`<button class="mini remind" data-remind="${x.id}">Erinnerung senden</button>`}));
    (data.bookings||[]).filter(x=>x.status==="booked"&&x.confirmationEmailSent===false).forEach(x=>items.push({kind:"red",title:`Bestätigung fehlt · ${x.name}`,text:`Termin ${dt(x.start)}`,action:""}));
    customerUniverse().filter(c=>lifecycleOf(c).clientStatus==="active").forEach(c=>{if(nextBooking(c.email))return;const last=lastPastBooking(c.email);if(!last)return;const days=Math.floor((now()-new Date(last.start).getTime())/86400000);if(days>=settings.dormantDays)items.push({kind:"orange",title:`${c.name} · kein Folgetermin`,text:`Letzter Termin vor ${days} Tagen`,action:`<button class="mini" data-open-client="${esc(c.email)}">Akte öffnen</button>`})});
    $("#attentionCount").textContent=items.length;$("#attention").innerHTML=items.length?items.map(i=>`<div class="attention-item ${i.kind}"><div><strong>${esc(i.title)}</strong><span>${esc(i.text)}</span></div>${i.action}</div>`).join(""):`<div class="empty">Aktuell nichts Dringendes. ✓</div>`;bindInvoiceActions();bindClientOpeners();
  }
  function renewalCandidates(){const s=loadSettings();return (data.packages||[]).filter(x=>Number(x.remaining)<=Number(s.renewalRemaining)&&Number(x.remaining)>=0&&(x.purchaseStatus||"")!=="test").sort((a,b)=>Number(a.remaining)-Number(b.remaining))}
  function renderRenewals(){const rows=renewalCandidates();$("#renewals").innerHTML=rows.length?rows.slice(0,7).map(x=>`<div class="renewal-item"><div><strong>${esc(x.customerName)} · ${esc(x.productName)}</strong><span>${x.remaining}/${x.total} Einheiten offen${nextBooking(x.customerEmail)?` · nächster Termin ${dt(nextBooking(x.customerEmail).start)}`:" · kein Folgetermin"}</span></div><button class="mini edit" data-offer="${x.creditId}">Angebot vorbereiten</button></div>`).join(""):`<div class="empty">Aktuell kein Package am Übergang.</div>`;bindOfferButtons()}

  function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`}
  function renderNext(){const rows=(data.bookings||[]).filter(x=>x.status==="booked"&&new Date(x.start).getTime()>=now()).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,7);$("#nextBookings").innerHTML=rows.length?table(["Termin","Kund:in","Berater","Art","Ort",""],rows.map(x=>`<tr><td><strong>${esc(dt(x.start))}</strong></td><td><span class="name">${esc(x.name)}</span><div class="sub">${esc(x.email)}</div></td><td>${esc(x.advisorName||"Theophil Kroller")}</td><td>${esc(x.typeLabel)}</td><td>${esc(x.locationLabel)}</td><td><button class="mini edit" data-booking-edit="${esc(x.eventId)}">Bearbeiten</button></td></tr>`)):`<div class="empty">Keine kommenden Termine.</div>`;bindPowerActions()}

  const stages={
    inquiry:{title:"Anfrage",copy:"Neu eingegangen, noch kein Erstgespräch.",dot:"stage-inquiry"},
    consultation:{title:"Erstgespräch",copy:"Erstkontakt bzw. erster Termin ist vereinbart.",dot:"stage-consultation"},
    waiting:{title:"Wartet",copy:"Besprochen und wartet auf einen passenden Folgetermin.",dot:"stage-waiting"},
    active:{title:"Aktiv",copy:"Laufende Begleitung mit Termin oder aktivem Package.",dot:"stage-active"},
    paused:{title:"Pausiert",copy:"Aktuell keine regelmäßige Begleitung geplant.",dot:"stage-paused"},
    completed:{title:"Abgeschlossen",copy:"Begleitung bewusst abgeschlossen.",dot:"stage-completed"}
  };
  function renderJourney(){const clients=customerUniverse(),group={};Object.keys(stages).forEach(k=>group[k]=[]);clients.forEach(c=>(group[boardBucket(c)]||group.inquiry).push(c));$("#journeyBoard").innerHTML=Object.entries(stages).map(([key,s])=>`<section class="journey-column" data-drop-stage="${key}"><div class="journey-column-head"><div class="label-wrap"><i class="stage-dot ${s.dot}"></i><h3>${s.title}</h3></div><span class="stage-count">${group[key].length}</span></div><div class="stage-copy">${s.copy}</div><div class="journey-cards">${group[key].map(clientCard).join("")}</div></section>`).join("");bindJourneyDnD();bindClientOpeners()}
  function clientCard(c){const n=nextBooking(c.email),pkg=activePackage(c.email),inv=clientData(c.email).invoices.find(x=>x.status==="overdue");return `<article class="client-card" draggable="true" data-client-email="${esc(c.email)}"><h4>${esc(c.name)}</h4><div class="card-email">${esc(c.email)}</div><div class="card-meta">${n?`<span>📅 ${esc(dt(n.start))}</span>`:""}${pkg?`<span>▣ ${esc(pkg.productName)} · ${pkg.remaining}/${pkg.total}</span>`:""}</div><div class="card-flags">${pkg&&Number(pkg.remaining)<=loadSettings().renewalRemaining?`<span class="flag warn">Fortsetzung</span>`:""}${inv?`<span class="flag alert">Rechnung überfällig</span>`:""}</div><button class="card-open" type="button" data-open-client="${esc(c.email)}">Akte öffnen →</button></article>`}
  function bindJourneyDnD(){let dragged="";$$('.client-card[draggable="true"]').forEach(card=>{card.addEventListener('dragstart',e=>{dragged=card.dataset.clientEmail;card.classList.add('dragging');e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>{card.classList.remove('dragging');$$('.journey-column').forEach(c=>c.classList.remove('drag-over'))})});$$('[data-drop-stage]').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('drag-over');if(!dragged)return;moveClient(dragged,col.dataset.dropStage);dragged=""})})}
  function moveClient(email,stage){const c=customerUniverse().find(x=>x.email===normEmail(email));if(!c)return;const life=loadLifecycle();const prospect=life.prospects.find(p=>normEmail(p.email)===c.email);if(prospect&&!c.backend){prospect.stage=stage;prospect.updatedAt=new Date().toISOString();saveLifecycle(life);logLocal(email,"journey",`Journey: ${stages[stage]?.title||stage}`);renderAll();return}const patch={journeyStage:stage};if(stage==="active")patch.clientStatus="active";else if(stage==="paused")patch.clientStatus="paused";else if(stage==="completed")patch.clientStatus="completed";else patch.clientStatus="prospect";setLifecycle(email,patch,"per Drag & Drop");renderAll()}

  function clientStatusBadge(s){return `<span class="badge ${s==='active'?'active-badge':s==='paused'?'paused-badge':s==='completed'?'completed-badge':'prospect-badge'}">${esc(lifecycleLabel(s))}</span>`}
  function renderClients(){const q=String($("#clientSearch").value||"").trim().toLowerCase(),filter=$("#clientStatusFilter").value;let cs=customerUniverse().filter(c=>!q||`${c.name} ${c.email}`.toLowerCase().includes(q));if(filter!=="all")cs=cs.filter(c=>lifecycleOf(c).clientStatus===filter);const rows=cs.map(c=>{const l=lifecycleOf(c),n=nextBooking(c.email),pkg=activePackage(c.email),open=clientData(c.email).invoices.filter(x=>x.status==="open"||x.status==="overdue").reduce((s,x)=>s+Number(x.totalCents||0),0);return `<tr><td><span class="name">${esc(c.name)}</span><div class="sub">${esc(c.email)}</div></td><td>${clientStatusBadge(l.clientStatus)}</td><td>${esc(stages[boardBucket(c)]?.title||"—")}</td><td>${n?esc(dt(n.start)):"—"}</td><td>${pkg?`${esc(pkg.productName)}<div class="sub">${pkg.remaining}/${pkg.total} offen</div>`:"—"}</td><td>${open?money(open):"—"}</td><td><button class="mini" data-open-client="${esc(c.email)}">Akte öffnen</button></td></tr>`});$("#clientsTable").innerHTML=cs.length?table(["Kund:in","Status","Phase","Nächster Termin","Package","Offen",""],rows):`<div class="empty">Keine Kund:innen gefunden.</div>`;bindClientOpeners()}
  $("#clientSearch").addEventListener("input",()=>data&&renderClients());$("#clientStatusFilter").addEventListener("change",()=>data&&renderClients());

  function bindClientOpeners(){$$('[data-open-client]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.stopPropagation();openClient(b.dataset.openClient)})})}
  function openClient(email){const c=customerUniverse().find(x=>x.email===normEmail(email));if(!c)return;currentRecordEmail=c.email;currentRecordTab='overview';$("#recordName").textContent=c.name;$("#recordEmail").textContent=c.email;$("#recordStatus").value=lifecycleOf(c).clientStatus;$$('[data-record-tab]').forEach(b=>b.classList.toggle('active',b.dataset.recordTab==='overview'));renderRecord();$("#clientDialog").showModal()}
  $("#clientDialogClose").addEventListener('click',()=>$("#clientDialog").close());$$('[data-record-tab]').forEach(b=>b.addEventListener('click',()=>{currentRecordTab=b.dataset.recordTab;$$('[data-record-tab]').forEach(x=>x.classList.toggle('active',x===b));renderRecord()}));
  $("#recordStatus").addEventListener('change',()=>{const status=$("#recordStatus").value,stage=status==='active'?'active':status==='paused'?'paused':status==='completed'?'completed':'inquiry';setLifecycle(currentRecordEmail,{clientStatus:status,journeyStage:stage},'in der Klientenakte');renderAll();renderRecord()});
  function renderRecord(){const c=customerUniverse().find(x=>x.email===currentRecordEmail);if(!c)return;const cd=clientData(c.email),l=lifecycleOf(c),n=nextBooking(c.email),pkg=activePackage(c.email);if(currentRecordTab==='overview'){$("#recordContent").innerHTML=`<div class="context-grid"><div class="context-card"><span>Status</span><strong>${lifecycleLabel(l.clientStatus)}</strong></div><div class="context-card"><span>Nächster Termin</span><strong>${n?esc(dt(n.start)):"Keiner geplant"}</strong></div><div class="context-card"><span>Aktuelles Package</span><strong>${pkg?`${esc(pkg.productName)} · ${pkg.remaining}/${pkg.total}`:"Kein aktives Package"}</strong></div><div class="context-card"><span>Letzter Termin</span><strong>${lastPastBooking(c.email)?esc(dt(lastPastBooking(c.email).start)):"—"}</strong></div><div class="context-card"><span>Offene Rechnungen</span><strong>${money(cd.invoices.filter(x=>x.status==='open'||x.status==='overdue').reduce((s,x)=>s+Number(x.totalCents||0),0))}</strong></div><div class="context-card"><span>Journey-Phase</span><strong>${esc(stages[boardBucket(c)]?.title||"—")}</strong></div></div><div style="margin-top:18px"><p class="eyebrow">Letzte Aktivität</p>${activityHtml(c.email,6)}</div>`}
    if(currentRecordTab==='bookings')$("#recordContent").innerHTML=cd.bookings.length?table(["Termin","Beratung","Ort","Status"],cd.bookings.sort((a,b)=>new Date(b.start)-new Date(a.start)).map(x=>`<tr><td>${esc(dt(x.start))}</td><td>${esc(x.typeLabel)}</td><td>${esc(x.locationLabel)}</td><td>${x.status==='cancelled'?'Abgesagt':'Gebucht'}</td></tr>`)):`<div class="empty">Keine Termine.</div>`;
    if(currentRecordTab==='packages')$("#recordContent").innerHTML=cd.packages.length?table(["Package","Offen","Gültig","Kauf"],cd.packages.map(x=>`<tr><td>${esc(x.productName)}</td><td>${x.remaining}/${x.total}</td><td>${dateOnly(x.expiresAt)}</td><td>${x.purchaseAmountCents==null?'—':money(x.purchaseAmountCents,x.currency)}<div class="sub">${esc(x.purchaseStatus||'')}</div></td></tr>`)):`<div class="empty">Keine Packages.</div>`;
    if(currentRecordTab==='invoices')$("#recordContent").innerHTML=cd.invoices.length?table(["Rechnung","Betrag","Fällig","Status"],cd.invoices.map(x=>`<tr><td>${esc(x.invoiceNumber)}</td><td>${money(x.totalCents,x.currency)}</td><td>${dateOnly(x.dueDate)}</td><td>${statusLabel(x.status)}</td></tr>`)):`<div class="empty">Keine Rechnungen.</div>`;
    if(currentRecordTab==='forms')$("#recordContent").innerHTML=`<div class="empty"><strong>Intake & Consent ist vorbereitet, aber noch nicht aktiviert.</strong><br><br>Beratungsinhalte und Outcome-Maße kommen erst mit einem eigenen Datenschutz- und Sicherheitskonzept hinzu.</div>`;
    if(currentRecordTab==='activity')$("#recordContent").innerHTML=activityHtml(c.email,80);
  }
  function activitiesFor(email){const cd=clientData(email),items=[];loadLifecycle().activities.filter(x=>x.email===email).forEach(x=>items.push({at:x.at,title:x.summary,detail:x.detail||'CRM-Aktion'}));cd.bookings.forEach(x=>items.push({at:x.start,title:x.status==='cancelled'?'Termin abgesagt':'Termin',detail:`${x.typeLabel} · ${x.locationLabel}`}));cd.invoices.forEach(x=>items.push({at:x.invoiceDate||x.dueDate,title:`Rechnung ${x.invoiceNumber}`,detail:`${money(x.totalCents,x.currency)} · ${statusLabel(x.status)}`}));cd.packages.forEach(x=>items.push({at:x.purchasedAt||x.createdAt||x.expiresAt,title:`Package ${x.productName}`,detail:`${x.remaining}/${x.total} Einheiten offen`}));const backend=(data.activities||data.auditLog||data.audit||[]).filter(x=>normEmail(x.email||x.customerEmail)===email);backend.forEach(x=>items.push({at:x.createdAt||x.at||x.timestamp,title:x.summary||x.action||x.type||'Aktivität',detail:x.detail||''}));return items.filter(x=>x.at).sort((a,b)=>new Date(b.at)-new Date(a.at))}
  function activityHtml(email,limit){const a=activitiesFor(email).slice(0,limit);return a.length?`<div class="timeline">${a.map(x=>`<div class="timeline-item"><div class="timeline-mark"></div><div class="timeline-copy"><strong>${esc(x.title)}</strong><span>${esc(dt(x.at))}${x.detail?' · '+esc(x.detail):''}</span></div></div>`).join('')}</div>`:`<div class="empty">Noch keine Aktivität.</div>`}

  function renderBookings(){const filter=$("#bookingFilter").value,t=now();let rows=(data.bookings||[]).slice();if(filter==='upcoming')rows=rows.filter(x=>x.status==='booked'&&new Date(x.start).getTime()>=t);if(filter==='past')rows=rows.filter(x=>x.status==='booked'&&new Date(x.start).getTime()<t);if(filter==='cancelled')rows=rows.filter(x=>x.status==='cancelled');rows.sort((a,b)=>filter==='upcoming'?new Date(a.start)-new Date(b.start):new Date(b.start)-new Date(a.start));$("#bookingsTable").innerHTML=rows.length?table(["Termin","Kund:in","Berater","Beratung","Ort","Status","Aktion"],rows.map(x=>`<tr><td>${esc(dt(x.start))}</td><td><span class="name">${esc(x.name)}</span><div class="sub">${esc(x.email)}</div></td><td>${esc(x.advisorName||'Theophil Kroller')}</td><td>${esc(x.typeLabel)}${x.packageName?`<div class="sub">${esc(x.packageName)}</div>`:''}</td><td>${esc(x.locationLabel)}</td><td><span class="badge ${x.status==='cancelled'?'cancelled':'booked'}">${x.status==='cancelled'?'Abgesagt':new Date(x.start).getTime()<t?'Vergangen':'Gebucht'}</span></td><td>${x.status==='booked'?`<div class="row-actions"><button class="mini edit" data-booking-edit="${esc(x.eventId)}">Verschieben</button><button class="mini danger" data-booking-delete="${esc(x.eventId)}">Löschen</button></div>`:'—'}</td></tr>`)):`<div class="empty">Keine Termine in dieser Ansicht.</div>`;bindPowerActions()}
  $("#bookingFilter").addEventListener('change',()=>data&&renderBookings());
  function renderPackages(){const rows=(data.packages||[]).map(x=>`<tr><td><span class="name">${esc(x.customerName)}</span><div class="sub">${esc(x.customerEmail)}</div></td><td>${esc(x.advisorName||'Theophil Kroller')}</td><td><strong>${esc(x.productName)}</strong><div class="sub">${esc(x.reference||'')}</div></td><td><strong>${x.remaining}/${x.total}</strong>${Number(x.remaining)<=loadSettings().renewalRemaining?'<div class="sub" style="color:#99631E">Fortsetzung im Blick</div>':''}</td><td>${x.expiresAt?dateOnly(x.expiresAt):'—'}</td><td>${x.purchaseAmountCents===null?'—':money(x.purchaseAmountCents,x.currency)}<div class="sub">${esc(x.purchaseStatus||'')}</div></td><td><div class="row-actions"><button class="mini edit" data-package-edit="${x.creditId}">Bearbeiten</button>${Number(x.remaining)<=loadSettings().renewalRemaining?`<button class="mini" data-offer="${x.creditId}">Fortsetzung</button>`:''}</div></td></tr>`);$("#packagesTable").innerHTML=rows.length?table(["Kund:in","Berater","Package","Offen","Gültig bis","Kauf","Aktion"],rows):`<div class="empty">Noch keine Packages.</div>`;bindPowerActions();bindOfferButtons()}
  function renderInvoices(){const filter=$("#invoiceFilter").value;const rows=(data.invoices||[]).filter(x=>filter==='all'||x.status===filter);$("#invoicesTable").innerHTML=rows.length?table(["Rechnung","Kund:in","Berater","Betrag","Fällig","Status","Aktion"],rows.map(x=>{let actions=`<button class="mini" data-pdf="${x.id}">PDF</button><button class="mini edit" data-due-edit="${x.id}">Zahlungsziel ändern</button>`;if(x.status==='open'||x.status==='overdue')actions+=`<button class="mini pay" data-paid="${x.id}">Bezahlt markieren</button>`;if(x.status==='overdue')actions+=`<button class="mini remind" data-remind="${x.id}">Erinnerung senden</button>`;if(x.status==='paid')actions+=`<button class="mini" data-open="${x.id}">Wieder öffnen</button>`;return `<tr><td><span class="name">${esc(x.invoiceNumber||'—')}</span><div class="sub">${dateOnly(x.invoiceDate)}</div></td><td>${esc(x.customerName)}<div class="sub">${esc(x.customerEmail)}</div></td><td>${esc(x.advisorName||'Theophil Kroller')}</td><td><strong>${money(x.totalCents,x.currency)}</strong></td><td>${dateOnly(x.dueDate)}</td><td><span class="badge ${esc(x.status)}">${esc(statusLabel(x.status))}</span></td><td><div class="row-actions">${actions}</div></td></tr>`})): `<div class="empty">Keine Rechnungen in dieser Ansicht.</div>`;bindInvoiceActions();bindPowerActions()}
  $("#invoiceFilter").addEventListener('change',()=>data&&renderInvoices());

  function findBooking(id){return(data.bookings||[]).find(x=>x.eventId===id&&x.status==='booked')}function findPackage(id){return(data.packages||[]).find(x=>Number(x.creditId)===Number(id))}function findInvoice(id){return(data.invoices||[]).find(x=>Number(x.id)===Number(id))}
  function viennaParts(iso){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
  function viennaIso(date,time){const probe=new Date(`${date}T12:00:00Z`);const name=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Vienna',timeZoneName:'shortOffset'}).formatToParts(probe).find(x=>x.type==='timeZoneName')?.value||'GMT+1';const m=name.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);const off=m?`${m[1]}${String(m[2]).padStart(2,'0')}:${m[3]||'00'}`:'+01:00';return new Date(`${date}T${time}:00${off}`).toISOString()}
  function openEditor(ctx){editCtx=ctx;$("#editEyebrow").textContent=ctx.eyebrow||'Änderung';$("#editTitle").textContent=ctx.title;$("#editSubtitle").textContent=ctx.subtitle||'';$("#editFields").innerHTML=ctx.fields.map(f=>`<label class="edit-field"${f.full?' style="grid-column:1/-1"':''}>${esc(f.label)}<input data-edit-key="${esc(f.key)}" type="${esc(f.type||'text')}" value="${esc(f.value??'')}" ${f.min!==undefined?`min="${f.min}"`:''} ${f.step!==undefined?`step="${f.step}"`:''}></label>`).join('');$("#emailPreview").classList.remove('active');$("#editState").textContent='';$$('[data-edit-key]').forEach(i=>i.addEventListener('input',refreshEditState));refreshEditState();$("#editDialog").showModal()}
  function editValues(){const o={};$$('[data-edit-key]').forEach(i=>o[i.dataset.editKey]=i.value);return o}function changes(){if(!editCtx)return[];const v=editValues();return editCtx.fields.filter(f=>String(v[f.key]??'')!==String(f.value??'')).map(f=>({label:f.label,old:f.display?f.display(f.value):String(f.value||'—'),now:f.display?f.display(v[f.key]):String(v[f.key]||'—')}))}
  function refreshEditState(){const c=changes(),dirty=c.length>0;$("#saveOnly").disabled=!dirty;$("#saveNotify").disabled=!dirty;$("#changeHeadline").textContent=dirty?`${c.length} ungespeicherte Änderung${c.length===1?'':'en'}`:'Keine Änderungen vorgenommen';$("#changeList").innerHTML=c.map(x=>`<div class="change-row"><span>${esc(x.label)}:</span><span class="old-value">${esc(x.old)}</span><span>→</span><span class="new-value">${esc(x.now)}</span></div>`).join('');$("#editState").textContent=dirty?'Noch nicht gespeichert':''}
  async function saveEditor(withEmail){if(!editCtx||!changes().length)return;const v=editValues(),c=changes();$("#saveOnly").disabled=true;$("#saveNotify").disabled=true;$("#editState").textContent='Speichere …';try{await editCtx.save(v);if(editCtx.email)logLocal(editCtx.email,'edit',editCtx.title,c.map(x=>`${x.label}: ${x.old} → ${x.now}`).join(' · '));$("#editState").textContent='Änderungen gespeichert ✓';if(withEmail){$("#emailPreviewText").innerHTML=`<div class="email-preview-text">Die Kundin bzw. der Kunde erhält eine Nachricht über:<br><br>${c.map(x=>`<strong>${esc(x.label)}</strong>: ${esc(x.old)} → ${esc(x.now)}`).join('<br>')}<br><br><strong>Es wurde noch keine E-Mail gesendet.</strong></div>`;$("#emailPreview").classList.add('active')}else{await load();$("#editDialog").close()}}catch(e){alert(e.message);refreshEditState()}}
  $("#editForm").addEventListener('submit',e=>{e.preventDefault();saveEditor(false)});$("#saveNotify").addEventListener('click',()=>saveEditor(true));$("#editClose").addEventListener('click',()=>$("#editDialog").close());$("#editCancel").addEventListener('click',()=>$("#editDialog").close());$("#emailCancel").addEventListener('click',()=>$("#emailPreview").classList.remove('active'));$("#emailConfirm").addEventListener('click',async()=>{if(!editCtx?.notify)return;const b=$("#emailConfirm");b.disabled=true;b.textContent='Sende …';try{await editCtx.notify();if(editCtx.email)logLocal(editCtx.email,'email','Kund:in über Änderung informiert');$("#emailPreviewText").innerHTML='<strong>E-Mail wurde gesendet ✓</strong>';setTimeout(async()=>{await load();$("#editDialog").close()},700)}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='E-Mail jetzt senden'}});

  function bindPowerActions(){
    $$('[data-booking-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findBooking(b.dataset.bookingEdit);if(!x)return;const p=viennaParts(x.start);openEditor({eyebrow:'Termin',title:'Termin verschieben',subtitle:`${x.name} · aktuell ${dt(x.start)}`,email:x.email,fields:[{key:'date',label:'Neues Datum',type:'date',value:p.date,display:dateOnly},{key:'time',label:'Neue Uhrzeit',type:'time',value:p.time,step:300}],save:v=>post('/admin/booking/update',{eventId:x.eventId,start:viennaIso(v.date,v.time)}),notify:()=>post('/admin/booking/notify',{eventId:x.eventId})})})});
    $$('[data-booking-delete]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{const x=findBooking(b.dataset.bookingDelete);if(!x||!confirm(`Termin von ${x.name} am ${dt(x.start)} wirklich löschen?`))return;const notify=confirm('Soll der Kunde zusätzlich per E-Mail über die Absage informiert werden?');b.disabled=true;try{await post('/admin/booking/delete',{eventId:x.eventId,notifyCustomer:notify});logLocal(x.email,'booking','Termin gelöscht',dt(x.start));await load()}catch(e){alert(e.message)}finally{b.disabled=false}})});
    $$('[data-package-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findPackage(b.dataset.packageEdit);if(!x)return;openEditor({eyebrow:'Package',title:'Package bearbeiten',subtitle:`${x.customerName} · ${x.productName}`,email:x.customerEmail,fields:[{key:'remaining',label:'Offene Einheiten',type:'number',value:String(x.remaining),min:0},{key:'total',label:'Gesamte Einheiten',type:'number',value:String(x.total),min:0},{key:'expiresAt',label:'Gültig bis',type:'date',value:x.expiresAt?String(x.expiresAt).slice(0,10):'',display:v=>v?dateOnly(v):'ohne Ablaufdatum'}],save:v=>{const remaining=Number(v.remaining),total=Number(v.total);if(!Number.isInteger(remaining)||!Number.isInteger(total)||remaining<0||total<0||remaining>total)throw new Error('Offene Einheiten müssen zwischen 0 und der Gesamtzahl liegen.');return post('/admin/package/update',{creditId:x.creditId,remaining,total,expiresAt:v.expiresAt||null})},notify:()=>post('/admin/package/notify',{creditId:Number(x.creditId)})})})});
    $$('[data-due-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findInvoice(b.dataset.dueEdit);if(!x)return;openEditor({eyebrow:'Rechnung',title:'Zahlungsziel ändern',subtitle:`${x.invoiceNumber} · ${x.customerName}`,email:x.customerEmail,fields:[{key:'dueDate',label:'Neues Zahlungsziel',type:'date',value:x.dueDate||'',display:dateOnly}],save:v=>post('/admin/invoice/update-due',{invoiceId:x.id,dueDate:v.dueDate}),notify:()=>post('/admin/invoice/notify',{invoiceId:Number(x.id)})})})})
  }
  function bindInvoiceActions(){
    $$('[data-remind]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{if(!confirm('Zahlungserinnerung jetzt senden?'))return;const x=findInvoice(b.dataset.remind);b.disabled=true;try{await post('/admin/invoice/remind',{invoiceId:Number(b.dataset.remind)});if(x)logLocal(x.customerEmail,'email','Zahlungserinnerung gesendet',x.invoiceNumber);await load()}catch(e){alert(e.message)}finally{b.disabled=false}})});
    $$('[data-paid]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{const x=findInvoice(b.dataset.paid);b.disabled=true;try{await post('/admin/invoice/mark-paid',{invoiceId:Number(b.dataset.paid),paid:true});if(x)logLocal(x.customerEmail,'invoice','Rechnung als bezahlt markiert',x.invoiceNumber);await load()}catch(e){alert(e.message)}finally{b.disabled=false}})});
    $$('[data-open]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{if(!confirm('Diese Rechnung wieder als offen markieren?'))return;b.disabled=true;try{await post('/admin/invoice/mark-paid',{invoiceId:Number(b.dataset.open),paid:false});await load()}catch(e){alert(e.message)}finally{b.disabled=false}})});
    $$('[data-pdf]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{b.disabled=true;try{const r=await fetch(API+'/admin/invoice-pdf?id='+encodeURIComponent(b.dataset.pdf),{headers:{Authorization:'Bearer '+session}});if(!r.ok)throw new Error('PDF konnte nicht geladen werden.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Rechnung.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){alert(e.message)}finally{b.disabled=false}})})
  }

  function openInquiry(){$("#inquiryForm").reset();$("#inquiryDialog").showModal()}$("#newInquiryBtn").addEventListener('click',openInquiry);$("#journeyAddBtn").addEventListener('click',openInquiry);$("#inquiryClose").addEventListener('click',()=>$("#inquiryDialog").close());$("#inquiryCancel").addEventListener('click',()=>$("#inquiryDialog").close());$("#inquiryForm").addEventListener('submit',e=>{e.preventDefault();const life=loadLifecycle(),email=normEmail($("#inqEmail").value);if(customerUniverse().some(c=>c.email===email)){alert('Diese E-Mail ist bereits im CRM vorhanden.');return}life.prospects.push({id:uid(),name:$("#inqName").value.trim(),email,source:$("#inqSource").value,stage:$("#inqStage").value,createdAt:new Date().toISOString()});saveLifecycle(life);logLocal(email,'inquiry','Neue Anfrage erfasst',$("#inqSource").value);$("#inquiryDialog").close();renderAll();switchView('journey')});

  function bindOfferButtons(){$$('[data-offer]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openOffer(b.dataset.offer))})}
  function openOffer(creditId){const x=findPackage(creditId);if(!x)return;offerCtx=x;$("#offerClient").textContent=`${x.customerName} · ${x.productName} · ${x.remaining}/${x.total} Einheiten offen`;const base=x.purchaseAmountCents!=null?Number(x.purchaseAmountCents)/100:0;$("#offerBasePrice").value=base||'';$("#offerDiscount").value=loadSettings().discount||0;updateOfferPrice();updateOfferEmail();$("#offerDialog").showModal()}
  function updateOfferPrice(){const base=Number($("#offerBasePrice").value||0),disc=Number($("#offerDiscount").value||0);$("#offerFinalPrice").value=(base*(1-disc/100)).toFixed(0);updateOfferEmail()}
  function updateOfferEmail(){if(!offerCtx)return;const final=Number($("#offerFinalPrice").value||0),disc=Number($("#offerDiscount").value||0),type=$("#offerType").selectedOptions[0]?.textContent||'Fortsetzung';$("#offerEmailText").value=`Hallo ${String(offerCtx.customerName||'').split(' ')[0]},\n\nbei deinem aktuellen Package ist nur noch ${offerCtx.remaining} Sitzung${Number(offerCtx.remaining)===1?'':'en'} offen. Wenn du die Begleitung direkt fortsetzen möchtest, können wir den nächsten Schritt gern schon jetzt planen.\n\n${type}${final?` · ${euro(final)}`:''}${disc?` (${disc} % Fortsetzungsbonus)`:''}\n\nWenn das für dich passt, antworte mir einfach kurz – dann kümmere ich mich um den Rest.\n\nLiebe Grüße\nTheophil`}
  ['offerBasePrice','offerDiscount'].forEach(id=>$("#"+id).addEventListener('input',updateOfferPrice));['offerFinalPrice','offerType'].forEach(id=>$("#"+id).addEventListener('input',updateOfferEmail));$("#offerClose").addEventListener('click',()=>$("#offerDialog").close());$("#copyOfferBtn").addEventListener('click',async()=>{await navigator.clipboard.writeText($("#offerEmailText").value);$("#copyOfferBtn").textContent='Kopiert ✓';setTimeout(()=>$("#copyOfferBtn").textContent='Text kopieren',1200)});$("#openMailBtn").addEventListener('click',()=>{if(!offerCtx)return;if(!confirm('E-Mail-Entwurf jetzt im Mailprogramm öffnen? Es wird noch nichts automatisch versendet.'))return;const subject=encodeURIComponent('Fortsetzung deiner Begleitung');const body=encodeURIComponent($("#offerEmailText").value);window.location.href=`mailto:${encodeURIComponent(offerCtx.customerEmail)}?subject=${subject}&body=${body}`;logLocal(offerCtx.customerEmail,'offer','Fortsetzungsangebot vorbereitet',`${$("#offerFinalPrice").value||'—'} EUR`);const life=loadLifecycle();life.offers.unshift({id:uid(),email:normEmail(offerCtx.customerEmail),creditId:offerCtx.creditId,amount:$("#offerFinalPrice").value,createdAt:new Date().toISOString(),status:'prepared'});saveLifecycle(life)});

  function renderSettings(){const s=loadSettings();$("#settingDormantDays").value=s.dormantDays;$("#settingRenewalRemaining").value=s.renewalRemaining;$("#settingDiscount").value=s.discount}
  $("#saveSettingsBtn").addEventListener('click',()=>{const s={dormantDays:Number($("#settingDormantDays").value||60),renewalRemaining:Number($("#settingRenewalRemaining").value||1),discount:Number($("#settingDiscount").value||0)};saveSettings(s);message($("#settingsMsg"),'Einstellungen gespeichert.');renderAll()});
  $("#exportLifecycleBtn").addEventListener('click',()=>{const payload={version:1,exportedAt:new Date().toISOString(),lifecycle:loadLifecycle(),settings:loadSettings()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beziehungsdynamiken-crm-status-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)});
  $("#importLifecycleInput").addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const x=JSON.parse(await file.text());if(!x.lifecycle)throw new Error('Ungültige Datei');saveLifecycle(x.lifecycle);if(x.settings)saveSettings(x.settings);message($("#settingsMsg"),'Statusdaten importiert.');renderAll()}catch(err){message($("#settingsMsg"),'Import fehlgeschlagen: '+err.message,'err')}finally{e.target.value=''}});

  (async()=>{if(!API){showLogin();message($("#loginMsg"),'Die API-Adresse ist noch nicht konfiguriert.','err');return}const magic=await consumeMagicLink();if(session||magic)await load();else showLogin()})();
})();
