(function(){
  "use strict";
  const root=document;
  const API=(window.BD_BOOKING_CONFIG?.apiBaseUrl||"").replace(/\/$/,"");
  const SESSION_KEY="bd_admin_session_v1";
  let session=sessionStorage.getItem(SESSION_KEY)||"";
  let data=null,currentRecordEmail="",currentRecordTab="overview",editCtx=null,offerCtx=null,salesCtx=null,cancelCtx=null;
  let dashboardWeekOffset=0,bookingWeekOffset=0;
  let pendingBankSource="",pendingBankRowCount=0;
  let crmState={byEmail:{},prospects:[],activities:[],offers:[],settings:{dormantDays:60,renewalRemaining:1,discount:0}};
  const $=s=>root.querySelector(s), $$=s=>[...root.querySelectorAll(s)];
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const normEmail=s=>String(s||"").trim().toLowerCase();
  const visibleContactEmail=s=>{const raw=String(s||"").trim();if(/^__bd(?:test|13)__:/i.test(raw)){const parts=raw.split(":");try{return decodeURIComponent(parts.slice(2).join(":"))||raw}catch(_){return raw}}return raw};
  const money=(cents,currency="EUR")=>new Intl.NumberFormat("de-AT",{style:"currency",currency:currency||"EUR"}).format(Number(cents||0)/100);
  const euro=n=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(Number(n||0));
  const dt=x=>x?new Intl.DateTimeFormat("de-AT",{timeZone:"Europe/Vienna",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(x)):"—";
  const dateOnly=x=>{if(!x)return"—";const s=String(x).slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[y,m,d]=s.split("-");return `${d}.${m}.${y}`}return dt(x).split(",")[0]};
  const now=()=>Date.now();
  const uid=()=>"p_"+Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  const statusLabel=s=>({paid:"Bezahlt",open:"Offen",overdue:"Überfällig",test:"Offen",void:"Storniert",cancelled:"Storniert",refunded:"Erstattet"})[s]||s;
  const invoicePayable=x=>!!x&&!["paid","void","cancelled","canceled","refunded"].includes(String(x.status||"").toLowerCase());
  const lifecycleLabel=s=>({active:"Aktiv",paused:"Pausiert",completed:"Abgeschlossen",prospect:"Interessent:in"})[s]||s;
  const paymentLabel=s=>({cash:"Bar",bank_transfer:"Überweisung",stripe:"Stripe",sumup:"SumUp / Kartenzahlung",card:"Karte",manual:"Manuell",other:"Sonstiges"})[s]||s||"—";
  const salesStatusLabel=s=>({offered:"Angebot gesendet",prepared:"Vorbereitet",sent:"Rechnung gesendet",paid:"Bezahlt",active:"Aktiv",payment_failed:"Zahlung fehlgeschlagen",cancelled:"Storniert"})[s]||s||"—";
  const b9=()=>data?.build9||{catalog:[],wallet:[],salesOrders:[],subscriptions:[],billing:[],bankImport:{}};
  const customerByEmail=email=>customerUniverse().find(x=>x.email===normEmail(email));
  const build9Rows=(key,email)=>{const c=customerByEmail(email);return c?(b9()[key]||[]).filter(x=>Number(x.customer_id??x.customerId)===Number(c.id)||normEmail(x.email)===c.email):[]}
  const walletBalance=email=>{const c=customerByEmail(email),w=(b9().wallet||[]).find(x=>Number(x.customer_id)===Number(c?.id)||normEmail(x.email)===normEmail(email));return Number(w?.balance_cents||w?.balanceCents||0)};

  function hydrateCrm(){
    const crm=data?.crm||{},byEmail={};
    (crm.lifecycle||[]).forEach(x=>{const email=normEmail(x.email||x.customerEmail);if(email)byEmail[email]={journeyStage:x.journeyStage||x.journey_stage||"active",clientStatus:x.clientStatus||x.client_status||"active",updatedAt:x.updatedAt||x.updated_at||null}});
    crmState={
      byEmail,
      prospects:(crm.inquiries||[]).map(x=>({id:x.id,name:x.name,email:normEmail(x.email),source:x.source||"",stage:x.journeyStage||x.journey_stage||"inquiry",status:x.status||"open",createdAt:x.createdAt||x.created_at,updatedAt:x.updatedAt||x.updated_at})),
      activities:(crm.activities||[]).map(x=>({id:x.id,email:normEmail(x.email||x.customerEmail),type:x.eventType||x.event_type||x.type,summary:x.summary||"Aktivität",detail:x.detail||"",at:x.createdAt||x.created_at||x.at})),
      offers:(crm.offers||[]),
      settings:{...{dormantDays:60,renewalRemaining:1,discount:0},...(crm.settings||{})}
    };
  }
  function loadLifecycle(){return crmState}
  function saveLifecycle(x){crmState={...crmState,...x}}
  function loadSettings(){return {...{dormantDays:60,renewalRemaining:1,discount:0},...(crmState.settings||{})}}
  function saveSettings(x){crmState.settings={...loadSettings(),...x};post("/admin/crm/settings",crmState.settings).catch(e=>console.error("CRM settings save failed",e))}
  function logLocal(email,type,summary,detail=""){
    email=normEmail(email);const x=loadLifecycle();x.activities.unshift({id:uid(),email,type,summary,detail,at:new Date().toISOString()});x.activities=x.activities.slice(0,1200);saveLifecycle(x);
    post("/admin/crm/activity",{email,eventType:type,summary,detail}).catch(e=>console.error("CRM activity save failed",e));
  }
  function setLifecycle(email,patch,reason=""){
    email=normEmail(email);if(!email)return;const x=loadLifecycle(),old=x.byEmail[email]||{};x.byEmail[email]={...old,...patch,updatedAt:new Date().toISOString()};saveLifecycle(x);
    const before=old.clientStatus||old.journeyStage||"—",after=patch.clientStatus||patch.journeyStage||before;
    const c=(data?.customers||[]).find(y=>normEmail(y.email)===email)||customerUniverse().find(y=>y.email===email)||{};
    post("/admin/crm/lifecycle",{customerId:c.id||null,email,name:c.name||email,journeyStage:x.byEmail[email].journeyStage||"active",clientStatus:x.byEmail[email].clientStatus||"active",reason}).catch(e=>{console.error("Lifecycle save failed",e);alert("Status konnte im Worker nicht gespeichert werden: "+e.message)});
    if(before!==after)logLocal(email,"status",`Status geändert: ${lifecycleLabel(before)} → ${lifecycleLabel(after)}`,reason);
  }

  async function api(path,opts={}){
    const headers={...(opts.headers||{})}; if(session)headers.Authorization="Bearer "+session;
    const r=await fetch(API+path,{...opts,headers});const type=r.headers.get("content-type")||"";const body=type.includes("application/json")?await r.json():await r.text();
    if(r.status===401){session="";sessionStorage.removeItem(SESSION_KEY);showLogin();throw new Error("Sitzung abgelaufen. Bitte erneut einloggen.")}
    if(!r.ok||body?.ok===false)throw new Error(body?.error||"Die Anfrage konnte nicht verarbeitet werden.");return body;
  }
  async function post(path,body){return api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}
  function message(el,text,kind="ok"){el.className="notice "+kind;el.textContent=text}
  function showLogin(){$("#loginView").classList.remove("hidden");$("#appShell").classList.add("hidden")}
  function showApp(){$("#loginView").classList.add("hidden");$("#appShell").classList.remove("hidden")}

  $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const btn=$("#loginBtn"),email=$("#loginEmail").value.trim();btn.disabled=true;btn.textContent="Sende …";try{const r=await fetch(API+"/admin/request-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Login-Link konnte nicht versendet werden.");message($("#loginMsg"),x.message||"Wenn diese Adresse freigeschaltet ist, wurde ein Login-Link versendet.")}catch(err){message($("#loginMsg"),err.message,"err")}finally{btn.disabled=false;btn.textContent="Login-Link senden"}});
  async function consumeMagicLink(){const u=new URL(location.href),token=u.searchParams.get("login");if(!token)return false;history.replaceState({},document.title,location.pathname);try{const r=await fetch(API+"/admin/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"Login-Link ungültig.");session=x.sessionToken;sessionStorage.setItem(SESSION_KEY,session);return true}catch(err){showLogin();message($("#loginMsg"),err.message,"err");return false}}
  $("#logoutBtn").addEventListener("click",async()=>{try{await api("/admin/logout",{method:"POST"})}catch(e){}session="";sessionStorage.removeItem(SESSION_KEY);showLogin()});
  $("#refreshBtn").addEventListener("click",()=>load());

  const viewMeta={
    dashboard:["Praxis-Cockpit","Dashboard","Was heute Aufmerksamkeit braucht – und was als Nächstes kommt."],
    journey:["Client Journey","Klientenreise","Vom ersten Kontakt bis zur abgeschlossenen Begleitung."],
    clients:["Klient:innen","Klient:innen","Akte öffnen und von hier aus Termine, Sitzungen, Angebote und Honorarnoten steuern."],
    bookings:["Kalender","Termine","Buchungen verwalten, verschieben und nachvollziehen."],
    packages:["Begleitpakete","Packages","Einheiten, Gültigkeit und Fortsetzung im Blick."],
    programs:["Programme & Gruppen","Programme & Gruppen","Gruppen, Workshops und mehrteilige Angebote ohne Codeänderung verwalten."],
    invoices:["Honorarnoten","Honorarnoten","Zahlungsstatus, Fristen und Zahlungen auf einen Blick."],
    vault:["Secure Practice Vault","Dokumentation","Lokale, verschlüsselte Beratungsdokumentation."],
    settings:["Praxis-CRM","Administration","Sicherheit, Lifecycle-Regeln und Datensicherung."]
  };
  function switchView(name){
    $$(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));
    const m=viewMeta[name]||viewMeta.dashboard;$("#viewEyebrow").textContent=m[0];$("#viewTitle").textContent=m[1];$("#viewSubtitle").textContent=m[2];
    $("#newInquiryBtn").style.display=(name==="journey"||name==="dashboard")?"":"none";
  }
  $$(".nav-item[data-view]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));

  async function load(){
    if(!session){showLogin();return}$("#appShell").classList.add("loading");
    try{data=await api("/admin/dashboard");hydrateCrm();showApp();$("#adminIdentity").textContent=data.admin?.email||"Administrator";renderAll();document.dispatchEvent(new CustomEvent('bd:cloud-snapshot',{detail:{customers:data.customers||[],bookings:data.bookings||[]}}))}catch(err){if(session)alert(err.message)}finally{$("#appShell").classList.remove("loading")}
  }

  function customerUniverse(){
    const map=new Map();const add=(email,name,id=null,backend=true,contactEmail=null,isSandboxProfile=false)=>{const key=normEmail(email);if(!key)return;const visible=visibleContactEmail(contactEmail||email);const old=map.get(key)||{email:key,contactEmail:visible,name:name||visible||email,id:null,backend:false,isSandboxProfile:false};map.set(key,{...old,name:name||old.name,contactEmail:visibleContactEmail(contactEmail||old.contactEmail||email),id:id||old.id,backend:old.backend||backend,isSandboxProfile:old.isSandboxProfile||!!isSandboxProfile})};
    (data?.customers||[]).forEach(x=>add(x.email,x.name,x.id,true,x.contactEmail||x.email,x.isSandboxProfile));
    (data?.bookings||[]).forEach(x=>add(x.customerIdentityEmail||x.email,x.name,x.customerId||null,true,x.customerContactEmail||x.email,!!x.isSandboxProfile||!!x.customerIdentityEmail&&/^__bd(?:test|13)__:/i.test(String(x.customerIdentityEmail))));
    (data?.packages||[]).forEach(x=>add(x.customerEmail,x.customerName,x.customerId,true,x.customerContactEmail||x.customerEmail,x.isSandboxProfile));
    (data?.invoices||[]).forEach(x=>add(x.customerEmail,x.customerName,x.customerId,true,x.customerContactEmail||x.customerEmail,x.isSandboxProfile));
    const life=loadLifecycle();life.prospects.forEach(p=>{if(!map.has(normEmail(p.email)))add(p.email,p.name,p.id,false,p.email,false)});return [...map.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name),"de"));
  }
  function clientData(email){email=normEmail(email);return {bookings:(data?.bookings||[]).filter(x=>normEmail(x.customerIdentityEmail||x.email)===email),packages:(data?.packages||[]).filter(x=>normEmail(x.customerEmail)===email),invoices:(data?.invoices||[]).filter(x=>normEmail(x.customerEmail)===email)}}
  function lifecycleOf(client){
    const life=loadLifecycle(),manual=life.byEmail[client.email]||{},prospect=life.prospects.find(p=>normEmail(p.email)===client.email),cd=clientData(client.email),t=now();
    if(!client.backend){return {journeyStage:prospect?.stage||manual.journeyStage||"inquiry",clientStatus:"prospect",manual:true}}
    if(manual.clientStatus==="completed")return {...manual,journeyStage:"completed",clientStatus:"completed"};
    if(manual.clientStatus==="paused")return {...manual,journeyStage:"paused",clientStatus:"paused"};
    if(["inquiry","consultation","waiting"].includes(manual.journeyStage))return {...manual,journeyStage:manual.journeyStage==="waiting"?"consultation":manual.journeyStage,clientStatus:"prospect"};
    const upcoming=cd.bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()>=t);const past=cd.bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()<t);const activePkg=cd.packages.some(x=>Number(x.remaining)>0&&(!x.expiresAt||new Date(x.expiresAt).getTime()>t));
    if(upcoming.length===1&&!past.length&&!activePkg)return {...manual,journeyStage:"consultation",clientStatus:"prospect"};
    if(upcoming.length||activePkg)return {...manual,journeyStage:"active",clientStatus:"active"};
    if(past.length||cd.packages.length)return {...manual,journeyStage:"paused",clientStatus:"paused"};
    return {...manual,journeyStage:"inquiry",clientStatus:"prospect"};
  }
  function boardBucket(client){const l=lifecycleOf(client);if(l.clientStatus==="completed")return"completed";if(l.clientStatus==="paused")return"paused";return l.journeyStage==="waiting"?"consultation":(l.journeyStage||"inquiry")}

  function renderAll(){renderStats();renderAttention();renderRenewals();renderNext();renderJourney();renderClients();renderBookings();renderPackages();renderInvoices();renderSettings()}
  function renderStats(){
    const o=data.overview||{},clients=customerUniverse(),counts={active:0,paused:0,completed:0,prospect:0};clients.forEach(c=>counts[lifecycleOf(c).clientStatus]=(counts[lifecycleOf(c).clientStatus]||0)+1);
    $("#statToday").textContent=o.todayBookings??0;$("#statWeek").textContent=o.next7Bookings??0;$("#statActiveClients").textContent=counts.active;$("#statLifecycle").textContent=`${counts.paused} pausiert · ${counts.completed} abgeschlossen`;$("#statOpen").textContent=money(o.openInvoicesCents||0);$("#statOverdue").textContent=`davon ${money(o.overdueInvoicesCents||0)} überfällig`;$("#statTest").textContent=`Sandbox/Test: ${money(o.testInvoicesCents||0)}`;$("#navJourneyCount").textContent=clients.length;
  }
  function lastPastBooking(email){return clientData(email).bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()<now()).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]}
  function nextBooking(email){return clientData(email).bookings.filter(x=>x.status==="booked"&&new Date(x.start).getTime()>=now()).sort((a,b)=>new Date(a.start)-new Date(b.start))[0]}
  function activePackage(email){return clientData(email).packages.filter(x=>Number(x.remaining)>0&&(!x.expiresAt||new Date(x.expiresAt).getTime()>now())).sort((a,b)=>Number(a.remaining)-Number(b.remaining))[0]}
  function renderAttention(){
    const items=[],settings=loadSettings();
    (data.invoices||[]).filter(x=>x.status==="overdue").forEach(x=>items.push({kind:"red",title:`${x.invoiceNumber} · ${x.customerName}`,text:`${money(x.totalCents,x.currency)} · fällig seit ${dateOnly(x.dueDate)}`,action:`<button class="mini remind" data-remind="${x.id}">Erinnerung senden</button>`}));
    (data.bookings||[]).filter(x=>x.status==="booked"&&x.confirmationEmailSent===false).forEach(x=>items.push({kind:"red",title:`Bestätigung fehlt · ${x.name}`,text:`Termin ${dt(x.start)}`,action:""}));
    customerUniverse().filter(c=>lifecycleOf(c).clientStatus==="active").forEach(c=>{if(nextBooking(c.email))return;const last=lastPastBooking(c.email);if(!last)return;const days=Math.floor((now()-new Date(last.start).getTime())/86400000);if(days>=settings.dormantDays)items.push({kind:"orange",title:`${c.name} · kein Folgetermin`,text:`Letzter Termin vor ${days} Tagen`,action:`<button class="mini" data-open-client="${esc(c.email)}">Akte öffnen</button>`})});
    const openBank=(data.invoices||[]).filter(x=>(x.status==='open'||x.status==='overdue')&&x.dbStatus!=='test');const bi=b9().bankImport||{},staleDays=Number(bi.staleDays||5),lastMs=bi.lastImportedAt?new Date(bi.lastImportedAt).getTime():0,ageDays=lastMs?Math.floor((now()-lastMs)/86400000):9999;if(openBank.length&&ageDays>=staleDays)items.push({kind:'orange',title:'Geschäftskonto abgleichen',text:bi.lastImportedAt?`Letzter CSV-Import ${dateOnly(bi.lastImportedAt)} · ${openBank.length} offene Rechnung${openBank.length===1?'':'en'}`:`Noch kein Bank-CSV-Import protokolliert · ${openBank.length} offene Rechnung${openBank.length===1?'':'en'}`,action:'<button class="mini" data-bank-jump>CSV importieren</button>'});
    $("#attentionCount").textContent=items.length;$("#attention").innerHTML=items.length?items.map(i=>`<div class="attention-item ${i.kind}"><div><strong>${esc(i.title)}</strong><span>${esc(i.text)}</span></div>${i.action}</div>`).join(""):`<div class="empty">Aktuell nichts Dringendes. ✓</div>`;bindInvoiceActions();bindClientOpeners();$$('[data-bank-jump]').forEach(x=>x.addEventListener('click',()=>{switchView('invoices');setTimeout(()=>$('#bankCsvInput')?.click(),50)}));
  }
  function renewalCandidates(){const s=loadSettings();return (data.packages||[]).filter(x=>Number(x.remaining)<=Number(s.renewalRemaining)&&Number(x.remaining)>=0&&(x.purchaseStatus||"")!=="test").sort((a,b)=>Number(a.remaining)-Number(b.remaining))}
  function renderRenewals(){const rows=renewalCandidates();$("#renewals").innerHTML=rows.length?rows.slice(0,7).map(x=>`<div class="renewal-item"><div><strong>${esc(x.customerName)} · ${esc(x.productName)}</strong><span>${x.remaining}/${x.total} Einheiten offen${nextBooking(x.customerEmail)?` · nächster Termin ${dt(nextBooking(x.customerEmail).start)}`:" · kein Folgetermin"}</span></div><button class="mini edit" data-open-sales="${esc(x.customerEmail)}">Angebote öffnen</button></div>`).join(""):`<div class="empty">Aktuell kein Package am Übergang.</div>`;$$('[data-open-sales]').forEach(b=>b.addEventListener('click',()=>{openClient(b.dataset.openSales);currentRecordTab='sales';$$('[data-record-tab]').forEach(x=>x.classList.toggle('active',x.dataset.recordTab==='sales'));renderRecord()}))}

  function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`}

  function viennaCalendarParts(value){
    const d=value instanceof Date?value:new Date(value);
    const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));
    return {ymd:`${parts.year}-${parts.month}-${parts.day}`,hour:Number(parts.hour||0),minute:Number(parts.minute||0)};
  }
  function addCalendarDays(ymd,days){const d=new Date(`${ymd}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
  function mondayFor(ymd){const d=new Date(`${ymd}T12:00:00Z`),wd=d.getUTCDay()||7;return addCalendarDays(ymd,1-wd)}
  function currentCalendarMonday(offset=0){return addCalendarDays(mondayFor(viennaCalendarParts(new Date()).ymd),Number(offset||0)*7)}
  function calendarLabel(ymd){return new Intl.DateTimeFormat('de-AT',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(`${ymd}T12:00:00Z`))}
  function calendarRangeLabel(monday){const end=addCalendarDays(monday,6),a=new Date(`${monday}T12:00:00Z`),b=new Date(`${end}T12:00:00Z`);const sameMonth=a.getUTCMonth()===b.getUTCMonth();const sameYear=a.getUTCFullYear()===b.getUTCFullYear();if(sameMonth&&sameYear)return `${a.getUTCDate()}.–${b.getUTCDate()}. ${new Intl.DateTimeFormat('de-AT',{month:'long',year:'numeric',timeZone:'UTC'}).format(a)}`;return `${new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'short',timeZone:'UTC'}).format(a)} – ${new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(b)}`}
  function bookingDurationMinutes(x){if(x?.end){const n=(new Date(x.end)-new Date(x.start))/60000;if(Number.isFinite(n)&&n>0)return n}const t=String(x?.typeLabel||x?.type||'').toLowerCase();return t.includes('90')||t.includes('paar')||t.includes('couple')?90:60}
  function calendarTone(x){const t=String(x?.typeLabel||x?.type||'').toLowerCase(),loc=String(x?.locationLabel||'').toLowerCase();if(t.includes('erst')||t.includes('initial'))return'initial';if(t.includes('paar')||t.includes('couple')||t.includes('gemeinsam'))return'couple';if(loc.includes('online')||t.includes('online'))return'online';return'single'}
  function weekCalendarHtml(rows,offset,scope,compact=false){
    const monday=currentCalendarMonday(offset),days=Array.from({length:7},(_,i)=>addCalendarDays(monday,i)),today=viennaCalendarParts(new Date()).ymd;
    const booked=(rows||[]).filter(x=>x.status==='booked'&&x.start);
    const weekRows=booked.filter(x=>{const y=viennaCalendarParts(x.start).ymd;return y>=days[0]&&y<=days[6]});
    let startHour=8,endHour=20;
    weekRows.forEach(x=>{const p=viennaCalendarParts(x.start),dur=bookingDurationMinutes(x);startHour=Math.min(startHour,Math.max(6,p.hour));endHour=Math.max(endHour,Math.min(22,Math.ceil((p.hour*60+p.minute+dur)/60)))});
    const hourHeight=compact?42:54,totalHeight=(endHour-startHour)*hourHeight;
    const gutter=Array.from({length:endHour-startHour+1},(_,i)=>`<span style="top:${i*hourHeight}px">${String(startHour+i).padStart(2,'0')}:00</span>`).join('');
    const columns=days.map((day,idx)=>{
      const events=weekRows.filter(x=>viennaCalendarParts(x.start).ymd===day).sort((a,b)=>new Date(a.start)-new Date(b.start));
      const nowP=viennaCalendarParts(new Date()),nowMin=nowP.hour*60+nowP.minute,startMin=startHour*60;
      const nowLine=day===today&&nowMin>=startMin&&nowMin<=endHour*60?`<i class="bd-cal-now" style="top:${((nowMin-startMin)/60)*hourHeight}px"></i>`:'';
      return `<div class="bd-cal-day ${day===today?'today':''} ${idx>=5?'weekend':''}" style="height:${totalHeight}px">${nowLine}${events.map(x=>{const p=viennaCalendarParts(x.start),mins=p.hour*60+p.minute-startMin,dur=bookingDurationMinutes(x),top=Math.max(0,(mins/60)*hourHeight),height=Math.max(compact?30:38,(dur/60)*hourHeight-3);return `<button class="bd-cal-event ${calendarTone(x)}" type="button" data-booking-edit="${esc(x.eventId)}" style="top:${top}px;height:${height}px" title="${esc(x.name)} · ${esc(x.typeLabel||'Termin')}"><strong>${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')} · ${esc(x.name)}</strong><span>${esc(x.typeLabel||'Termin')}${compact?'':` · ${esc(x.locationLabel||'')}`}</span></button>`}).join('')}</div>`
    }).join('');
    return `<div class="bd-week-calendar ${compact?'compact':''}" data-calendar-scope="${scope}"><div class="bd-cal-toolbar"><div class="bd-cal-nav"><button type="button" class="mini" data-cal-nav="${scope}" data-dir="-1" aria-label="Vorige Woche">←</button><button type="button" class="mini" data-cal-today="${scope}">Heute</button><button type="button" class="mini" data-cal-nav="${scope}" data-dir="1" aria-label="Nächste Woche">→</button></div><strong>${esc(calendarRangeLabel(monday))}</strong><span class="bd-cal-hint">${weekRows.length} Termin${weekRows.length===1?'':'e'}</span></div><div class="bd-cal-scroll"><div class="bd-cal-grid" style="--bd-hour:${hourHeight}px"><div class="bd-cal-head bd-cal-time-head">Zeit</div>${days.map((d,i)=>`<div class="bd-cal-head ${d===today?'today':''} ${i>=5?'weekend':''}">${esc(calendarLabel(d))}</div>`).join('')}<div class="bd-cal-times" style="height:${totalHeight}px">${gutter}</div>${columns}</div></div></div>`;
  }
  function bindWeekCalendar(scope){
    $$(`[data-cal-nav="${scope}"]`).forEach(b=>b.addEventListener('click',()=>{const d=Number(b.dataset.dir||0);if(scope==='dashboard'){dashboardWeekOffset+=d;renderNext()}else{bookingWeekOffset+=d;renderBookings()}}));
    $$(`[data-cal-today="${scope}"]`).forEach(b=>b.addEventListener('click',()=>{if(scope==='dashboard'){dashboardWeekOffset=0;renderNext()}else{bookingWeekOffset=0;renderBookings()}}));
  }
  function renderNext(){
    const rows=(data.bookings||[]).filter(x=>x.status==='booked');
    $('#nextBookings').innerHTML=weekCalendarHtml(rows,dashboardWeekOffset,'dashboard',true);
    bindWeekCalendar('dashboard');bindPowerActions();
  }

  const stages={
    inquiry:{title:"Anfrage",copy:"Neu eingegangen, noch kein Erstgespräch.",dot:"stage-inquiry"},
    consultation:{title:"Erstgespräch",copy:"Erstkontakt bzw. erster Termin ist vereinbart.",dot:"stage-consultation"},
    active:{title:"Aktiv",copy:"Laufende Begleitung mit Termin oder aktivem Package.",dot:"stage-active"},
    paused:{title:"Pausiert",copy:"Aktuell keine regelmäßige Begleitung geplant.",dot:"stage-paused"},
    completed:{title:"Abgeschlossen",copy:"Begleitung bewusst abgeschlossen.",dot:"stage-completed"}
  };
  function renderJourney(){const clients=customerUniverse(),group={};Object.keys(stages).forEach(k=>group[k]=[]);clients.forEach(c=>(group[boardBucket(c)]||group.inquiry).push(c));$("#journeyBoard").innerHTML=Object.entries(stages).map(([key,s])=>`<section class="journey-column" data-drop-stage="${key}"><div class="journey-column-head"><div class="label-wrap"><i class="stage-dot ${s.dot}"></i><h3>${s.title}</h3></div><span class="stage-count">${group[key].length}</span></div><div class="stage-copy">${s.copy}</div><div class="journey-cards">${group[key].map(clientCard).join("")}</div></section>`).join("");bindJourneyDnD();bindClientOpeners()}
  function clientCard(c){const n=nextBooking(c.email),pkg=activePackage(c.email),inv=clientData(c.email).invoices.find(x=>x.status==="overdue");return `<article class="client-card" draggable="true" data-client-email="${esc(c.email)}"><h4>${esc(c.name)}</h4><div class="card-email">${esc(visibleContactEmail(c.contactEmail||c.email))}${c.isSandboxProfile?` <span class="badge test">Sandbox/Testprofil</span>`:""}</div><div class="card-meta">${n?`<span>📅 ${esc(dt(n.start))}</span>`:""}${pkg?`<span>▣ ${esc(pkg.productName)} · ${pkg.remaining}/${pkg.total}</span>`:""}</div><div class="card-flags">${pkg&&Number(pkg.remaining)<=loadSettings().renewalRemaining?`<span class="flag warn">Fortsetzung</span>`:""}${inv?`<span class="flag alert">Rechnung überfällig</span>`:""}</div><button class="card-open" type="button" data-open-client="${esc(c.email)}">Akte öffnen →</button></article>`}
  function bindJourneyDnD(){let dragged="";$$('.client-card[draggable="true"]').forEach(card=>{card.addEventListener('dragstart',e=>{dragged=card.dataset.clientEmail;card.classList.add('dragging');e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>{card.classList.remove('dragging');$$('.journey-column').forEach(c=>c.classList.remove('drag-over'))})});$$('[data-drop-stage]').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('drag-over');if(!dragged)return;moveClient(dragged,col.dataset.dropStage);dragged=""})})}
  function moveClient(email,stage){const c=customerUniverse().find(x=>x.email===normEmail(email));if(!c)return;const life=loadLifecycle();const prospect=life.prospects.find(p=>normEmail(p.email)===c.email);if(prospect&&!c.backend){prospect.stage=stage;prospect.updatedAt=new Date().toISOString();saveLifecycle(life);post('/admin/crm/inquiry/update',{id:prospect.id,email:prospect.email,journeyStage:stage,status:stage==='completed'?'closed':'open'}).catch(e=>alert('Journey konnte nicht gespeichert werden: '+e.message));logLocal(email,'journey',`Journey: ${stages[stage]?.title||stage}`);renderAll();return}const patch={journeyStage:stage};if(stage==='active')patch.clientStatus='active';else if(stage==='paused')patch.clientStatus='paused';else if(stage==='completed')patch.clientStatus='completed';else patch.clientStatus='prospect';setLifecycle(email,patch,'per Drag & Drop');renderAll()}

  function clientStatusBadge(s){return `<span class="badge ${s==='active'?'active-badge':s==='paused'?'paused-badge':s==='completed'?'completed-badge':'prospect-badge'}">${esc(lifecycleLabel(s))}</span>`}
  function renderClients(){const q=String($("#clientSearch").value||"").trim().toLowerCase(),filter=$("#clientStatusFilter").value;let cs=customerUniverse().filter(c=>!q||`${c.name} ${c.contactEmail||''} ${c.email}`.toLowerCase().includes(q));if(filter!=="all")cs=cs.filter(c=>lifecycleOf(c).clientStatus===filter);const rows=cs.map(c=>{const l=lifecycleOf(c),n=nextBooking(c.email),pkg=activePackage(c.email),open=clientData(c.email).invoices.filter(x=>x.status==="open"||x.status==="overdue").reduce((s,x)=>s+Number(x.totalCents||0),0);return `<tr><td><span class="name">${esc(c.name)}</span><div class="sub">${esc(visibleContactEmail(c.contactEmail||c.email))}${c.isSandboxProfile?' · 🧪 Sandbox/Test':''}</div></td><td>${clientStatusBadge(l.clientStatus)}</td><td>${esc(stages[boardBucket(c)]?.title||"—")}</td><td>${n?esc(dt(n.start)):"—"}</td><td>${pkg?`${esc(pkg.productName)}<div class="sub">${pkg.remaining}/${pkg.total} offen</div>`:"—"}</td><td>${open?money(open):"—"}</td><td><button class="mini" data-open-client="${esc(c.email)}">Akte öffnen</button></td></tr>`});$("#clientsTable").innerHTML=cs.length?table(["Klient:in","Status","Phase","Nächster Termin","Package","Offen",""],rows):`<div class="empty">Keine Klient:innen gefunden.</div>`;bindClientOpeners()}
  $("#clientSearch").addEventListener("input",()=>data&&renderClients());$("#clientStatusFilter").addEventListener("change",()=>data&&renderClients());

  function bindClientOpeners(){$$('[data-open-client]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.stopPropagation();openClient(b.dataset.openClient)})})}
  function openClient(email){const c=customerUniverse().find(x=>x.email===normEmail(email));if(!c)return;currentRecordEmail=c.email;currentRecordTab='overview';$("#recordName").textContent=c.name;$("#recordEmail").textContent=visibleContactEmail(c.contactEmail||c.email)+(c.isSandboxProfile?" · Sandbox/Testprofil":"");$("#recordStatus").value=lifecycleOf(c).clientStatus;if(!$("#recordRenameBtn")){const status=$("#recordStatus")?.closest('.record-status');status?.insertAdjacentHTML('beforebegin','<button class="mini edit" id="recordRenameBtn" type="button">Name korrigieren</button>');$("#recordRenameBtn")?.addEventListener('click',renameCurrentClient)}$$('[data-record-tab]').forEach(b=>b.classList.toggle('active',b.dataset.recordTab==='overview'));renderRecord();$("#clientDialog").showModal()}
  $("#clientDialogClose").setAttribute("title","Klientenakte schließen");$("#clientDialogClose").setAttribute("aria-label","Klientenakte schließen");$("#clientDialogClose").addEventListener('click',()=>$("#clientDialog").close());$$('[data-record-tab]').forEach(b=>b.addEventListener('click',()=>{currentRecordTab=b.dataset.recordTab;$$('[data-record-tab]').forEach(x=>x.classList.toggle('active',x===b));renderRecord()}));
  $("#recordStatus").addEventListener('change',()=>{const status=$("#recordStatus").value,stage=status==='active'?'active':status==='paused'?'paused':status==='completed'?'completed':'inquiry';setLifecycle(currentRecordEmail,{clientStatus:status,journeyStage:stage},'in der Klientenakte');renderAll();renderRecord()});
  async function renameCurrentClient(){const c=customerUniverse().find(x=>x.email===currentRecordEmail);if(!c||!c.id)return;const name=prompt('Klientenname korrigieren',c.name||'');if(name===null)return;const clean=name.trim().replace(/\s+/g,' ');if(!clean||clean===c.name)return;try{await post('/admin/customer/update-name',{customerId:c.id,name:clean});await load();openClient(c.email)}catch(e){alert('Name konnte nicht geändert werden: '+e.message)}}
  function salesCatalogHtml(c){
    const catalog=(b9().catalog||[]).filter(x=>Number(x.priceCents||x.price_cents||0)>0),orders=build9Rows('salesOrders',c.email),subs=build9Rows('subscriptions',c.email);
    const cards=catalog.map(p=>{const price=Number(p.priceCents||p.price_cents||0),regular=Number(p.regularAmountCents||0),saving=Number(p.savingCents||0),isSub=p.product_kind==='subscription',internal=!Number(p.public_visible),unit=p.sessions_total?`${p.sessions_total} × ${p.session_minutes} Min.`:'',savingPct=regular>0&&saving>0?Math.round(saving/regular*1000)/10:0;return `<article class="sales-card ${internal?'internal':''} ${isSub?'subscription':''}"><div class="sales-card-head"><div><h3>${esc(p.name_de)}</h3><div class="sales-badges">${internal?'<span class="sales-badge internal">intern</span>':'<span class="sales-badge">öffentlich</span>'}${isSub?'<span class="sales-badge subscription">Abo-Pilot</span>':''}</div></div><div><div class="sales-price">${money(price)}</div>${regular>price?`<div class="sales-regular">statt ${money(regular)}</div>`:''}</div></div><div class="sales-copy">${esc(unit)}${p.validity_days?` · ${p.validity_days} Tage gültig`:''}${saving?`<br><span class="sales-saving">${money(saving)} Vorteil${savingPct?` · ${String(savingPct).replace('.',',')} %`:''}</span>`:''}${p.note?`<br>${esc(p.note)}`:''}</div><div class="sales-actions"><button class="mini" data-sales-offer="${esc(p.id)}">Angebot senden</button>${isSub?`<button class="mini edit" data-sales-sub="${esc(p.id)}">Abo-Link senden</button>`:`<button class="mini edit" data-sales-order="${esc(p.id)}">Bestellung anlegen</button>`}</div></article>`}).join('');
    const hist=orders.length?table(['Datum','Angebot','Status','Rechnung'],orders.slice(0,15).map(o=>`<tr><td>${dateOnly(o.created_at||o.createdAt)}</td><td>${esc(o.product_name||o.productName||o.product_id)}</td><td>${esc(salesStatusLabel(o.status))}</td><td>${o.invoice_id?`#${o.invoice_id}`:'—'}</td></tr>`)):'<div class="empty">Noch keine Angebote oder Bestellungen angelegt.</div>';
    const sub= subs.length?`<div class="sales-history"><h3>Kontinuitätsmodelle</h3>${table(['Start','Status','Monatlich'],subs.map(x=>`<tr><td>${dateOnly(x.started_at)}</td><td>${esc(salesStatusLabel(x.status))}</td><td>${money(x.amount_cents)}</td></tr>`))}</div>`:'';
    return `<div class="sales-grid">${cards}</div><div class="sales-history"><h3>Verlauf</h3>${hist}</div>${sub}`;
  }
  const secondaryRecordMeta={bookings:['Terminverwaltung','Termine dieses Klienten ansehen.'],sales:['Angebote & Buchungen','Neue Angebote starten oder bestehende Buchungen ansehen.'],packages:['Packages','Gebuchte Packages und verfügbare Einheiten.'],invoices:['Honorarnoten & Zahlungen','Honorarnoten, Status und Zahlungserfassung.'],activity:['Aktivität','Organisatorische CRM-Aktivitäten.'],journey:['Journey','Sekundäre Prozessansicht der Klientenbeziehung.']};
  function addSecondaryRecordNavigation(){const meta=secondaryRecordMeta[currentRecordTab],host=$('#recordContent');if(!meta||!host||host.querySelector('.client-subview-nav'))return;host.insertAdjacentHTML('afterbegin',`<div class="client-subview-nav"><button class="client-subview-back" type="button" aria-label="Zur Klientenübersicht">← Zur Übersicht</button><div><span>Weitere Aktion</span><strong>${esc(meta[0])}</strong><small>${esc(meta[1])}</small></div></div>`);host.querySelector('.client-subview-back')?.addEventListener('click',()=>{currentRecordTab='overview';$$('[data-record-tab]').forEach(x=>x.classList.toggle('active',x.dataset.recordTab==='overview'));renderRecord()})}
  function renderRecord(){const c=customerUniverse().find(x=>x.email===currentRecordEmail);if(!c)return;const cd=clientData(c.email),l=lifecycleOf(c),n=nextBooking(c.email),pkg=activePackage(c.email),wallet=walletBalance(c.email);if(currentRecordTab==='overview'){$("#recordContent").innerHTML=`<div class="client-command-bar"><div><span class="client-command-label">Schnellaktionen</span><strong>Was möchtest du für ${esc(c.name)} tun?</strong></div><div class="client-command-actions"><button class="btn primary compact" data-client-flow-email="${esc(c.email)}">Sitzung starten</button><button class="btn ghost compact" data-client-tab="case-summary">Briefing / Fallübersicht</button><button class="btn ghost compact" data-client-tab="bookings">Termine</button><button class="btn ghost compact" data-client-tab="sales">Angebot / Package</button><button class="btn ghost compact" data-client-tab="invoices">Honorarnoten / Zahlung</button></div></div><div class="context-grid"><div class="context-card"><span>Status</span><strong>${lifecycleLabel(l.clientStatus)}</strong></div><div class="context-card"><span>Nächster Termin</span><strong>${n?esc(dt(n.start)):"Keiner geplant"}</strong></div><div class="context-card"><span>Aktuelles Package</span><strong>${pkg?`${esc(pkg.productName)} · ${pkg.remaining}/${pkg.total}`:"Kein aktives Package"}</strong></div><div class="context-card"><span>Letzter Termin</span><strong>${lastPastBooking(c.email)?esc(dt(lastPastBooking(c.email).start)):"—"}</strong></div><div class="context-card"><span>Offene Honorarnoten</span><strong>${money(cd.invoices.filter(x=>x.status==='open'||x.status==='overdue').reduce((s,x)=>s+Number(x.totalCents||0),0))}</strong></div><div class="context-card"><span>Guthaben</span><strong>${money(wallet)}</strong></div></div><div style="margin-top:18px"><p class="eyebrow">Letzte Aktivität</p>${activityHtml(c.email,6)}</div>`}
    if(currentRecordTab==='journey')$("#recordContent").innerHTML=`<div class="journey-detail"><div class="context-card"><span>Aktuelle Phase</span><strong>${esc(stages[boardBucket(c)]?.title||'—')}</strong></div><div><p class="eyebrow">Phase ändern</p><div class="journey-stage-buttons">${Object.entries(stages).map(([k,v])=>`<button class="mini ${boardBucket(c)===k?'active':''}" data-record-stage="${k}">${esc(v.title)}</button>`).join('')}</div></div><p class="muted micro">Die Phase beschreibt, wo die Person im Prozess steht. Der Klientenstatus Aktiv / Pausiert / Abgeschlossen bleibt separat steuerbar.</p></div>`;
    if(currentRecordTab==='bookings')$("#recordContent").innerHTML=cd.bookings.length?table(["Termin","Beratung","Ort","Status"],cd.bookings.sort((a,b)=>new Date(b.start)-new Date(a.start)).map(x=>`<tr><td>${esc(dt(x.start))}</td><td>${esc(x.typeLabel)}</td><td>${esc(x.locationLabel)}</td><td>${x.status==='cancelled'?'Abgesagt':'Gebucht'}</td></tr>`)):`<div class="empty">Keine Termine.</div>`;
    if(currentRecordTab==='sales'){$("#recordContent").innerHTML=salesCatalogHtml(c);bindSalesActions()}
    if(currentRecordTab==='packages')$("#recordContent").innerHTML=cd.packages.length?table(["Package","Offen","Gültig","Kauf"],cd.packages.map(x=>`<tr><td>${esc(x.productName)}</td><td>${x.remaining}/${x.total}</td><td>${dateOnly(x.expiresAt)}</td><td>${x.purchaseAmountCents==null?'—':money(x.purchaseAmountCents,x.currency)}<div class="sub">${esc(x.purchaseStatus||'')}</div></td></tr>`)):`<div class="empty">Keine Packages.</div>`;
    if(currentRecordTab==='invoices'){$("#recordContent").innerHTML=cd.invoices.length?table(["Honorarnote","Betrag","Fällig","Status","Zahlung","Aktion"],cd.invoices.map(x=>`<tr><td>${esc(x.invoiceNumber)}</td><td>${money(x.totalCents,x.currency)}</td><td>${dateOnly(x.dueDate)}</td><td>${statusLabel(x.status)}${x.dbStatus==='test'?' · Sandbox/Test':''}</td><td>${x.status==='paid'?`${esc(paymentLabel(x.paymentMethod))}<div class="sub">${dt(x.paidAt)}</div>`:'—'}</td><td><div class="row-actions"><button class="mini" data-pdf="${x.id}">PDF</button>${invoicePayable(x)?`<button class="mini pay" data-paid="${x.id}">Zahlung erfassen</button>`:''}</div></td></tr>`)):`<div class="empty">Keine Honorarnoten.</div>`;bindInvoiceActions()}
    if(currentRecordTab==='documentation'){$("#recordContent").innerHTML=`<div id="vaultRecordMount" class="vault-doc"><div class="vault-empty">Secure Practice Vault wird geladen …</div></div>`;document.dispatchEvent(new CustomEvent('bd:vault-record',{detail:{email:c.email,name:c.name}}))}
    if(currentRecordTab==='activity')$("#recordContent").innerHTML=activityHtml(c.email,80);
    addSecondaryRecordNavigation();
    $$('[data-client-tab]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-record-tab="${CSS.escape(b.dataset.clientTab)}"]`)?.click()));
    $$('[data-client-flow-email]').forEach(b=>b.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('bd:open-client-flow',{detail:{email:b.dataset.clientFlowEmail}}))));
    $$('[data-record-stage]').forEach(b=>b.addEventListener('click',()=>{moveClient(c.email,b.dataset.recordStage);renderRecord()}));
  }
  function activitiesFor(email){const cd=clientData(email),items=[];loadLifecycle().activities.filter(x=>x.email===email).forEach(x=>items.push({at:x.at,title:x.summary,detail:x.detail||'CRM-Aktion'}));cd.bookings.forEach(x=>items.push({at:x.start,title:x.status==='cancelled'?'Termin abgesagt':'Termin',detail:`${x.typeLabel} · ${x.locationLabel}`}));cd.invoices.forEach(x=>items.push({at:x.invoiceDate||x.dueDate,title:`Honorarnote ${x.invoiceNumber}`,detail:`${money(x.totalCents,x.currency)} · ${statusLabel(x.status)}`}));cd.packages.forEach(x=>items.push({at:x.purchasedAt||x.createdAt||x.expiresAt,title:`Package ${x.productName}`,detail:`${x.remaining}/${x.total} Einheiten offen`}));const backend=(data.activities||data.auditLog||data.audit||[]).filter(x=>normEmail(x.email||x.customerEmail)===email);backend.forEach(x=>items.push({at:x.createdAt||x.at||x.timestamp,title:x.summary||x.action||x.type||'Aktivität',detail:x.detail||''}));return items.filter(x=>x.at).sort((a,b)=>new Date(b.at)-new Date(a.at))}
  function activityIcon(x){const t=`${x?.title||''} ${x?.detail||''}`.toLowerCase();if(/whatsapp/.test(t))return'💬';if(/e-mail|email|mail /.test(t))return'✉️';if(/telefon|anruf/.test(t))return'📞';if(/zahlung|betrag erhalten|bezahlt|stripe|barzahlung|überweisung/.test(t))return'🏦';if(/rechnung|honorar/.test(t))return'🧾';if(/termin|buchung|storn/.test(t))return'📅';if(/package|paket|einheit/.test(t))return'📦';if(/ziel/.test(t))return'🎯';if(/diktat|audio|sprach/.test(t))return'🎙️';if(/handnotiz|handschrift/.test(t))return'✍️';if(/datei|dokument|artefakt|foto|bild/.test(t))return'📎';if(/sitzung|session|erstgespräch/.test(t))return'📝';if(/anfrage|kontakt|website|nachricht/.test(t))return'👤';return'•'}
  function activityHtml(email,limit){const a=activitiesFor(email).slice(0,limit);return a.length?`<div class="timeline">${a.map(x=>`<div class="timeline-item"><div class="timeline-mark timeline-mark-icon" aria-hidden="true">${activityIcon(x)}</div><div class="timeline-copy"><strong>${esc(x.title)}</strong><span>${esc(dt(x.at))}${x.detail?' · '+esc(x.detail):''}</span></div></div>`).join('')}</div>`:`<div class="empty">Noch keine Aktivität.</div>`}

  // BUILD 13.9 extension point: exposes only the currently opened CRM record
  // to the local fall overview. Sensitive documentation remains in the Vault.
  window.BDClientRecordContext=()=>{const c=customerUniverse().find(x=>x.email===currentRecordEmail);if(!c)return null;return{email:c.email,name:c.name,client:c,clientData:clientData(c.email),activities:activitiesFor(c.email),lifecycle:lifecycleOf(c),nextBooking:nextBooking(c.email),lastBooking:lastPastBooking(c.email),activePackage:activePackage(c.email)}};
  window.BDAdminUX={switchView,openClient,getData:()=>data,getCurrentRecordEmail:()=>currentRecordEmail,refresh:load};

  function renderBookings(){
    const all=(data.bookings||[]).slice();
    const cal=$('#bookingCalendar');if(cal){cal.innerHTML=weekCalendarHtml(all,bookingWeekOffset,'bookings',false);bindWeekCalendar('bookings')}
    const filter=$('#bookingFilter')?.value||'upcoming',t=now();let rows=all.slice();if(filter==='upcoming')rows=rows.filter(x=>x.status==='booked'&&new Date(x.start).getTime()>=t);if(filter==='past')rows=rows.filter(x=>x.status==='booked'&&new Date(x.start).getTime()<t);if(filter==='cancelled')rows=rows.filter(x=>x.status==='cancelled');rows.sort((a,b)=>filter==='upcoming'?new Date(a.start)-new Date(b.start):new Date(b.start)-new Date(a.start));$('#bookingsTable').innerHTML=rows.length?table(['Termin','Klient:in','Berater','Beratung','Ort','Status','Aktion'],rows.map(x=>`<tr><td>${esc(dt(x.start))}</td><td><span class="name">${esc(x.name)}</span><div class="sub">${esc(x.email)}</div></td><td>${esc(x.advisorName||'Theophil Kroller')}</td><td>${esc(x.typeLabel)}${x.packageName?`<div class="sub">${esc(x.packageName)}</div>`:''}</td><td>${esc(x.locationLabel)}</td><td><span class="badge ${x.status==='cancelled'?'cancelled':'booked'}">${x.status==='cancelled'?'Abgesagt':new Date(x.start).getTime()<t?'Vergangen':'Gebucht'}</span></td><td>${x.status==='booked'?`<div class="row-actions"><button class="mini edit" data-booking-edit="${esc(x.eventId)}">Verschieben</button><button class="mini danger" data-booking-delete="${esc(x.eventId)}">Stornieren</button></div>`:'—'}</td></tr>`)):'<div class="empty">Keine Termine in dieser Ansicht.</div>';bindPowerActions()}
  $('#bookingFilter')?.addEventListener('change',()=>data&&renderBookings());
  function renderPackages(){const rows=(data.packages||[]).map(x=>`<tr><td><span class="name">${esc(x.customerName)}</span><div class="sub">${esc(visibleContactEmail(x.customerContactEmail||x.customerEmail))}</div></td><td>${esc(x.advisorName||'Theophil Kroller')}</td><td><strong>${esc(x.productName)}</strong><div class="sub">${esc(x.reference||'')}</div></td><td><strong>${x.remaining}/${x.total}</strong>${Number(x.remaining)<=loadSettings().renewalRemaining?'<div class="sub" style="color:#99631E">Fortsetzung im Blick</div>':''}</td><td>${x.expiresAt?dateOnly(x.expiresAt):'—'}</td><td>${x.purchaseAmountCents===null?'—':money(x.purchaseAmountCents,x.currency)}<div class="sub">${esc(x.purchaseStatus||'')}</div></td><td><div class="row-actions"><button class="mini edit" data-package-edit="${x.creditId}">Bearbeiten</button>${Number(x.remaining)<=loadSettings().renewalRemaining?`<button class="mini" data-offer="${x.creditId}">Fortsetzung</button>`:''}</div></td></tr>`);$("#packagesTable").innerHTML=rows.length?table(["Klient:in","Berater","Package","Offen","Gültig bis","Kauf","Aktion"],rows):`<div class="empty">Noch keine Packages.</div>`;bindPowerActions();bindOfferButtons()}
  function invoiceTypeLabel(type){return({group:'Gruppe',package:'Package',single:'Einzelsession',other:'Sonstige'})[type]||'Sonstige'}
  function renderInvoices(){
    const bi=b9().bankImport||{},el=$("#bankLastImport");
    if(el)el.textContent=bi.lastImportedAt?`Letzter Bankabgleich: ${dt(bi.lastImportedAt)} · ${bi.rowCount||0} Buchungen · ${bi.importedCount||0} übernommen`:'Noch kein Bankabgleich protokolliert.';
    const statusFilter=$("#invoiceFilter").value,typeFilter=$("#invoiceTypeFilter")?.value||'all';
    const rows=(data.invoices||[]).filter(x=>(statusFilter==='all'||x.status===statusFilter)&&(typeFilter==='all'||(x.invoiceType||'other')===typeFilter));
    $("#invoicesTable").innerHTML=rows.length?table(["Honorarnote","Klient:in","Typ","Betrag","Fällig","Status / Zahlung","Aktion"],rows.map(x=>{
      let actions=`<button class="mini" data-pdf="${x.id}">PDF</button><button class="mini edit" data-due-edit="${x.id}">Zahlungsziel</button>`;
      if(invoicePayable(x))actions+=`<button class="mini pay" data-paid="${x.id}">Zahlung erfassen</button>`;
      if(x.status==='overdue')actions+=`<button class="mini remind" data-remind="${x.id}">Erinnerung</button>`;
      if(x.status==='paid')actions+=`<button class="mini" data-open="${x.id}">Wieder öffnen</button>`;
      const payment=x.status==='paid'?`<div class="payment-meta"><strong>${esc(paymentLabel(x.paymentMethod))}</strong><span>${dt(x.paidAt)}${x.paymentReference?` · ${esc(x.paymentReference)}`:''}</span></div>`:'';
      const type=x.invoiceType||'other';
      return `<tr><td><span class="name">${esc(x.invoiceNumber||'—')}</span><div class="sub">${dateOnly(x.invoiceDate)}</div></td><td>${esc(x.customerName)}<div class="sub">${esc(visibleContactEmail(x.customerContactEmail||x.customerEmail))}</div></td><td><span class="invoice-type ${esc(type)}">${esc(invoiceTypeLabel(type))}</span></td><td><strong>${money(x.totalCents,x.currency)}</strong></td><td>${dateOnly(x.dueDate)}</td><td><span class="badge ${esc(x.status)}">${esc(statusLabel(x.status))}</span>${x.dbStatus==='test'?` <span class="badge test">Sandbox/Test</span>`:''}${payment}</td><td><div class="row-actions">${actions}</div></td></tr>`
    })): `<div class="empty">Keine Honorarnoten für diese Filterkombination.</div>`;
    bindInvoiceActions();bindPowerActions()
  }
  $("#invoiceFilter").addEventListener('change',()=>data&&renderInvoices());
  $("#invoiceTypeFilter")?.addEventListener('change',()=>data&&renderInvoices());

  function findBooking(id){return(data.bookings||[]).find(x=>x.eventId===id&&x.status==='booked')}function findPackage(id){return(data.packages||[]).find(x=>Number(x.creditId)===Number(id))}function findInvoice(id){return(data.invoices||[]).find(x=>Number(x.id)===Number(id))}
  function viennaParts(iso){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vienna',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
  function viennaIso(date,time){const probe=new Date(`${date}T12:00:00Z`);const name=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Vienna',timeZoneName:'shortOffset'}).formatToParts(probe).find(x=>x.type==='timeZoneName')?.value||'GMT+1';const m=name.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);const off=m?`${m[1]}${String(m[2]).padStart(2,'0')}:${m[3]||'00'}`:'+01:00';return new Date(`${date}T${time}:00${off}`).toISOString()}
  function openEditor(ctx){editCtx=ctx;$("#editEyebrow").textContent=ctx.eyebrow||'Änderung';$("#editTitle").textContent=ctx.title;$("#editSubtitle").textContent=ctx.subtitle||'';$("#editFields").innerHTML=ctx.fields.map(f=>{const attrs=`data-edit-key="${esc(f.key)}"`;const control=f.type==='select'?`<select ${attrs}>${(f.options||[]).map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(f.value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`:`<input ${attrs} type="${esc(f.type||'text')}" value="${esc(f.value??'')}" ${f.min!==undefined?`min="${f.min}"`:''} ${f.step!==undefined?`step="${f.step}"`:''}>`;return `<label class="edit-field"${f.full?' style="grid-column:1/-1"':''}>${esc(f.label)}${control}</label>`}).join('');$("#emailPreview").classList.remove('active');$("#editState").textContent='';$("#saveNotify").style.display=ctx.allowNotify===false?'none':'';$$('[data-edit-key]').forEach(i=>{i.addEventListener('input',refreshEditState);i.addEventListener('change',refreshEditState)});refreshEditState();$("#editDialog").showModal()}
  function editValues(){const o={};$$('[data-edit-key]').forEach(i=>o[i.dataset.editKey]=i.value);return o}function changes(){if(!editCtx)return[];const v=editValues();return editCtx.fields.filter(f=>String(v[f.key]??'')!==String(f.value??'')).map(f=>({label:f.label,old:f.display?f.display(f.value):String(f.value||'—'),now:f.display?f.display(v[f.key]):String(v[f.key]||'—')}))}
  function refreshEditState(){const c=changes(),dirty=c.length>0||!!editCtx?.actionMode;$("#saveOnly").disabled=!dirty;$("#saveNotify").disabled=!dirty;$("#changeHeadline").textContent=c.length?`${c.length} ungespeicherte Änderung${c.length===1?'':'en'}`:(editCtx?.actionMode?(editCtx.actionHeadline||'Aktion ist bereit'):'Keine Änderungen vorgenommen');$("#changeList").innerHTML=c.map(x=>`<div class="change-row"><span>${esc(x.label)}:</span><span class="old-value">${esc(x.old)}</span><span>→</span><span class="new-value">${esc(x.now)}</span></div>`).join('');$("#editState").textContent=dirty?'Noch nicht gespeichert':''}
  async function saveEditor(withEmail){if(!editCtx||(!changes().length&&!editCtx.actionMode))return;const v=editValues(),c=changes();$("#saveOnly").disabled=true;$("#saveNotify").disabled=true;$("#editState").textContent='Speichere …';try{await editCtx.save(v);if(editCtx.email)logLocal(editCtx.email,'edit',editCtx.title,c.map(x=>`${x.label}: ${x.old} → ${x.now}`).join(' · '));$("#editState").textContent='Änderungen gespeichert ✓';if(withEmail){$("#emailPreviewText").innerHTML=`<div class="email-preview-text">Die Kundin bzw. der Kunde erhält eine Nachricht über:<br><br>${c.map(x=>`<strong>${esc(x.label)}</strong>: ${esc(x.old)} → ${esc(x.now)}`).join('<br>')}<br><br><strong>Es wurde noch keine E-Mail gesendet.</strong></div>`;$("#emailPreview").classList.add('active')}else{await load();$("#editDialog").close()}}catch(e){alert(e.message);refreshEditState()}}
  $("#editForm").addEventListener('submit',e=>{e.preventDefault();saveEditor(false)});$("#saveNotify").addEventListener('click',()=>saveEditor(true));$("#editClose").addEventListener('click',()=>$("#editDialog").close());$("#editCancel").addEventListener('click',()=>$("#editDialog").close());$("#emailCancel").addEventListener('click',()=>$("#emailPreview").classList.remove('active'));$("#emailConfirm").addEventListener('click',async()=>{if(!editCtx?.notify)return;const b=$("#emailConfirm");b.disabled=true;b.textContent='Sende …';try{await editCtx.notify();if(editCtx.email)logLocal(editCtx.email,'email','Klient:in über Änderung informiert');$("#emailPreviewText").innerHTML='<strong>E-Mail wurde gesendet ✓</strong>';setTimeout(async()=>{await load();$("#editDialog").close()},700)}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='E-Mail jetzt senden'}});

  function bindPowerActions(){
    $$('[data-booking-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findBooking(b.dataset.bookingEdit);if(!x)return;const p=viennaParts(x.start);openEditor({eyebrow:'Termin',title:'Termin verschieben',subtitle:`${x.name} · aktuell ${dt(x.start)}`,email:x.email,fields:[{key:'date',label:'Neues Datum',type:'date',value:p.date,display:dateOnly},{key:'time',label:'Neue Uhrzeit',type:'time',value:p.time,step:300}],save:v=>post('/admin/booking/update',{eventId:x.eventId,start:viennaIso(v.date,v.time)}),notify:()=>post('/admin/booking/notify',{eventId:x.eventId})})})});
    $$('[data-booking-delete]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openCancellation(b.dataset.bookingDelete))});
    $$('[data-package-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findPackage(b.dataset.packageEdit);if(!x)return;openEditor({eyebrow:'Package',title:'Package bearbeiten',subtitle:`${x.customerName} · ${x.productName}`,email:x.customerEmail,fields:[{key:'remaining',label:'Offene Einheiten',type:'number',value:String(x.remaining),min:0},{key:'total',label:'Gesamte Einheiten',type:'number',value:String(x.total),min:0},{key:'expiresAt',label:'Gültig bis',type:'date',value:x.expiresAt?String(x.expiresAt).slice(0,10):'',display:v=>v?dateOnly(v):'ohne Ablaufdatum'}],save:v=>{const remaining=Number(v.remaining),total=Number(v.total);if(!Number.isInteger(remaining)||!Number.isInteger(total)||remaining<0||total<0||remaining>total)throw new Error('Offene Einheiten müssen zwischen 0 und der Gesamtzahl liegen.');return post('/admin/package/update',{creditId:x.creditId,remaining,total,expiresAt:v.expiresAt||null})},notify:()=>post('/admin/package/notify',{creditId:Number(x.creditId)})})})});
    $$('[data-due-edit]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findInvoice(b.dataset.dueEdit);if(!x)return;openEditor({eyebrow:'Rechnung',title:'Zahlungsziel ändern',subtitle:`${x.invoiceNumber} · ${x.customerName}`,email:x.customerEmail,fields:[{key:'dueDate',label:'Neues Zahlungsziel',type:'date',value:x.dueDate||'',display:dateOnly}],save:v=>post('/admin/invoice/update-due',{invoiceId:x.id,dueDate:v.dueDate}),notify:()=>post('/admin/invoice/notify',{invoiceId:Number(x.id)})})})})
  }
  function bindInvoiceActions(){
    $$('[data-remind]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('bd:receivable-open',{detail:{invoiceId:Number(b.dataset.remind)}})))});
    $$('[data-paid]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{const x=findInvoice(b.dataset.paid);if(!x)return;const vp=viennaParts(new Date().toISOString());openEditor({eyebrow:'Zahlung',title:'Betrag erhalten',subtitle:`${x.invoiceNumber} · ${x.customerName} · ${money(x.totalCents,x.currency)}`,email:x.customerEmail,allowNotify:false,actionMode:true,actionHeadline:'Zahlung kann jetzt verbucht werden',fields:[{key:'paymentMethod',label:'Zahlungsart',type:'select',value:'bank_transfer',options:[{value:'bank_transfer',label:'Banküberweisung'},{value:'cash',label:'Barzahlung'},{value:'sumup',label:'SumUp / Kartenzahlung'},{value:'other',label:'Sonstiges'}]},{key:'paymentDate',label:'Datum erhalten',type:'date',value:vp.date,display:dateOnly},{key:'paymentTime',label:'Uhrzeit erhalten',type:'time',value:vp.time,step:60},{key:'reference',label:'Referenz / Notiz',type:'text',value:'',full:true}],save:v=>post('/admin/invoice/payment',{invoiceId:x.id,paid:true,paymentMethod:v.paymentMethod,paymentDate:v.paymentDate,paymentDateTime:viennaIso(v.paymentDate,v.paymentTime||'12:00'),reference:v.reference})})})});
    $$('[data-open]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{if(!confirm('Diese Rechnung wieder als offen markieren? Der aktuelle Zahlungseintrag wird im Audit-Verlauf storniert, nicht gelöscht.'))return;b.disabled=true;try{await post('/admin/invoice/payment',{invoiceId:Number(b.dataset.open),paid:false});await load()}catch(e){alert(e.message)}finally{b.disabled=false}})});
    $$('[data-pdf]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{b.disabled=true;try{const r=await fetch(API+'/admin/invoice-pdf?id='+encodeURIComponent(b.dataset.pdf),{headers:{Authorization:'Bearer '+session}});if(!r.ok)throw new Error('PDF konnte nicht geladen werden.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Rechnung.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){alert(e.message)}finally{b.disabled=false}})})
  }

  function openInquiry(){$('#inquiryForm').reset();$('#inquiryDialog').showModal()}$('#newInquiryBtn').addEventListener('click',openInquiry);$('#journeyAddBtn').addEventListener('click',openInquiry);$('#inquiryClose').addEventListener('click',()=>$('#inquiryDialog').close());$('#inquiryCancel').addEventListener('click',()=>$('#inquiryDialog').close());$('#inquiryForm').addEventListener('submit',async e=>{e.preventDefault();const email=normEmail($('#inqEmail').value);if(customerUniverse().some(c=>c.email===email)){alert('Diese E-Mail ist bereits im CRM vorhanden.');return}try{const row=await post('/admin/crm/inquiry/create',{name:$('#inqName').value.trim(),email,source:$('#inqSource').value,journeyStage:$('#inqStage').value});const life=loadLifecycle();life.prospects.push({id:row.inquiry?.id||row.id||uid(),name:$('#inqName').value.trim(),email,source:$('#inqSource').value,stage:$('#inqStage').value,createdAt:new Date().toISOString()});saveLifecycle(life);logLocal(email,'inquiry','Neue Anfrage erfasst',$('#inqSource').value);$('#inquiryDialog').close();renderAll();switchView('journey')}catch(err){alert('Anfrage konnte nicht gespeichert werden: '+err.message)}});

  function bindOfferButtons(){$$('[data-offer]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openOffer(b.dataset.offer))})}
  function openOffer(creditId){const x=findPackage(creditId);if(!x)return;offerCtx=x;$("#offerClient").textContent=`${x.customerName} · ${x.productName} · ${x.remaining}/${x.total} Einheiten offen`;const base=x.purchaseAmountCents!=null?Number(x.purchaseAmountCents)/100:0;$("#offerBasePrice").value=base||'';$("#offerDiscount").value=loadSettings().discount||0;updateOfferPrice();updateOfferEmail();$("#offerDialog").showModal()}
  function updateOfferPrice(){const base=Number($("#offerBasePrice").value||0),disc=Number($("#offerDiscount").value||0);$("#offerFinalPrice").value=(base*(1-disc/100)).toFixed(0);updateOfferEmail()}
  function updateOfferEmail(){if(!offerCtx)return;const final=Number($("#offerFinalPrice").value||0),disc=Number($("#offerDiscount").value||0),type=$("#offerType").selectedOptions[0]?.textContent||'Fortsetzung';$("#offerEmailText").value=`Hallo ${String(offerCtx.customerName||'').split(' ')[0]},\n\nbei deinem aktuellen Package ist nur noch ${offerCtx.remaining} Sitzung${Number(offerCtx.remaining)===1?'':'en'} offen. Wenn du die Begleitung direkt fortsetzen möchtest, können wir den nächsten Schritt gern schon jetzt planen.\n\n${type}${final?` · ${euro(final)}`:''}${disc?` (${disc} % Fortsetzungsbonus)`:''}\n\nWenn das für dich passt, antworte mir einfach kurz – dann kümmere ich mich um den Rest.\n\nLiebe Grüße\nTheophil`}
  ['offerBasePrice','offerDiscount'].forEach(id=>$("#"+id).addEventListener('input',updateOfferPrice));['offerFinalPrice','offerType'].forEach(id=>$("#"+id).addEventListener('input',updateOfferEmail));$("#offerClose").addEventListener('click',()=>$("#offerDialog").close());$("#copyOfferBtn").addEventListener('click',async()=>{await navigator.clipboard.writeText($("#offerEmailText").value);$("#copyOfferBtn").textContent='Kopiert ✓';setTimeout(()=>$("#copyOfferBtn").textContent='Text kopieren',1200)});$("#sendOfferBtn").addEventListener('click',async()=>{if(!offerCtx)return;const text=$("#offerEmailText").value.trim();if(!text)return;if(!confirm(`Fortsetzungsangebot jetzt an ${visibleContactEmail(offerCtx.customerContactEmail||offerCtx.customerEmail)} senden?`))return;const btn=$("#sendOfferBtn");btn.disabled=true;btn.textContent='Sende …';try{const payload={customerId:offerCtx.customerId||null,email:offerCtx.customerEmail,creditId:offerCtx.creditId,sourceProductId:offerCtx.productId,offerLabel:$("#offerType").selectedOptions[0]?.textContent||'Fortsetzung',regularAmountCents:Math.round(Number($("#offerBasePrice").value||0)*100),offeredAmountCents:Math.round(Number($("#offerFinalPrice").value||0)*100),discountPercent:Number($("#offerDiscount").value||0),subject:'Fortsetzung deiner Begleitung',body:text};await post('/admin/crm/renewal-offer/send',payload);logLocal(offerCtx.customerEmail,'offer','Fortsetzungsangebot gesendet',`${$("#offerFinalPrice").value||'—'} EUR`);$("#offerDialog").close();await load()}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='E-Mail prüfen & senden'}});

  function catalogProduct(id){return (b9().catalog||[]).find(x=>String(x.id)===String(id))}
  function bindSalesActions(){
    $$('[data-sales-offer]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',async()=>{const c=customerByEmail(currentRecordEmail),p=catalogProduct(btn.dataset.salesOffer);if(!c||!p)return;const regular=Number(p.regularAmountCents||0),saving=Number(p.savingCents||0);const body=`Hallo ${String(c.name||'').split(' ')[0]},\n\nwie besprochen kann ich dir folgendes Angebot vorbereiten:\n\n${p.name_de}\n${p.sessions_total?`${p.sessions_total} × ${p.session_minutes} Minuten\n`:''}Preis: ${money(Number(p.priceCents||0))}${saving?`\nPaketvorteil: ${money(saving)} gegenüber ${money(regular)} bei Einzelsitzungen`:''}\n\nWenn das für dich passt, antworte mir kurz. Ich kann dir die Bestellung samt Rechnung und sicherem Zahlungslink direkt vorbereiten.\n\nLiebe Grüße\nTheophil`;if(!confirm(`Angebot „${p.name_de}“ jetzt an ${visibleContactEmail(c.contactEmail||c.email)} senden?`))return;btn.disabled=true;try{await post('/admin/sales/offer',{customerId:c.id,email:c.email,productId:p.id,body});await load();currentRecordTab='sales';renderRecord()}catch(e){alert(e.message)}finally{btn.disabled=false}})});
    $$('[data-sales-order]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>openSalesOrder(btn.dataset.salesOrder))});
    $$('[data-sales-sub]').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',async()=>{const c=customerByEmail(currentRecordEmail),p=catalogProduct(btn.dataset.salesSub);if(!c||!p)return;if(!confirm(`Internes Kontinuitätsmodell für ${c.name} vorbereiten und Stripe-Abo-Link per E-Mail senden?`))return;btn.disabled=true;try{await post('/admin/sales/subscription',{customerId:c.id,email:c.email,locale:'de'});await load();currentRecordTab='sales';renderRecord()}catch(e){alert(e.message)}finally{btn.disabled=false}})});
  }
  function openSalesOrder(productId){const c=customerByEmail(currentRecordEmail),p=catalogProduct(productId);if(!c||!p)return;salesCtx={client:c,product:p};const bill=(b9().billing||[]).find(x=>Number(x.customer_id)===Number(c.id)||normEmail(x.email)===c.email)||{};$('#salesOrderTitle').textContent=p.name_de;$('#salesOrderClient').textContent=`${c.name} · ${visibleContactEmail(c.contactEmail||c.email)}`;const saving=Number(p.savingCents||0);$('#salesOrderSummary').innerHTML=`<strong>${esc(p.name_de)} · ${money(Number(p.priceCents||0))}</strong><span>${p.sessions_total?`${p.sessions_total} × ${p.session_minutes} Min. · `:''}${saving?`${money(saving)} Paketvorteil · `:''}Package wird erst nach Zahlung aktiviert.</span>`;$('#salesStreet').value=bill.billing_street||'';$('#salesPostal').value=bill.billing_postal_code||'';$('#salesCity').value=bill.billing_city||'';$('#salesCountry').value=bill.billing_country||'Österreich';$('#salesIncludeStripe').checked=true;$('#salesEarlyService').checked=false;$('#salesImmediateDigital').checked=false;$('#salesOrderMsg').textContent='';$('#salesOrderDialog').showModal()}
  $('#salesOrderClose').onclick=$('#salesOrderCancel').onclick=()=>$('#salesOrderDialog').close();
  $('#salesOrderForm').addEventListener('submit',async e=>{e.preventDefault();if(!salesCtx)return;const b={customerId:salesCtx.client.id,email:salesCtx.client.email,productId:salesCtx.product.id,includeStripe:$('#salesIncludeStripe').checked,locale:'de',billing:{street:$('#salesStreet').value.trim(),postal:$('#salesPostal').value.trim(),city:$('#salesCity').value.trim(),country:$('#salesCountry').value.trim()},consents:{earlyService:$('#salesEarlyService').checked,immediateDigital:$('#salesImmediateDigital').checked}};const submit=e.submitter;submit.disabled=true;try{const x=await post('/admin/sales/order',b);message($('#salesOrderMsg'),`Bestellung ${x.invoiceNumber||''} wurde angelegt${x.emailSent?' und per E-Mail versendet.':'.'}`);setTimeout(async()=>{$('#salesOrderDialog').close();await load();currentRecordTab='sales';renderRecord()},900)}catch(err){message($('#salesOrderMsg'),err.message,'err')}finally{submit.disabled=false}});

  async function openCancellation(eventId){const x=findBooking(eventId);if(!x)return;try{const o=await api('/admin/booking/cancel-options?eventId='+encodeURIComponent(eventId)),f=o.finance||{};cancelCtx={booking:x,finance:f};$('#cancelClient').textContent=`${x.name} · ${dt(x.start)} · ${x.typeLabel}`;const charge=Number(f.chargePercent??0),ref=Number(f.refundableCents||0),total=Number(f.totalCents||0),fee=Number(f.cancellationFeeCents||0);let summary='';if(f.packageCredit)summary='Package-Termin · Einheit wird zurückgebucht.';else if(f.isPaid)summary=total?`Bezahlter Betrag ${money(total)} · erstattungsfähig ${money(ref)}`:'Bezahlte Einzelrechnung nicht gefunden.';else if(f.invoiceId)summary=charge===0?`Offene Rechnung ${esc(f.invoiceNumber||'')} wird storniert · keine Gebühr.`:`Offene Rechnung ${esc(f.invoiceNumber||'')} · Stornogebühr ${money(fee)} (${charge}%).`;else summary='Keine zugeordnete Einzelrechnung gefunden.';$('#cancelSummary').innerHTML=`<strong>Stornoregel: ${charge}% Gebühr</strong><span>${summary}</span>`;let html='';if(f.packageCredit){html='<div class="policy-result">Dieser Termin wurde aus einem Package gebucht. Die verwendete Einheit wird dem Package wieder gutgeschrieben.</div>'}else if(f.isPaid&&ref>0){html=`<label class="settlement-option"><input type="radio" name="cancelSettlement" value="wallet" checked><span><strong>Als Guthaben in der Member Area</strong><span>${money(ref)} werden als Praxisguthaben hinterlegt.</span></span></label>${f.paymentMethod==='stripe'?`<label class="settlement-option"><input type="radio" name="cancelSettlement" value="refund"><span><strong>Auf ursprüngliches Zahlungsmittel zurückerstatten</strong><span>${money(ref)} werden über Stripe zurückerstattet.</span></span></label>`:''}`}else if(!f.isPaid&&f.invoiceId){html=`<div class="policy-result"><strong>${charge===0?'Offene Rechnung wird storniert':'Stornorechnung wird erstellt'}</strong><br>${charge===0?'Es bleibt kein Betrag offen.':`Die ursprüngliche Rechnung wird storniert; neu verrechnet werden ${money(fee)}.`}</div>`}else{html=`<div class="policy-result"><strong>Stornogebühr gemäß Bedingungen</strong><br>Aufgrund der Stornofrist besteht kein erstattungsfähiger Betrag. Die Stornierung kann trotzdem durchgeführt werden.</div>`}$('#cancelChoices').innerHTML=html;$('#cancelNotify').checked=true;$('#cancelDialog').showModal()}catch(e){alert(e.message)}}
  $('#cancelClose').onclick=$('#cancelAbort').onclick=()=>$('#cancelDialog').close();
  $('#cancelConfirm').addEventListener('click',async()=>{if(!cancelCtx)return;const f=cancelCtx.finance||{},settlement=f.packageCredit?'package_credit':Number(f.refundableCents||0)>0?(document.querySelector('input[name="cancelSettlement"]:checked')?.value||'wallet'):'policy';if(!confirm('Termin jetzt verbindlich stornieren? Diese Aktion entfernt ihn aus dem Google Kalender.'))return;const b=$('#cancelConfirm');b.disabled=true;b.textContent='Storniere …';try{await post('/admin/booking/cancel-settlement',{eventId:cancelCtx.booking.eventId,settlement,notifyCustomer:$('#cancelNotify').checked});$('#cancelDialog').close();await load()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Termin verbindlich stornieren'}});

  let pendingBankMatches=[];
  function parseCsvLine(line,sep){const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++}else quote=!quote}else if(ch===sep&&!quote){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(x=>x.trim())}
  function normalizeHeader(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
  function parseEuroAmount(s){let v=String(s||'').trim().replace(/\s|€/g,'');if(!v)return NaN;if(v.includes(',')&&v.includes('.'))v=v.lastIndexOf(',')>v.lastIndexOf('.')?v.replace(/\./g,'').replace(',','.'):v.replace(/,/g,'');else if(v.includes(','))v=v.replace(/\./g,'').replace(',','.');return Number(v)}
  function parseBankDate(s){s=String(s||'').trim();let m;if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);if((m=s.match(/^(\d{1,2})[.\/]\s*(\d{1,2})[.\/]\s*(\d{4})/)))return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;return null}
  function pickHeader(headers,names){for(const name of names){const i=headers.findIndex(h=>h===name||h.includes(name));if(i>=0)return i}return -1}
  function csvTransactions(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('CSV enthält keine Daten.');const sample=lines.slice(0,5).join('\n'),sep=(sample.match(/;/g)||[]).length>=(sample.match(/,/g)||[]).length?';':',';const headers=parseCsvLine(lines[0],sep).map(normalizeHeader);const dateI=pickHeader(headers,['buchungsdatum','valutadatum','datum','booking date','date']);const amountI=pickHeader(headers,['betrag eur','betrag','umsatz','amount']);const refIs=['verwendungszweck','buchungstext','zahlungsreferenz','referenz','reference','memo','purpose','text'].map(n=>pickHeader(headers,[n])).filter((v,i,a)=>v>=0&&a.indexOf(v)===i);const cpI=pickHeader(headers,['zahlungsbeteiligter','auftraggeber','gegenkonto name','empfanger auftraggeber','counterparty','payer','name']);if(dateI<0||amountI<0)throw new Error('Datum- oder Betragsspalte konnte nicht erkannt werden. Exportiere bitte ein CSV mit Buchungsdatum/Valutadatum und Betrag.');const tx=[];for(let i=1;i<lines.length;i++){const row=parseCsvLine(lines[i],sep),amount=parseEuroAmount(row[amountI]);if(!Number.isFinite(amount)||amount<=0)continue;const date=parseBankDate(row[dateI]);if(!date)continue;const reference=refIs.map(j=>row[j]||'').filter(Boolean).join(' · ');tx.push({row:i+1,paymentDate:date,amountCents:Math.round(amount*100),reference,counterparty:cpI>=0?(row[cpI]||''):''})}return tx}
  function confidenceBadge(c){return c==='exact'?'<span class="badge paid">Sicher erkannt</span>':c==='probable'?'<span class="badge open">Wahrscheinlich</span>':c==='amount_only'?'<span class="badge neutral">Nur Betrag</span>':'<span class="badge neutral">Offen</span>'}
  async function handleBankCsv(file){pendingBankSource=file.name||'Bank-CSV';const transactions=csvTransactions(await file.text());pendingBankRowCount=transactions.length;if(!transactions.length)throw new Error('Keine eingehenden Zahlungen erkannt.');const x=await post('/admin/payments/match',{transactions});pendingBankMatches=(x.matches||[]).map(m=>({...transactions[m.index],...m}));const exact=pendingBankMatches.filter(x=>x.confidence==='exact').length,probable=pendingBankMatches.filter(x=>x.confidence==='probable').length;$("#bankImportSummary").textContent=`${transactions.length} eingehende Buchungen · ${exact} sicher zugeordnet · ${probable} wahrscheinlich. Sichere Treffer sind vorausgewählt.`;$("#bankImportTable").innerHTML=table(['Übernehmen','Datum','Betrag','Absender / Referenz','Zuordnung','Sicherheit'],pendingBankMatches.map((m,i)=>`<tr><td>${m.invoiceId?`<input type="checkbox" data-bank-match="${i}" ${m.confidence==='exact'?'checked':''}>`:'—'}</td><td>${dateOnly(m.paymentDate)}</td><td>${money(m.amountCents)}</td><td>${esc(m.counterparty||'—')}<div class="sub">${esc(m.reference||'')}</div></td><td>${m.invoiceId?`${esc(m.invoiceNumber)}<div class="sub">${esc(m.customerName||'')}</div>`:'Keine eindeutige Rechnung'}</td><td>${confidenceBadge(m.confidence)}<div class="sub">${esc(m.reason||'')}</div></td></tr>`));$("#bankImportDialog").showModal()}
  $("#bankCsvInput").addEventListener('change',async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{await handleBankCsv(f)}catch(err){alert('CSV-Import: '+err.message)}});$("#bankImportClose").onclick=$("#bankImportCancel").onclick=()=>$("#bankImportDialog").close();$("#bankImportApply").addEventListener('click',async()=>{const selected=$$('[data-bank-match]:checked').map(el=>pendingBankMatches[Number(el.dataset.bankMatch)]).filter(Boolean).map(x=>({invoiceId:x.invoiceId,paymentDate:x.paymentDate,amountCents:x.amountCents,reference:x.reference,counterparty:x.counterparty}));if(!selected.length){alert('Bitte mindestens eine erkannte Zahlung auswählen.');return}if(!confirm(`${selected.length} Zahlung${selected.length===1?'':'en'} jetzt als Banküberweisung verbuchen?`))return;const b=$("#bankImportApply");b.disabled=true;b.textContent='Übernehme …';try{const x=await post('/admin/payments/import',{matches:selected,sourceName:pendingBankSource,rowCount:pendingBankRowCount});alert(`${x.imported||0} Zahlung${Number(x.imported)===1?'':'en'} übernommen.`);$("#bankImportDialog").close();await load()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Ausgewählte Zahlungen übernehmen'}});

  function renderSettings(){const s=loadSettings();$("#settingDormantDays").value=s.dormantDays;$("#settingRenewalRemaining").value=s.renewalRemaining;$("#settingDiscount").value=s.discount}
  $("#saveSettingsBtn").addEventListener('click',async()=>{const cfg={dormantDays:Number($("#settingDormantDays").value||60),renewalRemaining:Number($("#settingRenewalRemaining").value||1),discount:Number($("#settingDiscount").value||0)};try{crmState.settings=cfg;await post('/admin/crm/settings',cfg);message($("#settingsMsg"),'Einstellungen im Worker gespeichert.');renderAll()}catch(e){message($("#settingsMsg"),'Speichern fehlgeschlagen: '+e.message,'err')}});
  $("#exportLifecycleBtn").addEventListener('click',()=>{const payload={version:1,exportedAt:new Date().toISOString(),lifecycle:loadLifecycle(),settings:loadSettings()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beziehungsdynamiken-crm-status-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)});
  if($("#importLifecycleInput")) $("#importLifecycleInput").addEventListener('change',async e=>{e.target.value='';message($("#settingsMsg"),'Import ist in BUILD 9 bewusst deaktiviert, weil CRM-Status jetzt serverseitig in D1 gespeichert wird. Nutze für Migrationen die D1-Sicherung.','err')});

  (async()=>{if(!API){showLogin();message($("#loginMsg"),'Die API-Adresse ist noch nicht konfiguriert.','err');return}const magic=await consumeMagicLink();if(session||magic)await load();else showLogin()})();
})();
