(function(){
  'use strict';
  const LEGACY_SUCCESS_COPY='Dieses Capture befindet sich jetzt in deiner Dokumentations-Inbox';
  const $=selector=>document.querySelector(selector);
  const API=String(window.BD_BOOKING_CONFIG?.apiBaseUrl||'https://beziehungsdynamiken-booking.theophil-kroller.workers.dev').replace(/\/$/,'');
  const DB_NAME='bd-praxis-capture-v3',DB_VERSION=3,ACTIVE_KEY='bd_capture_active_v3',EINK_KEY='bd_capture_eink_mode_v1';
  const LIMITS={photos:12,audio:12,pages:30,directChars:7500000,partChars:1400000,maxTransferChars:80000000};
  const canvas=$('#inkCanvas'),ctx=canvas.getContext('2d');
  let dbPromise=null,deviceKey=null,draft=null,activePage=0,activeStroke=null,activeStrokeIndex=-1,saveTimer=0,inkSnapshotTimer=0,saveChain=Promise.resolve(),inkJournalChain=Promise.resolve();
  let recorder=null,stream=null,recordStarted=0,recordTick=0,scannerStream=null,scannerTimer=0,audioUrls=[],wakeLock=null,installPrompt=null;
  let chunkSequence=0,chunkSaveChain=Promise.resolve(),queueBusy=false,accessPairing=null;
  let uiStage='home',justSent=false,renderedStage='';

  function uid(){return crypto.randomUUID()}
  function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function now(){return new Date().toISOString()}
  function bytes64(bytes){let value='';for(let i=0;i<bytes.length;i+=0x8000)value+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(value)}
  function from64(value){let source=String(value||'').replace(/-/g,'+').replace(/_/g,'/');while(source.length%4)source+='=';const raw=atob(source),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
  function fmt(value){return new Intl.DateTimeFormat('de-AT',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
  function formatTime(seconds){return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
  function modeLabel(value){return({dictation:'Diktat',session:'Sitzung + Handschrift',note:'Notiz / Anlage',idea:'Idee / Inspiration',method:'Übung / Methode'}[value]||'Erfassung')}
  function statusLabel(value){return({draft:'lokal gespeichert',queued:'wartet auf Übertragung',sending:'wird verschlüsselt übertragen',sent:'✓ übertragen · lokale Kopie vorhanden'}[value]||value||'lokal gespeichert')}
  function defaultDeviceType(){return /boox|onyx/i.test(navigator.userAgent||'')?'boox':'s22'}
  function blankDraft(){return{version:5,captureId:uid(),createdAt:now(),updatedAt:now(),deviceType:defaultDeviceType(),domain:'practice',label:'',captureType:'dictation',ideaSourceType:'own',ideaSourceUrl:'',methodSourceType:'',methodSourceDescription:'',methodSourceUrl:'',consentConfirmed:false,noteText:'',inkPages:[{id:uid(),createdAt:now(),strokes:[]}],audio:[],photos:[],pairing:null,status:'draft',syncAttempts:0,nextRetryAt:null,lastSyncError:'',pendingRecording:null}}

  function openDb(){
    if(dbPromise)return dbPromise;
    dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains('drafts'))database.createObjectStore('drafts');if(!database.objectStoreNames.contains('meta'))database.createObjectStore('meta');if(!database.objectStoreNames.contains('recordingChunks'))database.createObjectStore('recordingChunks');if(!database.objectStoreNames.contains('inkJournal'))database.createObjectStore('inkJournal')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
    return dbPromise;
  }
  async function dbGet(store,key){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),request=tx.objectStore(store).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function dbPut(store,key,value){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
  async function dbDelete(store,key){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
  async function dbEntries(store){const database=await openDb();return new Promise((resolve,reject)=>{const rows=[],tx=database.transaction(store,'readonly'),request=tx.objectStore(store).openCursor();request.onsuccess=()=>{const cursor=request.result;if(cursor){rows.push([cursor.key,cursor.value]);cursor.continue()}else resolve(rows)};request.onerror=()=>reject(request.error)})}

  function inkJournalKey(captureId,pageId,index){return `${captureId}|${pageId}|${String(index).padStart(6,'0')}`}
  async function journalInkStroke(pageId,index,stroke){
    if(!draft||!Array.isArray(stroke)||!stroke.length)return;
    const row={captureId:draft.captureId,pageId,strokeIndex:index,stroke:JSON.parse(JSON.stringify(stroke)),createdAt:now(),updatedAt:now(),status:'ink'};
    inkJournalChain=inkJournalChain.then(async()=>{await dbPut('inkJournal',inkJournalKey(row.captureId,pageId,index),await encryptDraft(row));if(draft?.captureId===row.captureId&&$('#workSaveState'))$('#workSaveState').textContent='✓ Handschrift lokal gesichert'}).catch(error=>{if($('#workSaveState')){$('#workSaveState').textContent='⚠ Handschrift noch nicht gesichert';$('#workSaveState').classList.add('error')}console.error('BD ink journal',error)});
    return inkJournalChain;
  }
  async function recoverInkJournal(){
    if(!draft)return 0;let recovered=0;const rows=await dbEntries('inkJournal');const pending=[];
    for(const [key,row] of rows){try{const x=await decryptDraft(row);if(x.captureId===draft.captureId)pending.push([key,x])}catch(_){}}
    pending.sort((a,b)=>Number(a[1].strokeIndex)-Number(b[1].strokeIndex));
    for(const [,x] of pending){const pg=(draft.inkPages||[]).find(v=>String(v.id)===String(x.pageId));if(!pg)continue;const idx=Number(x.strokeIndex);if(pg.strokes.length===idx){pg.strokes.push(x.stroke);recovered++}}
    return recovered;
  }
  async function clearInkJournalThrough(snapshot){
    const rows=await dbEntries('inkJournal');for(const [key,row] of rows){try{const x=await decryptDraft(row);if(x.captureId!==snapshot.captureId)continue;const pg=(snapshot.inkPages||[]).find(v=>String(v.id)===String(x.pageId));if(pg&&pg.strokes.length>Number(x.strokeIndex))await dbDelete('inkJournal',key)}catch(_){}}
  }
  async function clearInkJournalCapture(captureId){const rows=await dbEntries('inkJournal');for(const [key,row] of rows){try{const x=await decryptDraft(row);if(x.captureId===captureId)await dbDelete('inkJournal',key)}catch(_){}}}
  async function getDeviceKey(){if(deviceKey)return deviceKey;const stored=await dbGet('meta','device-key');if(stored?.raw){deviceKey=await crypto.subtle.importKey('raw',from64(stored.raw),'AES-GCM',false,['encrypt','decrypt']);return deviceKey}if(stored?.type){deviceKey=stored;return deviceKey}const raw=crypto.getRandomValues(new Uint8Array(32));deviceKey=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);await dbPut('meta','device-key',{raw:bytes64(raw)});return deviceKey}
  async function encryptDraft(value){const key=await getDeviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return{iv,cipher,createdAt:value.createdAt,updatedAt:value.updatedAt,status:value.status||'draft'}}
  async function decryptDraft(row){const key=await getDeviceKey(),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(row.iv)},key,row.cipher);return JSON.parse(new TextDecoder().decode(plain))}
  async function loadAccessPairing(){try{const row=await dbGet('meta','capture-access-pairing');accessPairing=row?await decryptDraft(row):null}catch(_){accessPairing=null}return accessPairing}
  async function saveAccessPairing(pair){accessPairing=pair?{...pair,createdAt:pair.createdAt||now(),updatedAt:now()}:null;if(accessPairing)await dbPut('meta','capture-access-pairing',await encryptDraft(accessPairing));else await dbDelete('meta','capture-access-pairing');renderTransfer();return accessPairing}
  async function encryptChunk(bytes,meta){const key=await getDeviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);return{...meta,iv,cipher}}
  async function decryptChunk(row){const key=await getDeviceKey(),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(row.iv)},key,row.cipher);return new Uint8Array(plain)}
  async function persistDraft(value){value.updatedAt=now();await dbPut('drafts',value.captureId,await encryptDraft(JSON.parse(JSON.stringify(value))));return value}

  function normalizeDraft(value){const x={...blankDraft(),...(value||{})};x.version=5;x.captureType=['dictation','session','note','idea','method'].includes(x.captureType)?x.captureType:'dictation';x.domain=['idea','method'].includes(x.captureType)?'knowledge':'practice';x.methodSourceType=['','workshop','book','conversation','own','training','web','other'].includes(x.methodSourceType)?x.methodSourceType:'';x.methodSourceDescription=String(x.methodSourceDescription||'');x.methodSourceUrl=String(x.methodSourceUrl||'');x.ideaSourceType=['own','reddit','youtube','web','book','conversation','other'].includes(x.ideaSourceType)?x.ideaSourceType:'own';x.ideaSourceUrl=String(x.ideaSourceUrl||'');x.inkPages=Array.isArray(x.inkPages)&&x.inkPages.length?x.inkPages:[{id:uid(),createdAt:now(),strokes:Array.isArray(x.strokes)?x.strokes:[]}];x.audio=Array.isArray(x.audio)?x.audio:[];x.photos=Array.isArray(x.photos)?x.photos:[];return x}
  function syncFromForm(){if(!draft)return;draft.deviceType=$('#deviceType').value;draft.label=$('#label').value.trim();draft.noteText=$('#noteText').value;draft.consentConfirmed=$('#consentConfirmed').checked;draft.methodSourceType=$('#methodSourceType').value;draft.methodSourceDescription=$('#methodSourceDescription').value.trim();draft.methodSourceUrl=$('#methodSourceUrl').value.trim();draft.updatedAt=now()}
  function scheduleSave(message='Änderung wird lokal gespeichert …'){if(!draft)return;syncFromForm();clearTimeout(saveTimer);$('#saveState').textContent=message;$('#saveState').className='save-state';if($('#workSaveState'))$('#workSaveState').textContent='Wird gespeichert …';saveTimer=setTimeout(()=>saveNow(),520)}
  function scheduleInkSnapshot(){if(!draft)return;clearTimeout(inkSnapshotTimer);inkSnapshotTimer=setTimeout(()=>saveNow({quiet:true}),1600)}
  function saveNow({quiet=false}={}){if(!draft)return Promise.resolve();syncFromForm();const copy=JSON.parse(JSON.stringify(draft));saveChain=saveChain.then(async()=>{try{await persistDraft(copy);await clearInkJournalThrough(copy);localStorage.setItem(ACTIVE_KEY,copy.captureId);if(draft?.captureId===copy.captureId&&!quiet){$('#saveState').textContent='✓ Lokal gespeichert · '+new Date().toLocaleTimeString('de-AT');$('#saveState').className='save-state ok';if($('#workSaveState'))$('#workSaveState').textContent='✓ Sicher gespeichert';if($('#draftState'))$('#draftState').textContent=statusLabel(draft.status);updateProductUI()}}catch(error){$('#saveState').textContent='Lokales Speichern fehlgeschlagen: '+error.message;$('#saveState').className='save-state err';if($('#workSaveState')){$('#workSaveState').textContent='⚠ Speichern fehlgeschlagen';$('#workSaveState').classList.add('error')}}});return saveChain}
  async function loadDraft(id){const row=id&&await dbGet('drafts',id);draft=normalizeDraft(row?await decryptDraft(row):blankDraft());activePage=0;localStorage.setItem(ACTIVE_KEY,draft.captureId);const recoveredInk=await recoverInkJournal();await recoverInterruptedRecording();renderAll();if(recoveredInk&&$('#saveState')){$('#saveState').textContent=`✓ ${recoveredInk} Handschrift-Strich${recoveredInk===1?'':'e'} aus lokaler Sicherung wiederhergestellt`;$('#saveState').className='save-state ok'}await saveNow({quiet:true});await refreshDraftSelect();await renderQueue()}
  async function allDrafts(){const rows=await dbEntries('drafts'),items=[];for(const [id,row] of rows){try{items.push(normalizeDraft(await decryptDraft(row)))}catch(_){}}return items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}
  async function refreshDraftSelect(){const items=await allDrafts();$('#draftSelect').innerHTML=items.map(item=>`<option value="${esc(item.captureId)}">${item.status==='sent'?'✓ ':item.status==='queued'?'↻ ':''}${esc(item.label||modeLabel(item.captureType)+' · '+fmt(item.createdAt))}${item.status==='sent'?' · übertragen':''}</option>`).join('');$('#draftSelect').value=draft.captureId;const wrap=$('#draftSelectorWrap');if(wrap)wrap.hidden=items.length<=1;if($('#draftCount'))$('#draftCount').textContent=items.length?`(${items.length})`:'';const recent=items.filter(item=>item.status==='sent').sort((a,b)=>String(b.sentAt||b.updatedAt).localeCompare(String(a.sentAt||a.updatedAt))).slice(0,3);$('#recentTransfers').hidden=!recent.length;$('#recentTransferList').innerHTML=recent.map(item=>`<div class="recent-transfer-item"><div><strong>${esc(item.label||modeLabel(item.captureType))}</strong><small>✓ ${esc(fmt(item.sentAt||item.updatedAt))} · übertragen</small></div><button type="button" data-history-id="${esc(item.captureId)}">Ansehen</button></div>`).join('');$('#recentTransferList').querySelectorAll('[data-history-id]').forEach(button=>button.onclick=async()=>{await loadDraft(button.dataset.historyId);uiStage='review';updateProductUI()});updateProductUI()}

  function renderAll(){
    $('#deviceType').value=draft.deviceType||'s22';$('#label').value=draft.label||'';$('#noteText').value=draft.noteText||'';$('#consentConfirmed').checked=!!draft.consentConfirmed;
    renderMode();renderPhotos();renderAudio();renderInkPages();renderTransfer();applyDeviceProfile();resizeCanvas();
    if($('#draftState'))$('#draftState').textContent=statusLabel(draft.status);updateProductUI();
  }
  function setMode(mode){if(recorder?.state==='recording')return;draft.captureType=mode;draft.domain=['idea','method'].includes(mode)?'knowledge':'practice';if(['idea','method'].includes(mode)&&draft.pairing?.kind==='session')draft.pairing=null;uiStage='capture';renderMode();renderTransfer();scheduleSave('Capture-Modus wird gespeichert …');updateProductUI()}
  function renderMode(){const mode=draft.captureType||'dictation',idea=mode==='idea',method=mode==='method';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#audioSection').hidden=mode==='note';$('#inkSection').hidden=mode==='dictation';$('#noteSection').hidden=false;$('#consentWrap').hidden=mode!=='session';if($('#ideaMetaSection'))$('#ideaMetaSection').hidden=!idea;$('#methodMetaSection').hidden=!method;if($('#workTitle'))$('#workTitle').textContent=mode==='session'?'Sitzung aufnehmen':mode==='note'?'Notiz':idea?'Idee festhalten':method?'Übung festhalten':'Diktat';if($('#workSubtitle'))$('#workSubtitle').textContent=mode==='session'?'Audio und Handschrift · lokal gesichert':mode==='note'?'Text, Handschrift oder Foto · lokal gesichert':idea?'Geistesblitz, Fundstück oder Screenshot · lokal gesichert':method?'Audio, Text, Foto oder Link · lokal gesichert':'Kurze Nachbesprechung · lokal gesichert';if($('#recordHelp'))$('#recordHelp').textContent=idea?'Sprich deinen Gedanken ein – Whisper transkribiert ihn später lokal im Knowledge Hub.':mode==='session'?'Audio wird fortlaufend lokal gesichert. Du kannst gleichzeitig mitschreiben.':'Audio wird fortlaufend lokal gesichert.';const details=$('#noteDetails');if(details)details.open=mode==='note'||idea||method;if($('#ideaSourceType'))$('#ideaSourceType').value=draft.ideaSourceType||'own';if($('#ideaSourceUrl'))$('#ideaSourceUrl').value=draft.ideaSourceUrl||'';$('#methodSourceType').value=draft.methodSourceType||'';$('#methodSourceDescription').value=draft.methodSourceDescription||'';$('#methodSourceUrl').value=draft.methodSourceUrl||'';const photo=$('#photoInput');if(photo){if(idea||method)photo.removeAttribute('capture');else photo.setAttribute('capture','environment')}if($('#photoButtonLabel'))$('#photoButtonLabel').textContent=idea||method?'Screenshot / Bild hinzufügen':'Foto hinzufügen';updateRecordStartState();updateProductUI()}
  function updateRecordStartState(){const needsConsent=draft?.captureType==='session';$('#recordStart').disabled=!!recorder||needsConsent&&!$('#consentConfirmed').checked}
  function renderPhotos(){$('#photoPreview').innerHTML=draft.photos.length?draft.photos.map((photo,index)=>`<article class="media-item"><img src="data:${esc(photo.mime)};base64,${photo.dataBase64}" alt="Foto ${index+1}"><div class="media-copy"><strong>${esc(photo.name||'Foto '+(index+1))}</strong><small>Foto ${index+1} von ${draft.photos.length}</small></div><button class="danger" data-photo-delete="${index}" type="button">Entfernen</button></article>`).join(''):'<p class="help">Noch keine Fotos hinzugefügt.</p>';document.querySelectorAll('[data-photo-delete]').forEach(button=>button.onclick=()=>{draft.photos.splice(Number(button.dataset.photoDelete),1);renderPhotos();scheduleSave();updateProductUI()})}
  function audioBlob(item){return new Blob([from64(item.dataBase64)],{type:item.mime||'audio/webm'})}
  function renderAudio(){audioUrls.forEach(URL.revokeObjectURL);audioUrls=[];const host=$('#audioList');if(!draft.audio.length){host.innerHTML='<p class="help">Noch keine Aufnahmen vorhanden.</p>';return}host.innerHTML='';draft.audio.forEach((item,index)=>{const url=URL.createObjectURL(audioBlob(item));audioUrls.push(url);const article=document.createElement('article');article.className='media-item';article.innerHTML=`<div class="media-copy"><strong>${draft.captureType==='session'?'Sitzungsaufnahme':'Aufnahme'} ${index+1}${item.recovered?' · wiederhergestellt':''}</strong><small>${formatTime(Number(item.durationSeconds||0))} · lokal gespeichert</small></div><audio controls src="${url}"></audio><button class="danger" type="button">Entfernen</button>`;article.querySelector('button').onclick=()=>{if(confirm('Diese lokal gespeicherte Aufnahme wirklich entfernen?')){draft.audio.splice(index,1);renderAudio();scheduleSave()}};host.appendChild(article)});updateProductUI()}
  function page(){return draft.inkPages[activePage]}
  function renderInkPages(){activePage=Math.max(0,Math.min(activePage,draft.inkPages.length-1));$('#inkPageSelect').innerHTML=draft.inkPages.map((item,index)=>`<option value="${index}">Seite ${index+1}</option>`).join('');$('#inkPageSelect').value=String(activePage);$('#inkPageState').textContent=`Seite ${activePage+1} von ${draft.inkPages.length}`;$('#inkPrev').disabled=activePage===0;$('#inkNext').disabled=activePage===draft.inkPages.length-1;$('#inkDelete').disabled=draft.inkPages.length===1;drawInk();updateProductUI()}
  function einkOptimized(){return draft?.deviceType==='boox'||document.body.classList.contains('ink')||document.body.classList.contains('eink-device')}
  function applyDeviceProfile(){const boox=draft?.deviceType==='boox'||/boox|onyx/i.test(navigator.userAgent||'');document.body.classList.toggle('eink-device',boox);const manual=localStorage.getItem(EINK_KEY)==='1';document.body.classList.toggle('ink',manual);if($('#inkMode'))$('#inkMode').textContent=manual?'E‑Ink-Modus ✓':'E‑Ink-Modus';if($('#deviceType')&&boox&&$('#deviceType').value!=='boox')$('#deviceType').value='boox'}
  function resizeCanvas(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const ratio=einkOptimized()?1:Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*ratio));canvas.height=Math.max(1,Math.floor(rect.height*ratio));ctx.setTransform(ratio,0,0,ratio,0,0);drawInk()}
  function prepareInkContext(){ctx.lineWidth=einkOptimized()?2.15:2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#111'}
  function drawInk(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;ctx.clearRect(0,0,rect.width,rect.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,rect.width,rect.height);prepareInkContext();for(const stroke of page()?.strokes||[]){if(!stroke.length)continue;ctx.beginPath();ctx.moveTo(stroke[0].x*rect.width,stroke[0].y*rect.height);for(const point of stroke.slice(1))ctx.lineTo(point.x*rect.width,point.y*rect.height);if(stroke.length===1)ctx.lineTo(stroke[0].x*rect.width+.2,stroke[0].y*rect.height+.2);ctx.stroke()}}
  function drawInkPoints(points){if(!activeStroke||!points?.length)return;const rect=canvas.getBoundingClientRect(),last=activeStroke[activeStroke.length-1];prepareInkContext();ctx.beginPath();ctx.moveTo(last.x*rect.width,last.y*rect.height);for(const point of points){activeStroke.push(point);ctx.lineTo(point.x*rect.width,point.y*rect.height)}ctx.stroke()}
  function inkPoint(event){const rect=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height)),t:recordStarted?Date.now()-recordStarted:null}}

  async function compressPhoto(file){const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),work=document.createElement('canvas');work.width=Math.max(1,Math.round(bitmap.width*scale));work.height=Math.max(1,Math.round(bitmap.height*scale));work.getContext('2d').drawImage(bitmap,0,0,work.width,work.height);bitmap.close?.();const blob=await new Promise(resolve=>work.toBlob(resolve,'image/jpeg',.8));return{mime:'image/jpeg',name:(file.name||'foto').replace(/\.[^.]+$/,'')+'.jpg',dataBase64:bytes64(new Uint8Array(await blob.arrayBuffer())),createdAt:now()}}
  function recorderMime(){return['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>window.MediaRecorder?.isTypeSupported?.(type))||''}
  function chunkKey(captureId,recordingId,sequence){return`${captureId}|${recordingId}|${String(sequence).padStart(6,'0')}`}
  async function recordingRows(captureId,recordingId){const rows=await dbEntries('recordingChunks');return rows.filter(([key,row])=>row?.captureId===captureId&&row?.recordingId===recordingId).sort((a,b)=>Number(a[1].sequence)-Number(b[1].sequence))}
  async function clearRecordingRows(captureId,recordingId){for(const [key] of await recordingRows(captureId,recordingId))await dbDelete('recordingChunks',key)}
  async function acquireWakeLock(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch(_){wakeLock=null}}
  async function releaseWakeLock(){try{await wakeLock?.release?.()}catch(_){ }wakeLock=null}
  function lockDraftSwitch(locked){$('#newDraft').disabled=locked;$('#deleteDraft').disabled=locked;$('#draftSelect').disabled=locked;$('#photoInput').disabled=locked;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=locked)}
  async function startRecording(){
    if(!window.MediaRecorder){$('#recordState').textContent='Dieser Browser unterstützt die Audioaufnahme nicht.';return}
    if(draft.audio.length>=LIMITS.audio){$('#recordState').textContent=`Maximal ${LIMITS.audio} Aufnahmen pro Erfassung.`;return}
    if(draft.captureType==='session'&&!$('#consentConfirmed').checked){$('#recordState').textContent='Bitte zuerst bestätigen, dass die Einwilligung zur Audioaufnahme vorliegt.';return}
    try{
      stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});const mime=recorderMime(),recordingId=uid();chunkSequence=0;chunkSaveChain=Promise.resolve();recordStarted=Date.now();draft.pendingRecording={id:recordingId,startedAt:now(),mime:mime||'audio/webm',captureType:draft.captureType};await saveNow();
      recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);
      recorder.ondataavailable=event=>{if(!event.data?.size)return;const sequence=chunkSequence++,createdAt=now(),blob=event.data;chunkSaveChain=chunkSaveChain.then(async()=>{const bytes=new Uint8Array(await blob.arrayBuffer()),row=await encryptChunk(bytes,{captureId:draft.captureId,recordingId,sequence,mime:blob.type||mime||'audio/webm',createdAt});await dbPut('recordingChunks',chunkKey(draft.captureId,recordingId,sequence),row);if(draft?.pendingRecording?.id===recordingId){$('#recordLocalState').textContent=`✓ ${sequence+1} Abschnitte lokal`;$('#recordLocalState').className='status-pill local'}}).catch(error=>{$('#recordState').textContent='Lokaler Audioabschnitt konnte nicht gespeichert werden: '+error.message})};
      recorder.onstop=()=>finalizeRecording(recordingId).catch(error=>{$('#recordState').textContent='Aufnahme konnte nicht abgeschlossen werden: '+error.message});
      recorder.start(2000);await acquireWakeLock();lockDraftSwitch(true);$('#recordStart').disabled=true;$('#recordStop').disabled=false;$('#recordState').textContent='Aufnahme läuft · lokale Sicherung aktiv';$('#recordLocalState').textContent='✓ lokale Sicherung aktiv';$('#recordLocalState').className='status-pill local';recordTick=setInterval(()=>$('#recordTime').textContent=formatTime(Math.round((Date.now()-recordStarted)/1000)),500);
    }catch(error){lockDraftSwitch(false);stream?.getTracks().forEach(track=>track.stop());stream=null;recordStarted=0;draft.pendingRecording=null;await saveNow();$('#recordState').textContent='Mikrofon nicht verfügbar: '+error.message;updateRecordStartState()}
  }
  async function finalizeRecording(recordingId,recovered=false){
    await chunkSaveChain;const rows=await recordingRows(draft.captureId,recordingId);if(!rows.length){draft.pendingRecording=null;await saveNow();throw new Error('Es wurden keine Audioabschnitte gespeichert.')}
    $('#recordState').textContent='Lokale Audioabschnitte werden sicher zusammengeführt …';const parts=[];for(const [,row] of rows)parts.push(await decryptChunk(row));const blob=new Blob(parts,{type:rows[0][1].mime||draft.pendingRecording?.mime||'audio/webm'}),bytes=new Uint8Array(await blob.arrayBuffer());const started=new Date(draft.pendingRecording?.startedAt||rows[0][1].createdAt).getTime(),ended=new Date(rows.at(-1)[1].createdAt).getTime(),effectiveEnd=recovered?Math.max(ended,started+2000):Math.max(ended,Date.now()),duration=Math.max(1,Math.round((effectiveEnd-started)/1000));draft.audio.push({id:recordingId,mime:blob.type||'audio/webm',durationSeconds:duration,dataBase64:bytes64(bytes),createdAt:draft.pendingRecording?.startedAt||rows[0][1].createdAt,recovered:!!recovered});await clearRecordingRows(draft.captureId,recordingId);draft.pendingRecording=null;stream?.getTracks().forEach(track=>track.stop());stream=null;clearInterval(recordTick);recordStarted=0;recorder=null;await releaseWakeLock();$('#recordTime').textContent='0:00';$('#recordState').textContent=recovered?'Unterbrochene Aufnahme wurde aus lokalen Abschnitten wiederhergestellt.':'✓ Aufnahme vollständig lokal gespeichert.';$('#recordLocalState').textContent='✓ lokal gespeichert';$('#recordStart').disabled=false;$('#recordStop').disabled=true;lockDraftSwitch(false);renderAudio();await saveNow();await renderQueue();updateRecordStartState();updateProductUI()}
  function stopRecording(){if(recorder?.state==='recording'){try{recorder.requestData()}catch(_){ }recorder.stop();$('#recordStop').disabled=true;$('#recordState').textContent='Aufnahme wird sicher beendet …'}}
  async function recoverInterruptedRecording(){const pending=draft?.pendingRecording;if(!pending?.id)return;try{const rows=await recordingRows(draft.captureId,pending.id);if(rows.length){$('#saveState').textContent=`Unterbrochene Aufnahme gefunden · ${rows.length} lokale Abschnitte werden wiederhergestellt …`;await finalizeRecording(pending.id,true)}else{draft.pendingRecording=null}}catch(error){$('#saveState').textContent='Unterbrochene Aufnahme bleibt lokal erhalten: '+error.message;$('#saveState').className='save-state err'}}

  function pairingFrom(value){const url=new URL(String(value).trim(),location.href),relay=url.searchParams.get('relay')||'',token=url.searchParams.get('token')||'',key=url.searchParams.get('key')||'';if(!/^[a-f0-9]{32}$/i.test(relay)||token.length<32||key.length<32)throw new Error('Dieser QR-Code enthält keine vollständige Sitzungs-Verbindung.');return{relay,token,key,pairedAt:now(),kind:'session',sessionId:url.searchParams.get('session')||'',sessionDate:url.searchParams.get('sessionDate')||'',owner:url.searchParams.get('owner')||''}}
  function accessPairingFrom(value){const url=new URL(String(value).trim(),location.href),pairId=url.searchParams.get('accessPair')||'',token=url.searchParams.get('accessToken')||'',key=url.searchParams.get('key')||'',workspaceKey=url.searchParams.get('workspaceKey')||'',workspaceKeyId=url.searchParams.get('workspaceKeyId')||'',owner=url.searchParams.get('owner')||'',userId=url.searchParams.get('userId')||'',practiceId=url.searchParams.get('practiceId')||'',practitionerId=url.searchParams.get('practitionerId')||'',vaultId=url.searchParams.get('vaultId')||'';if(!/^[a-f0-9]{32}$/i.test(pairId)||token.length<32||key.length<32)throw new Error('Dieser QR-Code enthält keine vollständige Praxis-Kopplung.');return{pairId,token,key,workspaceKey,workspaceKeyId,owner,userId,practiceId,practitionerId,vaultId,createdAt:now(),updatedAt:now()}}
  function knowledgeCaptureType(target){if(!['idea','method'].includes(target.captureType))return target.captureType;const a=(target.audio||[]).length>0,t=!!String(target.noteText||'').trim(),p=(target.photos||[]).length>0,i=(target.inkPages||[]).some(page=>(page.strokes||[]).length),u=!!String(target.captureType==='method'?target.methodSourceUrl:target.ideaSourceUrl||'').trim(),n=(target.photos||[]).map(x=>String(x.name||'').toLowerCase()).join(' '),source=String(target.ideaSourceType||'');const count=[a,t,p,i].filter(Boolean).length;if(count>1)return'mixed';if(a)return'audio';if(t)return'text';if(i)return'handwriting';if(p)return(/screenshot|screen.?shot|bildschirm|capture/.test(n)||['reddit','youtube','web'].includes(source))?'screenshot':'image';if(u)return'link';return'other'}
  function transferPayload(target=draft){return{version:6,captureId:target.captureId,domain:['idea','method'].includes(target.captureType)?'knowledge':'practice',captureType:target.captureType,knowledgeCaptureType:knowledgeCaptureType(target),ideaSourceType:target.ideaSourceType||'own',ideaSourceUrl:target.ideaSourceUrl||'',methodSourceType:target.methodSourceType||'',methodSourceDescription:target.methodSourceDescription||'',methodSourceUrl:target.methodSourceUrl||'',consentConfirmed:!!target.consentConfirmed,deviceType:target.deviceType,label:target.label,createdAt:target.createdAt,updatedAt:target.updatedAt,noteText:target.noteText,inkPages:target.inkPages,strokes:target.inkPages?.[0]?.strokes||[],audio:target.audio,photos:target.photos}}
  async function encryptRelay(payload,keyText){const key=await crypto.subtle.importKey('raw',from64(keyText),'AES-GCM',false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return{format:'bdcapture-relay-1',iv:bytes64(iv),ciphertext:bytes64(new Uint8Array(cipher))}}
  async function jsonPost(path,body){const response=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let result={};try{result=await response.json()}catch(_){ }if(!response.ok||result.ok===false){const error=new Error(result.error||`Synchronisierung fehlgeschlagen (${response.status})`);error.status=response.status;throw error}return result}
  async function uploadEnvelope(target,encoded,onProgress){
    const pairing=target.pairing;if(!pairing)throw new Error('Keine Session-Verbindung vorhanden.');
    if(encoded.length<=LIMITS.directChars){onProgress?.('Verschlüsselte Erfassung wird übertragen …');return jsonPost('/capture-transfer/upload',{relay:pairing.relay,token:pairing.token,ciphertext:encoded})}
    if(encoded.length>LIMITS.maxTransferChars)throw new Error('Die Erfassung ist sehr groß. Sie bleibt sicher lokal gespeichert. Bitte verschlüsselten Datei-Export verwenden oder die Aufnahme in mehreren Teilen erfassen.');
    const parts=Math.ceil(encoded.length/LIMITS.partChars);onProgress?.(`Große Aufnahme · ${parts} verschlüsselte Abschnitte werden vorbereitet …`);await jsonPost('/capture-transfer/upload/init',{relay:pairing.relay,token:pairing.token,captureId:target.captureId,parts,totalChars:encoded.length});
    for(let part=0;part<parts;part++){onProgress?.(`Synchronisierung ${part+1} von ${parts} · lokale Kopie bleibt erhalten`);await jsonPost('/capture-transfer/upload/part',{relay:pairing.relay,token:pairing.token,part,data:encoded.slice(part*LIMITS.partChars,(part+1)*LIMITS.partChars)})}
    return jsonPost('/capture-transfer/upload/commit',{relay:pairing.relay,token:pairing.token,parts});
  }
  function backoffMs(attempt){return[0,15*60*1000,60*60*1000,4*60*60*1000,12*60*60*1000][Math.min(4,Math.max(1,attempt))]}
  async function sendDraft(target,{manual=false}={}){
    if(!target.pairing)throw new Error('Für diese Übertragung fehlt noch ein Ziel.');if(target.pendingRecording)throw new Error('Bitte die laufende Aufnahme zuerst sicher beenden.');
    target.status='sending';target.lastSyncError='';await persistDraft(target);if(target.captureId===draft?.captureId){draft=target;renderTransfer();await renderQueue()}
    const progress=text=>{if(target.captureId===draft?.captureId){$('#transferState').textContent=text;$('#transferState').className='save-state'}};
    try{const envelope=await encryptRelay(transferPayload(target),target.pairing.key),encoded=bytes64(new TextEncoder().encode(JSON.stringify(envelope)));await uploadEnvelope(target,encoded,progress);target.status='sent';target.sentAt=now();target.lastSyncError='';target.nextRetryAt=null;target.syncAttempts=0;target.lastRelay={relay:target.pairing.relay,sentAt:target.sentAt};target.pairing=null;await persistDraft(target);if(target.captureId===draft?.captureId){draft=target;justSent=true;renderTransfer();await refreshDraftSelect()}await renderQueue();return true}catch(error){target.status='queued';target.syncAttempts=Number(target.syncAttempts||0)+1;target.lastSyncError=error.message;target.nextRetryAt=new Date(Date.now()+backoffMs(target.syncAttempts)).toISOString();await persistDraft(target);if(target.captureId===draft?.captureId){draft=target;renderTransfer();$('#transferState').textContent='Nicht übertragen: '+error.message+' ✓ Die lokale Kopie bleibt erhalten.';$('#transferState').className='save-state err'}await refreshDraftSelect();await renderQueue();if(manual)throw error;return false}
  }
  async function sendToPersonalInbox(){
    if(!accessPairing)throw new Error('Dieses Gerät ist noch nicht mit deinem Praxis-Login gekoppelt. Öffne im Dashboard „Gerät verbinden“ und nutze einmalig den QR-Code oder Kopplungscode.');
    if(draft.pendingRecording)throw new Error('Bitte die laufende Aufnahme zuerst sicher beenden.');
    const workspace=draft.domain==='knowledge';if(workspace&&!accessPairing.workspaceKey)throw new Error('Dieses Capture-Gerät wurde noch ohne gemeinsamen Workspace-Schlüssel gekoppelt. Bitte im CRM einmal „Gerät verbinden“ neu ausführen; persönliche Dokumentations-Captures funktionieren weiterhin.');
    const x=await jsonPost('/capture-transfer/create-access',{pairId:accessPairing.pairId,accessToken:accessPairing.token,routingScope:workspace?'workspace':'personal',captureKind:draft.captureType});
    draft.pairing={relay:x.relay,token:x.token,key:workspace?accessPairing.workspaceKey:accessPairing.key,workspaceKeyId:workspace?accessPairing.workspaceKeyId||'':'',pairedAt:now(),kind:'inbox',generic:true,accessPairId:accessPairing.pairId,owner:accessPairing.owner||'',userId:accessPairing.userId||'',practiceId:accessPairing.practiceId||'',practitionerId:accessPairing.practitionerId||'',vaultId:accessPairing.vaultId||'',routingScope:workspace?'workspace':'personal'};
    draft.status='queued';draft.lastSyncError='';draft.nextRetryAt=null;await saveNow();renderTransfer();await renderQueue();return sendDraft(draft,{manual:true});
  }

  async function processQueue(manual=false){if(queueBusy||!navigator.onLine)return;queueBusy=true;if($('#retryQueue'))$('#retryQueue').disabled=true;try{const items=await allDrafts();for(const item of items){if(!item.pairing||!['queued','draft'].includes(item.status))continue;if(!manual&&item.nextRetryAt&&new Date(item.nextRetryAt).getTime()>Date.now())continue;await sendDraft(item,{manual:false})}}finally{queueBusy=false;if($('#retryQueue'))$('#retryQueue').disabled=false;await renderQueue()}}
  async function renderQueue(){const items=await allDrafts(),queued=items.filter(x=>x.status==='queued'),paired=items.filter(x=>x.pairing&&x.status!=='sent'),sent=items.filter(x=>x.status==='sent');$('#queueSummary').innerHTML=`<span class="queue-chip ${queued.length?'warn':'ok'}">${queued.length} wartet${queued.length===1?'':'en'} auf Sync</span><span class="queue-chip">${paired.length} verbunden</span><span class="queue-chip ok">${sent.length} an Praxis-Relay übertragen · lokale Kopie vorhanden</span>`;const rows=[...queued,...paired.filter(x=>!queued.includes(x))].slice(0,8);$('#queueList').innerHTML=rows.length?rows.map(item=>`<div class="queue-item"><div><strong>${esc(item.label||modeLabel(item.captureType))}</strong><small>${esc(statusLabel(item.status))}${item.nextRetryAt?' · nächster Versuch '+esc(fmt(item.nextRetryAt)):''}${item.lastSyncError?' · '+esc(item.lastSyncError):''}</small></div>${item.captureId===draft?.captureId&&item.pairing?'<button type="button" data-retry-current>Erneut versuchen</button>':''}</div>`).join(''):'<p class="help">Keine offenen Synchronisierungen. Neue Captures bleiben trotzdem lokal gespeichert.</p>';document.querySelector('[data-retry-current]')?.addEventListener('click',()=>sendDraft(draft,{manual:true}).catch(()=>{}))}
  function renderTransfer(){
    const isIdea=['idea','method'].includes(draft?.captureType),isMethod=draft?.captureType==='method',direct=!isIdea&&!!draft?.pairing&&draft.pairing.kind!=='inbox',hasAccess=!!accessPairing,sent=draft?.status==='sent';
    $('#accessPairingBox')?.classList.toggle('connected',hasAccess);$('#accessDot').classList.toggle('ok',hasAccess);$('#accessTitle').textContent=hasAccess?`Mit Praxis-Login verbunden${accessPairing.owner?' · '+accessPairing.owner:''}`:'Gerät noch nicht verbunden';
    $('#accessCopy').textContent=hasAccess?(isMethod?'Übungen können an die gemeinsame Praxis-Methoden-Inbox gesendet werden.':isIdea?'Ideen können direkt an den gemeinsamen Knowledge-Workspace gesendet werden.':'Captures können direkt an deine persönliche Dokumentations-Inbox gesendet werden.'):'Im CRM „Gerät verbinden“ wählen und einmalig QR-Code oder Kopplungscode verwenden.';$('#forgetAccess').hidden=!hasAccess;
    $('#targetBox')?.classList.toggle('direct',direct);if($('#targetTitle'))$('#targetTitle').textContent=isMethod?'Praxis · Methoden-Inbox':isIdea?'Praxis · Knowledge-Workspace':'Persönliche Dokumentations-Inbox';if($('#targetCopy'))$('#targetCopy').textContent=isMethod?'Audio wird lokal transkribiert. Der Entwurf entsteht später im Local Vault.':isIdea?'Audio wird lokal transkribiert; Text und Screenshots gehen ohne unnötige Verarbeitung in den Ideenspeicher.':'Klient:in und Sitzung kannst du später am Laptop zuordnen.';if($('#sendInboxBtn'))$('#sendInboxBtn').textContent=isMethod?'An die Praxis-Methoden-Inbox senden':isIdea?'An den gemeinsamen Knowledge-Workspace senden':'An meine Dokumentations-Inbox senden';
    $('#sendInboxBtn').hidden=sent||!hasAccess;$('#sendBtn').hidden=sent||!direct;$('#clearSessionPairing').hidden=sent||!direct;$('#newCaptureAfterSend').hidden=!sent;
    $('#scanBtn').hidden=sent;$('#scanBtn').className=(hasAccess?'ghost big':'primary big');$('#scanBtn').textContent=hasAccess?'Optional: Sitzungs-QR scannen':'🔗 Gerät verbinden';
    if(direct){const d=draft.pairing.sessionDate?new Intl.DateTimeFormat('de-AT',{dateStyle:'medium'}).format(new Date(draft.pairing.sessionDate+'T12:00:00')):'';$('#targetTitle').textContent=d?'Direkte Sitzung · '+d:'Direkte Sitzung';$('#targetCopy').textContent='Dieser QR ordnet die Erfassung direkt dieser Sitzung zu. Falls das nicht stimmt, entferne die Zuordnung und sende stattdessen an deine Inbox.';$('#transferTitle').textContent='Direkte Sitzungszuordnung';}
    else{$('#targetTitle').textContent=isMethod?'Praxis · Methoden-Inbox':isIdea?'Praxis · Knowledge-Workspace':'Persönliche Dokumentations-Inbox';$('#targetCopy').textContent=isIdea?(hasAccess?'Die Erfassung wird lokal verarbeitet; das Original bleibt erhalten.':'Verbinde dieses Gerät einmalig mit deinem Praxis-Login.'):(hasAccess?'Die konkrete Klient:innenakte oder Sitzung kannst du später am Laptop zuordnen.':'Verbinde dieses Gerät einmalig mit deinem Praxis-Login.');$('#transferTitle').textContent=sent?'Übertragung abgeschlossen':isMethod?'Praxis-Methoden-Inbox':isIdea?'Knowledge-Workspace':'Dokumentations-Inbox';}
    if(sent){$('#transferState').textContent='✓ Verschlüsselt übertragen. Die lokale Kopie bleibt hier; du kannst sofort eine neue Erfassung beginnen.';$('#transferState').className='save-state ok'}else if(draft.status==='queued'){$('#transferState').textContent='☁ Übertragung ausstehend. '+(draft.lastSyncError||'Die lokale Kopie ist sicher.');$('#transferState').className='save-state err'}else if(direct){$('#transferState').textContent='Direkte Sitzung vorgemerkt. Noch nichts übertragen.';$('#transferState').className='save-state'}else if(hasAccess){$('#transferState').textContent='Bereit zum sicheren Senden.';$('#transferState').className='save-state'}else{$('#transferState').textContent='Noch nicht verbunden. Die Erfassung bleibt vollständig lokal gespeichert.';$('#transferState').className='save-state'}
    if($('#connectionAction'))$('#connectionAction').classList.toggle('connected',hasAccess);if($('#connectionLabel'))$('#connectionLabel').textContent=hasAccess?'Verbunden':'Gerät verbinden';if(sent&&justSent)uiStage='success';updateProductUI();
  }
  async function applyPairing(value,sendAfter=false){
    const next=pairingFrom(value);
    if(draft.pairing&&draft.pairing.kind==='session'&&draft.pairing.relay!==next.relay&&!confirm('Diese Erfassung war bereits mit einer anderen Sitzung verbunden. Neue Sitzungszuordnung übernehmen? Du kannst alternativ ohne Zuordnung an deine Dokumentations-Inbox senden.'))return;
    draft.pairing=next;draft.status='draft';draft.lastSyncError='';draft.nextRetryAt=null;await saveNow();renderTransfer();await renderQueue();if(sendAfter)await sendDraft(draft,{manual:true});
  }

  function normalizePairCode(value){let raw=String(value||'').toUpperCase().replace(/[^A-Z2-9]/g,'');if(raw.startsWith('BD'))raw=raw.slice(2);raw=raw.slice(0,12);const groups=raw.match(/.{1,4}/g)||[];return 'BD-'+groups.join('-')}
  function openConnectionChoice(){if(accessPairing){uiStage='review';updateProductUI();return}if(draft?.deviceType==='boox'||/boox|onyx/i.test(navigator.userAgent||'')){openPairCodeDialog();return}$('#connectDialog')?.showModal()}
  function openPairCodeDialog(){const d=$('#pairCodeDialog');if(!d)return;$('#pairCodeInput').value='';$('#pairCodeState').textContent='Den Code findest du im CRM unter „Gerät verbinden“.';$('#pairCodeState').className='save-state';d.showModal();setTimeout(()=>$('#pairCodeInput')?.focus(),80)}
  async function derivePairHandshake(privateKey,peerPublicJwk){const peer=await crypto.subtle.importKey('jwk',peerPublicJwk,{name:'ECDH',namedCurve:'P-256'},false,[]);const bits=await crypto.subtle.deriveBits({name:'ECDH',public:peer},privateKey,256);return crypto.subtle.importKey('raw',bits,'AES-GCM',false,['decrypt'])}
  async function decryptPairPackage(envelope,key){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(envelope.iv)},key,from64(envelope.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
  async function claimPairingCode(value){
    const code=normalizePairCode(value);if(!/^BD-[A-Z2-9]{4}-[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(code))throw new Error('Bitte den vollständigen Kopplungscode eingeben.');
    const state=$('#pairCodeState')||$('#transferState');state.textContent='Sichere Geräte-Kopplung wird vorbereitet …';state.className='save-state';
    try{
      const keys=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),devicePublicJwk=await crypto.subtle.exportKey('jwk',keys.publicKey);
      const claim=await jsonPost('/capture-access/code/claim',{code,devicePublicJwk}),handshake=await derivePairHandshake(keys.privateKey,claim.adminPublicJwk);
      state.textContent='Code erkannt · warte auf Bestätigung im Praxis-CRM …';
      let ready=null;for(let i=0;i<75;i++){await new Promise(r=>setTimeout(r,800));const r=await fetch(API+'/capture-access/code/fetch?session='+encodeURIComponent(claim.pairingSessionId));let x={};try{x=await r.json()}catch(_){ }if(r.ok&&x.ok&&x.status==='ready'){ready=x;break}if(x.status==='expired'||r.status===410)throw new Error('Der Kopplungscode ist abgelaufen. Bitte im CRM einen neuen Code erzeugen.')}if(!ready)throw new Error('Die Kopplung wurde im CRM noch nicht bestätigt. Bitte den Dialog „Gerät verbinden“ dort geöffnet lassen und erneut versuchen.');
      const pkg=await decryptPairPackage(ready.envelope,handshake);await saveAccessPairing({pairId:pkg.pairId,token:pkg.accessToken,key:pkg.secret,workspaceKey:pkg.workspaceSecret||'',workspaceKeyId:pkg.workspaceKeyId||'',owner:pkg.owner||'',userId:pkg.userId||'',practiceId:pkg.practiceId||'',practitionerId:pkg.practitionerId||'',vaultId:pkg.vaultId||'',createdAt:now(),updatedAt:now()});
      $('#pairCodeDialog')?.close();$('#transferState').textContent='✓ Gerät sicher mit deinem Praxis-Login gekoppelt. Deine vorhandenen lokalen Captures können jetzt übertragen werden.';$('#transferState').className='save-state ok';renderTransfer();updateProductUI();
    }catch(error){state.textContent=error.message;state.className='save-state err';throw error}
  }
  async function startScanner(){await saveNow();const dialog=$('#scannerDialog');if($('#scannerTitle'))$('#scannerTitle').textContent=accessPairing?'Sitzungs-QR scannen':'Gerät verbinden';if($('#scannerEyebrow'))$('#scannerEyebrow').textContent=accessPairing?'Optionale Direktzuordnung':'Einmaliges Pairing';if($('#scannerCopy'))$('#scannerCopy').textContent=accessPairing?'Nur wenn du diese Erfassung sofort einer konkreten Sitzung zuordnen möchtest. Ohne Sitzungs-QR kannst du an deine persönliche Dokumentations-Inbox senden.':'Öffne im CRM „Gerät verbinden“ und scanne den dort angezeigten QR-Code.';dialog.showModal();$('#scannerState').textContent='Kamera wird gestartet …';try{if(!('BarcodeDetector'in window))throw new Error('Der integrierte QR-Scanner wird von diesem Browser nicht unterstützt. Der Entwurf ist sicher gespeichert; nutze die normale Kamera oder füge den QR-Link ein.');const formats=await BarcodeDetector.getSupportedFormats();if(!formats.includes('qr_code'))throw new Error('Dieser Browser kann keine QR-Codes erkennen.');const detector=new BarcodeDetector({formats:['qr_code']});scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=$('#scannerVideo');video.srcObject=scannerStream;await video.play();$('#scannerState').textContent='QR-Code in den Rahmen halten …';const scan=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){const value=codes[0].rawValue;stopScanner();dialog.close();const url=new URL(value,location.href);if(url.searchParams.get('accessPair')){await saveAccessPairing(accessPairingFrom(value));$('#transferState').textContent='✓ Gerät mit deinem Praxis-Login gekoppelt. Ab jetzt kannst du ohne Sitzungs-QR an die Dokumentations-Inbox senden.';$('#transferState').className='save-state ok'}else{await applyPairing(value,false);$('#transferState').textContent='Sitzungs-QR übernommen, aber noch nicht gesendet. Prüfe das Ziel oder sende stattdessen an deine Inbox.';$('#transferState').className='save-state'}return}}catch(error){$('#scannerState').textContent=error.message;return}scannerTimer=setTimeout(scan,180)};scan()}catch(error){$('#scannerState').textContent=error.message}}
  function stopScanner(){clearTimeout(scannerTimer);scannerStream?.getTracks().forEach(track=>track.stop());scannerStream=null;$('#scannerVideo').srcObject=null}

  async function encryptPassword(payload,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt']),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return{format:'bdcapture-1',kdf:'PBKDF2-SHA256',iterations:250000,salt:bytes64(salt),iv:bytes64(iv),ciphertext:bytes64(new Uint8Array(cipher))}}
  async function exportFile(){const password=$('#password').value;if(password.length<10)throw new Error('Bitte ein Exportpasswort mit mindestens 10 Zeichen wählen.');await saveNow();const box=await encryptPassword(transferPayload(),password),blob=new Blob([JSON.stringify(box)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='praxis-capture-'+draft.createdAt.replace(/[:.]/g,'-')+'.bdcapture';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}

  function meaningfulInk(){return (draft?.inkPages||[]).some(page=>(page.strokes||[]).length)}
  function hasCaptureContent(){return !!((draft?.audio||[]).length||String(draft?.noteText||'').trim()||(draft?.photos||[]).length||meaningfulInk()||(draft?.captureType==='method'&&String(draft.methodSourceUrl||'').trim()))}
  function captureCounts(){return{audio:(draft?.audio||[]).length,notes:String(draft?.noteText||'').trim()?1:0,photos:(draft?.photos||[]).length,pages:(draft?.inkPages||[]).filter(p=>(p.strokes||[]).length).length}}
  function setStage(stage){const changed=renderedStage!==stage;uiStage=stage;renderedStage=stage;['captureHome','captureWork','captureReview','captureSuccess'].forEach(id=>$('#'+id)?.classList.toggle('active',id===({home:'captureHome',capture:'captureWork',review:'captureReview',success:'captureSuccess'}[stage]||'captureHome')));if(stage==='capture'&&changed)setTimeout(resizeCanvas,80);if(changed)window.scrollTo({top:0,behavior:'smooth'})}
  function updateProductUI(){if(!draft)return;const has=hasCaptureContent(),counts=captureCounts(),sent=draft.status==='sent';if(sent&&uiStage==='capture')uiStage='home';setStage(uiStage);if($('#resumeCard'))$('#resumeCard').hidden=!has&&!sent;$('#resumeCard')?.classList.toggle('transferred',sent);if($('#resumeCard .resume-kicker'))$('#resumeCard .resume-kicker').textContent=sent?'✓ Übertragung abgeschlossen':'Letzte Erfassung';if($('#resumeTitle'))$('#resumeTitle').textContent=draft.label||modeLabel(draft.captureType);if($('#resumeMeta'))$('#resumeMeta').textContent=sent?`${fmt(draft.sentAt||draft.updatedAt)} · verschlüsselt übertragen. Du kannst jetzt etwas Neues erfassen, ohne diese Kopie zu löschen.`:`${fmt(draft.updatedAt||draft.createdAt)} · ${statusLabel(draft.status)}`;if($('#resumeDraft'))$('#resumeDraft').textContent=sent?'+ Neue Erfassung':'Fortsetzen';if($('#backToCapture'))$('#backToCapture').textContent=sent?'‹ Zur Übersicht':'‹ Bearbeiten';if($('#goToReview'))$('#goToReview').disabled=!has||!!recorder;const parts=[];if(counts.audio)parts.push(`${counts.audio} Audio`);if(counts.pages)parts.push(`${counts.pages} Handschriftseite${counts.pages===1?'':'n'}`);if(counts.notes)parts.push('Textnotiz');if(counts.photos)parts.push(`${counts.photos} Foto${counts.photos===1?'':'s'}`);if($('#reviewSummary'))$('#reviewSummary').innerHTML=`<div><span>Erfassung</span><strong>${esc(modeLabel(draft.captureType))}</strong></div><div><span>Inhalt</span><strong>${esc(parts.join(' · ')||'noch leer')}</strong></div><div><span>Status</span><strong>${esc(statusLabel(draft.status))}</strong></div>`;if($('#reviewPreview'))$('#reviewPreview').textContent=sent?'Diese Erfassung wurde verschlüsselt übertragen. Die lokale Kopie bleibt auf diesem Gerät.':draft.label?`Titel: ${draft.label}`:draft.captureType==='method'?'Die Übung wird lokal verarbeitet und später in der Methoden-Inbox geprüft.':draft.captureType==='idea'?'Die Idee wird lokal verarbeitet und später in der Ideen-Inbox geprüft.':'Du kannst die Zuordnung zur konkreten Sitzung später in der Dokumentations-Inbox vornehmen.';if($('#captureSuccessCopy'))$('#captureSuccessCopy').textContent=`Verschlüsselt an deine ${draft.captureType==='method'?'Methoden-Inbox':draft.captureType==='idea'?'Ideen-Inbox':'Dokumentations-Inbox'} übertragen. Die lokale Kopie bleibt auf diesem Gerät erhalten. Du kannst eine neue Erfassung beginnen, ohne sie zu löschen.`;if($('#workSaveState'))$('#workSaveState').textContent=draft.status==='queued'?'☁ Übertragung wartet · lokal sicher':'✓ Wird automatisch gespeichert';}
  async function storageInfo(){try{const persisted=await navigator.storage?.persist?.(),estimate=await navigator.storage?.estimate?.(),used=Number(estimate?.usage||0),quota=Number(estimate?.quota||0);$('#storageState').textContent=`${persisted?'Persistenter Gerätespeicher aktiv':'Lokaler Gerätespeicher aktiv'}${quota?` · ${Math.round(used/1048576)} MB von ${Math.round(quota/1048576)} MB verwendet`:''}. Cloudflare-Ausfälle löschen keine Erfassung.`}catch(_){ }}
  function updateNetwork(){const online=navigator.onLine;$('#networkState').textContent=online?'● online':'● offline · local-first';$('#networkState').className='status-pill '+(online?'online':'offline');if(online)setTimeout(()=>processQueue(false),800)}

  async function createNewDraft(){if(recorder?.state==='recording')return;await saveNow();draft=blankDraft();activePage=0;uiStage='home';justSent=false;renderAll();await saveNow();await refreshDraftSelect();await renderQueue();updateProductUI()}

  document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=async()=>{if(draft?.status==='sent')await createNewDraft();setMode(button.dataset.mode)});
  $('#resumeDraft')?.addEventListener('click',()=>{if(draft?.status==='sent'){createNewDraft();return}uiStage='capture';updateProductUI()});
  $('#backHome')?.addEventListener('click',()=>{uiStage='home';updateProductUI()});
  $('#goToReview')?.addEventListener('click',async()=>{await saveNow();if(!hasCaptureContent())return;renderTransfer();uiStage='review';updateProductUI()});
  $('#backToCapture')?.addEventListener('click',()=>{if(draft?.status==='sent'){createNewDraft();return}uiStage='capture';updateProductUI()});
  $('#successNewCapture')?.addEventListener('click',()=>createNewDraft());
  $('#successHome')?.addEventListener('click',()=>createNewDraft());
  $('#connectionAction')?.addEventListener('click',()=>{if(!accessPairing)openConnectionChoice();else{uiStage='review';updateProductUI()}});

  ['label','noteText','methodSourceDescription','methodSourceUrl'].forEach(id=>$('#'+id).addEventListener('input',()=>scheduleSave()));$('#methodSourceType').addEventListener('change',()=>scheduleSave());$('#deviceType').addEventListener('input',()=>{syncFromForm();applyDeviceProfile();resizeCanvas();scheduleSave('Geräteprofil wird gespeichert …')});$('#consentConfirmed').addEventListener('change',()=>{scheduleSave();updateRecordStartState()});
  $('#inkMode').onclick=()=>{const next=localStorage.getItem(EINK_KEY)!=='1';localStorage.setItem(EINK_KEY,next?'1':'0');applyDeviceProfile();resizeCanvas()};
  $('#inkExpand').onclick=()=>{document.body.classList.toggle('ink-expanded');$('#inkExpand').textContent=document.body.classList.contains('ink-expanded')?'↙ Klein schreiben':'⛶ Groß schreiben';setTimeout(resizeCanvas,80)};
  $('#inkPrev').onclick=()=>{activePage--;renderInkPages()};$('#inkNext').onclick=()=>{activePage++;renderInkPages()};$('#inkPageSelect').onchange=event=>{activePage=Number(event.target.value);renderInkPages()};
  $('#inkAdd').onclick=()=>{if(draft.inkPages.length>=LIMITS.pages){alert(`Maximal ${LIMITS.pages} Handschriftseiten pro Erfassung.`);return}draft.inkPages.push({id:uid(),createdAt:now(),strokes:[]});activePage=draft.inkPages.length-1;renderInkPages();scheduleSave()};
  $('#inkDelete').onclick=()=>{if(draft.inkPages.length===1||!confirm('Diese Handschriftseite wirklich löschen?'))return;draft.inkPages.splice(activePage,1);activePage=Math.min(activePage,draft.inkPages.length-1);renderInkPages();scheduleSave()};
  $('#inkUndo').onclick=async()=>{page().strokes.pop();drawInk();await saveNow({quiet:true})};$('#inkClear').onclick=async()=>{if(confirm('Diese Handschriftseite wirklich leeren?')){page().strokes=[];drawInk();await saveNow({quiet:true})}};
  canvas.onpointerdown=event=>{event.preventDefault();canvas.setPointerCapture(event.pointerId);activeStroke=[inkPoint(event)];activeStrokeIndex=page().strokes.length;page().strokes.push(activeStroke)};
  canvas.onpointermove=event=>{if(!activeStroke)return;event.preventDefault();const source=event.getCoalescedEvents?.()||[event],points=[];for(const e of source){const point=inkPoint(e),last=activeStroke[activeStroke.length-1];if(!last||Math.abs(point.x-last.x)+Math.abs(point.y-last.y)>.00015)points.push(point)}if(points.length)drawInkPoints(points)};
  const finishInkStroke=async event=>{if(!activeStroke)return;event?.preventDefault?.();const stroke=activeStroke,pageId=page().id,index=activeStrokeIndex;if(stroke.length===1){const rect=canvas.getBoundingClientRect();prepareInkContext();ctx.beginPath();ctx.moveTo(stroke[0].x*rect.width,stroke[0].y*rect.height);ctx.lineTo(stroke[0].x*rect.width+.2,stroke[0].y*rect.height+.2);ctx.stroke()}activeStroke=null;activeStrokeIndex=-1;journalInkStroke(pageId,index,stroke);scheduleInkSnapshot()};canvas.onpointerup=finishInkStroke;canvas.onpointercancel=finishInkStroke;
  $('#photoInput').addEventListener('pointerdown',()=>saveNow());$('#photoInput').onchange=async event=>{try{const files=[...event.target.files];event.target.value='';for(const file of files){if(draft.photos.length>=LIMITS.photos){alert(`Maximal ${LIMITS.photos} Fotos pro Erfassung.`);break}$('#saveState').textContent='Foto wird verarbeitet und lokal gespeichert …';draft.photos.push(await compressPhoto(file));await saveNow()}renderPhotos()}catch(error){$('#saveState').textContent='Foto konnte nicht verarbeitet werden: '+error.message;$('#saveState').className='save-state err'}};
  if($('#ideaSourceType'))$('#ideaSourceType').onchange=e=>{draft.ideaSourceType=e.target.value;scheduleSave()};if($('#ideaSourceUrl'))$('#ideaSourceUrl').oninput=e=>{draft.ideaSourceUrl=e.target.value;scheduleSave()};
  $('#recordStart').onclick=startRecording;$('#recordStop').onclick=stopRecording;
  $('#newDraft').onclick=createNewDraft;$('#newCaptureAfterSend').onclick=createNewDraft;
  $('#deleteDraft').onclick=async()=>{if(recorder?.state==='recording')return;const warning=draft.status==='sent'?'Diese Erfassung wurde bereits verschlüsselt übertragen. Du musst die lokale Kopie für eine neue Aufnahme nicht löschen. Möchtest du sie auf diesem Gerät trotzdem löschen?':draft.status==='queued'||draft.pairing?'Diese gesamte Erfassung ist noch nicht sicher übernommen. Wirklich die lokale Kopie vollständig verwerfen?':'Diese gesamte aktuelle Erfassung wirklich verwerfen? Einzelne Audio-, Foto- oder Handschrift-Elemente kannst du direkt beim jeweiligen Element entfernen.';if(!confirm(warning))return;const id=draft.captureId;if(draft.pendingRecording?.id)await clearRecordingRows(id,draft.pendingRecording.id);await dbDelete('drafts',id);await clearInkJournalCapture(id);const rows=await allDrafts();await loadDraft(rows[0]?.captureId||null)};
  $('#draftSelect').onchange=async event=>{if(recorder?.state==='recording')return;await saveNow();await loadDraft(event.target.value)};
  $('#scanBtn').onclick=openConnectionChoice;$('#sendBtn').onclick=()=>sendDraft(draft,{manual:true}).catch(()=>{});$('#sendInboxBtn').onclick=()=>sendToPersonalInbox().catch(error=>{$('#transferState').textContent=error.message;$('#transferState').className='save-state err'});$('#clearSessionPairing').onclick=async()=>{draft.pairing=null;draft.status='draft';draft.lastSyncError='';draft.nextRetryAt=null;await saveNow();renderTransfer();await renderQueue()};$('#forgetAccess').onclick=async()=>{if(!confirm('Kopplung dieses Geräts mit dem Praxis-Login entfernen? Lokale Captures bleiben erhalten.'))return;await saveAccessPairing(null)};if($('#retryQueue'))$('#retryQueue').onclick=()=>processQueue(true);$('#scannerClose').onclick=()=>$('#scannerDialog').close();$('#scannerDialog').addEventListener('close',stopScanner);
  $('#pairingApply').onclick=async()=>{try{const value=$('#pairingInput').value.trim();if(/^BD[- ]/i.test(value)){await claimPairingCode(value);return}const url=new URL(value,location.href);if(url.searchParams.get('accessPair')){await saveAccessPairing(accessPairingFrom(value));$('#transferState').textContent='✓ Praxis-Kopplung übernommen. Ab jetzt kannst du ohne Sitzungs-QR senden.';$('#transferState').className='save-state ok'}else await applyPairing(value,false)}catch(error){ $('#transferState').textContent=error.message;$('#transferState').className='save-state err'}};
  $('#connectQrBtn')?.addEventListener('click',()=>{$('#connectDialog').close();startScanner()});
  $('#connectCodeBtn')?.addEventListener('click',()=>{$('#connectDialog').close();openPairCodeDialog()});
  $('#connectClose')?.addEventListener('click',()=>$('#connectDialog').close());
  $('#pairCodeClose')?.addEventListener('click',()=>$('#pairCodeDialog').close());
  $('#pairCodeSubmit')?.addEventListener('click',()=>claimPairingCode($('#pairCodeInput').value).catch(()=>{}));
  $('#pairCodeInput')?.addEventListener('input',event=>{event.target.value=normalizePairCode(event.target.value)});
  $('#pairCodeInput')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();claimPairingCode(event.target.value).catch(()=>{})}});
  $('#exportBtn').onclick=()=>exportFile().then(()=>{$('#transferState').textContent='Verschlüsselte Exportdatei wurde erstellt. Die lokale Kopie bleibt erhalten.';$('#transferState').className='save-state ok'}).catch(error=>{$('#transferState').textContent=error.message;$('#transferState').className='save-state err'});

  document.addEventListener('focusin',event=>{if(event.target?.matches?.('textarea,input[type="text"],input[type="search"]'))document.body.classList.add('capture-typing')});
  document.addEventListener('focusout',event=>{if(event.target?.matches?.('textarea,input[type="text"],input[type="search"]'))setTimeout(()=>document.body.classList.remove('capture-typing'),60)});
  window.addEventListener('resize',resizeCanvas);window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(recorder?.state==='recording')stopRecording();else saveNow()}else if(recorder?.state==='recording')acquireWakeLock()});window.addEventListener('pagehide',()=>{if(recorder?.state==='recording')stopRecording();else saveNow()});
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice.catch(()=>{});installPrompt=null;$('#installBtn').hidden=true};window.addEventListener('appinstalled',()=>{$('#installBtn').hidden=true});

  async function init(){
    try{uiStage='home';await getDeviceKey();await loadAccessPairing();await storageInfo();const active=localStorage.getItem(ACTIVE_KEY);await loadDraft(active);if(draft.status==='sent')await createNewDraft();const params=new URLSearchParams(location.search);if(params.get('accessPair')){await saveAccessPairing(accessPairingFrom(location.href));history.replaceState({},'',location.pathname);$('#transferState').textContent='✓ Dieses Gerät ist jetzt deinem Praxis-Login zugeordnet. Künftige Captures können ohne Sitzungs-QR an deine Inbox gesendet werden.';$('#transferState').className='save-state ok'}else if(params.get('relay')){await applyPairing(location.href,false);history.replaceState({},'',location.pathname);$('#transferState').textContent='Sitzungs-Verbindung übernommen. Prüfe das Ziel; du kannst auch ohne Zuordnung an deine Inbox senden.';$('#transferState').className='save-state ok'}const quickType=params.get('type');if(['idea','method','note','dictation'].includes(quickType)){if(draft.status!=='draft'||draft.noteText||draft.audio.length||draft.photos.length||draft.inkPages.some(p=>p.strokes?.length))await createNewDraft();setMode(quickType);uiStage='capture';history.replaceState({},'',location.pathname)}if('serviceWorker'in navigator)navigator.serviceWorker.register('capture-sw.js').catch(()=>{});updateNetwork();setTimeout(()=>processQueue(false),1200)}catch(error){$('#saveState').textContent='Capture konnte nicht initialisiert werden: '+error.message;$('#saveState').className='save-state err'}
  }
  init();
})();
