(function(){
  'use strict';
  const $=selector=>document.querySelector(selector);
  const API=String(window.BD_BOOKING_CONFIG?.apiBaseUrl||'https://beziehungsdynamiken-booking.theophil-kroller.workers.dev').replace(/\/$/,'');
  const DB_NAME='bd-praxis-capture-v3',DB_VERSION=1,ACTIVE_KEY='bd_capture_active_v3';
  const LIMITS={photos:12,audio:12,pages:20,payloadBytes:9*1024*1024};
  const canvas=$('#inkCanvas'),ctx=canvas.getContext('2d');
  let dbPromise=null,deviceKey=null,draft=null,activePage=0,activeStroke=null,saveTimer=0,saveChain=Promise.resolve();
  let recorder=null,stream=null,chunks=[],recordStarted=0,recordTick=0,scannerStream=null,scannerTimer=0,audioUrls=[];

  function uid(){return crypto.randomUUID()}
  function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function now(){return new Date().toISOString()}
  function bytes64(bytes){let value='';for(let i=0;i<bytes.length;i+=0x8000)value+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(value)}
  function from64(value){let source=String(value||'').replace(/-/g,'+').replace(/_/g,'/');while(source.length%4)source+='=';const raw=atob(source),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
  function fmt(value){return new Intl.DateTimeFormat('de-AT',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
  function formatTime(seconds){return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
  function blankDraft(){return{version:3,captureId:uid(),createdAt:now(),updatedAt:now(),deviceType:'s22',label:'',noteText:'',inkPages:[{id:uid(),createdAt:now(),strokes:[]}],audio:[],photos:[],pairing:null,status:'draft'}}

  function openDb(){
    if(dbPromise)return dbPromise;
    dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains('drafts'))database.createObjectStore('drafts');if(!database.objectStoreNames.contains('meta'))database.createObjectStore('meta')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
    return dbPromise;
  }
  async function dbGet(store,key){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),request=tx.objectStore(store).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function dbPut(store,key,value){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
  async function dbDelete(store,key){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
  async function dbEntries(store){const database=await openDb();return new Promise((resolve,reject)=>{const rows=[],tx=database.transaction(store,'readonly'),request=tx.objectStore(store).openCursor();request.onsuccess=()=>{const cursor=request.result;if(cursor){rows.push([cursor.key,cursor.value]);cursor.continue()}else resolve(rows)};request.onerror=()=>reject(request.error)})}
  async function getDeviceKey(){if(deviceKey)return deviceKey;const stored=await dbGet('meta','device-key');if(stored?.raw){deviceKey=await crypto.subtle.importKey('raw',from64(stored.raw),'AES-GCM',false,['encrypt','decrypt']);return deviceKey}if(stored?.type){deviceKey=stored;return deviceKey}const raw=crypto.getRandomValues(new Uint8Array(32));deviceKey=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);await dbPut('meta','device-key',{raw:bytes64(raw)});return deviceKey}
  async function encryptDraft(value){const key=await getDeviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return{iv,cipher,createdAt:value.createdAt,updatedAt:value.updatedAt,status:value.status||'draft'}}
  async function decryptDraft(row){const key=await getDeviceKey(),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(row.iv)},key,row.cipher);return JSON.parse(new TextDecoder().decode(plain))}

  function syncFromForm(){if(!draft)return;draft.deviceType=$('#deviceType').value;draft.label=$('#label').value.trim();draft.noteText=$('#noteText').value;draft.updatedAt=now()}
  function scheduleSave(message='Änderung wird verschlüsselt gespeichert …'){if(!draft)return;syncFromForm();clearTimeout(saveTimer);$('#saveState').textContent=message;$('#saveState').className='save-state';saveTimer=setTimeout(()=>saveNow(),350)}
  function saveNow(){if(!draft)return Promise.resolve();syncFromForm();const copy=JSON.parse(JSON.stringify(draft));saveChain=saveChain.then(async()=>{try{await dbPut('drafts',copy.captureId,await encryptDraft(copy));localStorage.setItem(ACTIVE_KEY,copy.captureId);if(draft?.captureId===copy.captureId){$('#saveState').textContent='Verschlüsselt lokal gespeichert · '+new Date().toLocaleTimeString('de-AT');$('#saveState').className='save-state ok';$('#draftState').textContent=draft.status==='sent'?'Übertragen – lokale Kopie vorhanden':'Entwurf sicher auf diesem Gerät'}}catch(error){$('#saveState').textContent='Lokales Speichern fehlgeschlagen: '+error.message;$('#saveState').className='save-state err'}});return saveChain}
  async function loadDraft(id){const row=id&&await dbGet('drafts',id);draft=row?await decryptDraft(row):blankDraft();draft.inkPages=Array.isArray(draft.inkPages)&&draft.inkPages.length?draft.inkPages:[{id:uid(),createdAt:now(),strokes:Array.isArray(draft.strokes)?draft.strokes:[]}];draft.audio=Array.isArray(draft.audio)?draft.audio:[];draft.photos=Array.isArray(draft.photos)?draft.photos:[];activePage=0;localStorage.setItem(ACTIVE_KEY,draft.captureId);renderAll();await saveNow();await refreshDraftSelect()}
  async function refreshDraftSelect(){const rows=await dbEntries('drafts'),items=[];for(const [id,row] of rows){try{const value=await decryptDraft(row);items.push(value)}catch(error){}}items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('#draftSelect').innerHTML=items.map(item=>`<option value="${esc(item.captureId)}">${item.status==='sent'?'✓ ':''}${esc(item.label||'Erfassung '+fmt(item.createdAt))}</option>`).join('');$('#draftSelect').value=draft.captureId}

  function renderAll(){
    $('#deviceType').value=draft.deviceType||'s22';$('#label').value=draft.label||'';$('#noteText').value=draft.noteText||'';
    renderPhotos();renderAudio();renderInkPages();renderTransfer();resizeCanvas();
    $('#draftState').textContent=draft.status==='sent'?'Übertragen – lokale Kopie vorhanden':'Entwurf sicher auf diesem Gerät';
  }
  function renderPhotos(){$('#photoPreview').innerHTML=draft.photos.length?draft.photos.map((photo,index)=>`<article class="media-item"><img src="data:${esc(photo.mime)};base64,${photo.dataBase64}" alt="Foto ${index+1}"><div class="media-copy"><strong>${esc(photo.name||'Foto '+(index+1))}</strong><small>Foto ${index+1} von ${draft.photos.length}</small></div><button class="danger" data-photo-delete="${index}" type="button">Entfernen</button></article>`).join(''):'<p class="help">Noch keine Fotos hinzugefügt.</p>';document.querySelectorAll('[data-photo-delete]').forEach(button=>button.onclick=()=>{draft.photos.splice(Number(button.dataset.photoDelete),1);renderPhotos();scheduleSave()})}
  function audioBlob(item){return new Blob([from64(item.dataBase64)],{type:item.mime||'audio/webm'})}
  function renderAudio(){audioUrls.forEach(URL.revokeObjectURL);audioUrls=[];const host=$('#audioList');if(!draft.audio.length){host.innerHTML='<p class="help">Noch keine Aufnahmen vorhanden.</p>';return}host.innerHTML='';draft.audio.forEach((item,index)=>{const url=URL.createObjectURL(audioBlob(item));audioUrls.push(url);const article=document.createElement('article');article.className='media-item';article.innerHTML=`<div class="media-copy"><strong>Aufnahme ${index+1}</strong><small>${formatTime(Number(item.durationSeconds||0))}</small></div><audio controls src="${url}"></audio><button class="danger" type="button">Entfernen</button>`;article.querySelector('button').onclick=()=>{draft.audio.splice(index,1);renderAudio();scheduleSave()};host.appendChild(article)})}
  function page(){return draft.inkPages[activePage]}
  function renderInkPages(){activePage=Math.max(0,Math.min(activePage,draft.inkPages.length-1));$('#inkPageSelect').innerHTML=draft.inkPages.map((item,index)=>`<option value="${index}">Seite ${index+1}</option>`).join('');$('#inkPageSelect').value=String(activePage);$('#inkPageState').textContent=`Seite ${activePage+1} von ${draft.inkPages.length}`;$('#inkPrev').disabled=activePage===0;$('#inkNext').disabled=activePage===draft.inkPages.length-1;$('#inkDelete').disabled=draft.inkPages.length===1;drawInk()}
  function resizeCanvas(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(rect.width*ratio));canvas.height=Math.max(1,Math.floor(rect.height*ratio));ctx.setTransform(ratio,0,0,ratio,0,0);drawInk()}
  function drawInk(){const rect=canvas.getBoundingClientRect();ctx.clearRect(0,0,rect.width,rect.height);ctx.lineWidth=2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#111';for(const stroke of page()?.strokes||[]){if(!stroke.length)continue;ctx.beginPath();ctx.moveTo(stroke[0].x*rect.width,stroke[0].y*rect.height);for(const point of stroke.slice(1))ctx.lineTo(point.x*rect.width,point.y*rect.height);if(stroke.length===1)ctx.lineTo(stroke[0].x*rect.width+.2,stroke[0].y*rect.height+.2);ctx.stroke()}}
  function inkPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height,t:Date.now()}}

  async function compressPhoto(file){const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),work=document.createElement('canvas');work.width=Math.max(1,Math.round(bitmap.width*scale));work.height=Math.max(1,Math.round(bitmap.height*scale));work.getContext('2d').drawImage(bitmap,0,0,work.width,work.height);bitmap.close?.();const blob=await new Promise(resolve=>work.toBlob(resolve,'image/jpeg',.8));return{mime:'image/jpeg',name:(file.name||'foto').replace(/\.[^.]+$/,'')+'.jpg',dataBase64:bytes64(new Uint8Array(await blob.arrayBuffer())),createdAt:now()}}
  function recorderMime(){return['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type))||''}
  function lockDraftSwitch(locked){$('#newDraft').disabled=locked;$('#deleteDraft').disabled=locked;$('#draftSelect').disabled=locked;$('#photoInput').disabled=locked}
  async function startRecording(){if(draft.audio.length>=LIMITS.audio){$('#recordState').textContent=`Maximal ${LIMITS.audio} Aufnahmen pro Erfassung.`;return}try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});chunks=[];const mime=recorderMime();recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=finishRecording;recorder.start(1000);recordStarted=Date.now();lockDraftSwitch(true);$('#recordStart').disabled=true;$('#recordStop').disabled=false;$('#recordState').textContent='Aufnahme läuft – beim App-Wechsel wird automatisch gestoppt und gespeichert.';recordTick=setInterval(()=>$('#recordTime').textContent=formatTime(Math.round((Date.now()-recordStarted)/1000)),500)}catch(error){lockDraftSwitch(false);$('#recordState').textContent='Mikrofon nicht verfügbar: '+error.message}}
  async function finishRecording(){if(!recordStarted)return;const duration=Math.max(1,Math.round((Date.now()-recordStarted)/1000)),blob=new Blob(chunks,{type:recorder?.mimeType||'audio/webm'}),bytes=new Uint8Array(await blob.arrayBuffer());stream?.getTracks().forEach(track=>track.stop());stream=null;clearInterval(recordTick);recordStarted=0;draft.audio.push({id:uid(),mime:blob.type||'audio/webm',durationSeconds:duration,dataBase64:bytes64(bytes),createdAt:now()});$('#recordTime').textContent='0:00';$('#recordState').textContent='Aufnahme hinzugefügt und wird gespeichert.';$('#recordStart').disabled=false;$('#recordStop').disabled=true;lockDraftSwitch(false);renderAudio();await saveNow()}
  function stopRecording(){if(recorder?.state==='recording')recorder.stop()}

  function pairingFrom(value){const url=new URL(String(value).trim(),location.href),relay=url.searchParams.get('relay')||'',token=url.searchParams.get('token')||'',key=url.searchParams.get('key')||'';if(!/^[a-f0-9]{32}$/i.test(relay)||token.length<32||key.length<32)throw new Error('Dieser QR-Code enthält keine vollständige Capture-Verbindung.');return{relay,token,key,pairedAt:now()}}
  function renderTransfer(){const paired=!!draft.pairing;$('#scanBtn').hidden=paired;$('#sendBtn').hidden=!paired;$('#transferTitle').textContent=paired?'Bereit zur Übertragung':'Mit Sitzung verbinden';$('#transferCopy').textContent=paired?'Der Entwurf ist mit dem QR-Code einer Sitzung gekoppelt. Du kannst ihn jetzt sicher übertragen.':'Öffne am Laptop den richtigen Session Flow und scanne dessen QR-Code. Dein Entwurf bleibt bis zur bestätigten Übertragung lokal gespeichert.';if(draft.status==='sent'){$('#transferState').textContent='Die Erfassung wurde verschlüsselt übertragen. Die lokale Kopie bleibt erhalten, bis du sie bewusst löschst.';$('#transferState').className='save-state ok'}else if(paired){$('#transferState').textContent='QR-Verbindung übernommen. Noch nicht übertragen.';$('#transferState').className='save-state'}else{$('#transferState').textContent='Noch keiner Sitzung zugeordnet.';$('#transferState').className='save-state'}}
  async function applyPairing(value,sendAfter=false){draft.pairing=pairingFrom(value);draft.status='draft';await saveNow();renderTransfer();if(sendAfter)await sendRelay()}
  function transferPayload(){return{version:3,captureId:draft.captureId,deviceType:draft.deviceType,label:draft.label,createdAt:draft.createdAt,updatedAt:draft.updatedAt,noteText:draft.noteText,inkPages:draft.inkPages,strokes:draft.inkPages[0]?.strokes||[],audio:draft.audio,photos:draft.photos}}
  async function encryptRelay(payload,keyText){const key=await crypto.subtle.importKey('raw',from64(keyText),'AES-GCM',false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return{format:'bdcapture-relay-1',iv:bytes64(iv),ciphertext:bytes64(new Uint8Array(cipher))}}
  async function sendRelay(){if(!draft.pairing)throw new Error('Bitte zuerst den QR-Code der Sitzung scannen.');syncFromForm();const payload=transferPayload(),plain=new TextEncoder().encode(JSON.stringify(payload));if(plain.byteLength>LIMITS.payloadBytes)throw new Error('Diese Erfassung ist für eine einzelne Übertragung zu groß. Bitte Fotos oder lange Diktate auf zwei Erfassungen aufteilen.');const button=$('#sendBtn');button.disabled=true;$('#transferState').textContent='Erfassung wird verschlüsselt übertragen …';try{const envelope=await encryptRelay(payload,draft.pairing.key),encoded=bytes64(new TextEncoder().encode(JSON.stringify(envelope))),response=await fetch(API+'/capture-transfer/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({relay:draft.pairing.relay,token:draft.pairing.token,ciphertext:encoded})}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Übertragung konnte nicht gesendet werden.');draft.status='sent';draft.sentAt=now();draft.pairing=null;await saveNow();renderTransfer();await refreshDraftSelect()}catch(error){$('#transferState').textContent='Nicht übertragen: '+error.message+' Der lokale Entwurf bleibt erhalten.';$('#transferState').className='save-state err';throw error}finally{button.disabled=false}}

  async function startScanner(){await saveNow();const dialog=$('#scannerDialog');dialog.showModal();$('#scannerState').textContent='Kamera wird gestartet …';try{if(!('BarcodeDetector'in window))throw new Error('Der integrierte QR-Scanner wird von diesem Browser nicht unterstützt. Der Entwurf ist sicher gespeichert; nutze die normale Kamera oder füge den QR-Link ein.');const formats=await BarcodeDetector.getSupportedFormats();if(!formats.includes('qr_code'))throw new Error('Dieser Browser kann keine QR-Codes erkennen.');const detector=new BarcodeDetector({formats:['qr_code']});scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=$('#scannerVideo');video.srcObject=scannerStream;await video.play();$('#scannerState').textContent='QR-Code in den Rahmen halten …';const scan=async()=>{if(!scannerStream)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){const value=codes[0].rawValue;stopScanner();dialog.close();await applyPairing(value,true);return}}catch(error){}scannerTimer=setTimeout(scan,180)};scan()}catch(error){$('#scannerState').textContent=error.message}}
  function stopScanner(){clearTimeout(scannerTimer);scannerStream?.getTracks().forEach(track=>track.stop());scannerStream=null;$('#scannerVideo').srcObject=null}

  async function encryptPassword(payload,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt']),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload)));return{format:'bdcapture-1',kdf:'PBKDF2-SHA256',iterations:250000,salt:bytes64(salt),iv:bytes64(iv),ciphertext:bytes64(new Uint8Array(cipher))}}
  async function exportFile(){const password=$('#password').value;if(password.length<10)throw new Error('Bitte ein Exportpasswort mit mindestens 10 Zeichen wählen.');await saveNow();const box=await encryptPassword(transferPayload(),password),blob=new Blob([JSON.stringify(box)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='praxis-capture-'+draft.createdAt.replace(/[:.]/g,'-')+'.bdcapture';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}

  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.id==='tab-'+button.dataset.tab));if(button.dataset.tab==='ink')setTimeout(resizeCanvas,50)});
  ['deviceType','label','noteText'].forEach(id=>$('#'+id).addEventListener('input',()=>scheduleSave()));
  $('#inkMode').onclick=()=>document.body.classList.toggle('ink');
  $('#inkExpand').onclick=()=>{document.body.classList.toggle('ink-expanded');$('#inkExpand').textContent=document.body.classList.contains('ink-expanded')?'↙ Klein schreiben':'⛶ Groß schreiben';setTimeout(resizeCanvas,80)};
  $('#inkPrev').onclick=()=>{activePage--;renderInkPages()};$('#inkNext').onclick=()=>{activePage++;renderInkPages()};$('#inkPageSelect').onchange=event=>{activePage=Number(event.target.value);renderInkPages()};
  $('#inkAdd').onclick=()=>{if(draft.inkPages.length>=LIMITS.pages){alert(`Maximal ${LIMITS.pages} Handschriftseiten pro Erfassung.`);return}draft.inkPages.push({id:uid(),createdAt:now(),strokes:[]});activePage=draft.inkPages.length-1;renderInkPages();scheduleSave()};
  $('#inkDelete').onclick=()=>{if(draft.inkPages.length===1||!confirm('Diese Handschriftseite wirklich löschen?'))return;draft.inkPages.splice(activePage,1);activePage=Math.min(activePage,draft.inkPages.length-1);renderInkPages();scheduleSave()};
  $('#inkUndo').onclick=()=>{page().strokes.pop();drawInk();scheduleSave()};$('#inkClear').onclick=()=>{if(confirm('Diese Handschriftseite wirklich leeren?')){page().strokes=[];drawInk();scheduleSave()}};
  canvas.onpointerdown=event=>{canvas.setPointerCapture(event.pointerId);activeStroke=[inkPoint(event)];page().strokes.push(activeStroke)};canvas.onpointermove=event=>{if(!activeStroke)return;activeStroke.push(inkPoint(event));drawInk()};canvas.onpointerup=canvas.onpointercancel=()=>{activeStroke=null;scheduleSave()};
  $('#photoInput').addEventListener('pointerdown',()=>saveNow());$('#photoInput').onchange=async event=>{try{const files=[...event.target.files];event.target.value='';for(const file of files){if(draft.photos.length>=LIMITS.photos){alert(`Maximal ${LIMITS.photos} Fotos pro Erfassung.`);break}$('#saveState').textContent='Foto wird verarbeitet und lokal gespeichert …';draft.photos.push(await compressPhoto(file));await saveNow()}renderPhotos()}catch(error){$('#saveState').textContent='Foto konnte nicht verarbeitet werden: '+error.message;$('#saveState').className='save-state err'}};
  $('#recordStart').onclick=startRecording;$('#recordStop').onclick=stopRecording;
  $('#newDraft').onclick=async()=>{await saveNow();draft=blankDraft();activePage=0;renderAll();await saveNow();await refreshDraftSelect()};
  $('#deleteDraft').onclick=async()=>{if(!confirm('Diesen lokal gespeicherten Entwurf wirklich löschen?'))return;const id=draft.captureId;await dbDelete('drafts',id);const rows=await dbEntries('drafts');await loadDraft(rows[0]?.[0]||null)};
  $('#draftSelect').onchange=async event=>{await saveNow();await loadDraft(event.target.value)};
  $('#scanBtn').onclick=startScanner;$('#sendBtn').onclick=()=>sendRelay().catch(()=>{});$('#scannerClose').onclick=()=>$('#scannerDialog').close();$('#scannerDialog').addEventListener('close',stopScanner);
  $('#pairingApply').onclick=()=>applyPairing($('#pairingInput').value,false).catch(error=>{$('#transferState').textContent=error.message;$('#transferState').className='save-state err'});
  $('#exportBtn').onclick=()=>exportFile().then(()=>{$('#transferState').textContent='Verschlüsselte Exportdatei wurde erstellt.';$('#transferState').className='save-state ok'}).catch(error=>{$('#transferState').textContent=error.message;$('#transferState').className='save-state err'});
  window.addEventListener('resize',resizeCanvas);document.addEventListener('visibilitychange',()=>{if(document.hidden){if(recorder?.state==='recording')stopRecording();else saveNow()}});window.addEventListener('pagehide',()=>saveNow());

  async function init(){
    try{await getDeviceKey();await navigator.storage?.persist?.();const active=localStorage.getItem(ACTIVE_KEY);await loadDraft(active);const params=new URLSearchParams(location.search);if(params.get('relay')){await applyPairing(location.href,false);history.replaceState({},'',location.pathname);$('#transferState').textContent='QR-Verbindung übernommen. Dein vorhandener Entwurf ist bereit zur Übertragung.';$('#transferState').className='save-state ok'}if('serviceWorker'in navigator)navigator.serviceWorker.register('capture-sw.js').catch(()=>{})}catch(error){$('#saveState').textContent='Capture konnte nicht initialisiert werden: '+error.message;$('#saveState').className='save-state err'}
  }
  init();
})();
