(function(){
  "use strict";
  const KEY = "bd_cart_v1";
  const DEFAULT_API="https://beziehungsdynamiken-booking.theophil-kroller.workers.dev";
  function getCart(){try{const value=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(value))return[];return value.filter(item=>{const price=Number(item?.price);return item?.price!==null&&item?.price!==undefined&&item?.price!==""&&Number.isFinite(price)&&price>=0})}catch(e){return[]}}
  function saveCart(items){localStorage.setItem(KEY,JSON.stringify(items));updateBadges();window.dispatchEvent(new CustomEvent("bd-cart-updated",{detail:items}))}
  function count(items){return items.reduce((sum,item)=>sum+Math.max(1,Number(item.qty||1)),0)}
  function updateBadges(){const n=count(getCart());document.querySelectorAll("[data-cart-count]").forEach(el=>{el.textContent=String(n);el.hidden=n===0})}
  window.BDCart={get:getCart,set:saveCart,add(item){const items=getCart(),key=item.id||item.sku||item.name,existing=items.find(x=>(x.id||x.sku||x.name)===key);if(existing){if(item.unique||existing.unique)existing.qty=1;else existing.qty=Number(existing.qty||1)+Number(item.qty||1)}else items.push({...item,qty:Number(item.qty||1)});saveCart(items)},remove(key){saveCart(getCart().filter(x=>(x.id||x.sku||x.name)!==key))},clear(){saveCart([])},count(){return count(getCart())},updateBadges};
  const apiBase=()=>String(window.BD_BOOKING_CONFIG?.apiBaseUrl||DEFAULT_API).replace(/\/$/,"");
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const moneyCents=(c,lang="de")=>new Intl.NumberFormat(lang==="en"?"en-IE":"de-AT",{style:"currency",currency:"EUR"}).format(Number(c||0)/100);
  const getLang=()=>document.documentElement.lang==="en"?"en":"de";
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  async function getPublicConfig(){try{const r=await fetch(apiBase()+"/public-config",{cache:"no-store"});if(!r.ok)throw new Error();return await r.json()}catch(e){return{ok:false,stripeEnabled:false,appointmentFees:{individual:0,couple:0}}}}
  async function checkoutStatus(sessionId){for(let i=0;i<12;i++){const r=await fetch(apiBase()+"/stripe/checkout-status?session_id="+encodeURIComponent(sessionId),{cache:"no-store"});const x=await r.json().catch(()=>({}));if(r.ok&&x.ok&&!x.pending)return x;if(!r.ok&&r.status!==202)throw new Error(x.error||"Checkout status failed");await sleep(800)}throw new Error(getLang()==="en"?"Payment is still being processed. Please reload this page in a moment.":"Die Zahlung wird noch verarbeitet. Bitte lade die Seite in einem Moment neu.")}

  function bookingWaveFix(){if(!document.querySelector('.booking-wave'))return;const style=document.createElement('style');style.textContent='.booking-wave{background:#FFF7ED!important}.booking-wave+footer{background:#F8E7DE!important;border-top:0!important}';document.head.appendChild(style)}
  function injectPaymentStyles(){if(document.getElementById('bdPaymentStyles'))return;const s=document.createElement('style');s.id='bdPaymentStyles';s.textContent=`
    .bd-payment-box{margin-top:20px;border:1px solid #E8D2BE;border-radius:16px;padding:16px;background:#fff}.bd-payment-box h3{margin:0 0 10px;font-size:17px}.bd-payment-choice{display:grid;grid-template-columns:1fr 1fr;gap:10px}.bd-pay-option{display:flex;gap:9px;align-items:flex-start;border:1px solid #E8D2BE;border-radius:13px;padding:12px;background:#FFFDFC;cursor:pointer}.bd-pay-option:has(input:checked){border-color:#C96B4B;background:#FFF7ED}.bd-pay-option input{margin-top:3px;accent-color:#C96B4B}.bd-pay-option strong,.bd-pay-option span{display:block}.bd-pay-option span{font-size:11px;color:#75645C;margin-top:2px}.bd-billing{display:none;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.bd-billing.active{display:grid}.bd-billing label{font-size:11px;font-weight:800;color:#75645C}.bd-billing input{display:block;width:100%;margin-top:5px;border:1px solid #E8D2BE;border-radius:10px;padding:10px 11px;background:#fff}.bd-billing .full{grid-column:1/-1}.bd-pay-note{font-size:11px;color:#75645C;margin-top:10px;line-height:1.45}.bd-checkout-state{padding:28px;border:1px solid #E8D2BE;border-radius:20px;background:#fff;text-align:center;max-width:700px;margin:40px auto}.bd-checkout-state h2{font-family:Georgia,serif;font-size:30px}.bd-checkout-state p{color:#5F504A;line-height:1.6}.bd-checkout-state a{color:#A9543B;font-weight:800}.bd-price-row{padding:12px 0;border-bottom:1px solid rgba(255,255,255,.12)}.bd-price-row span{display:block;color:rgba(255,255,255,.62);font-size:12px;text-transform:uppercase;letter-spacing:.1em;margin-bottom:4px}.bd-price-row b{font-size:16px}@media(max-width:600px){.bd-payment-choice,.bd-billing{grid-template-columns:1fr}.bd-billing .full{grid-column:auto}}`;
    document.head.appendChild(s);
  }

  function cartFormBody(lang){
    const val=id=>String(document.getElementById(id)?.value||"").trim();
    return {lang,name:val("checkoutName"),email:val("checkoutEmail"),street:val("checkoutStreet"),postal:val("checkoutPostal"),city:val("checkoutCity"),country:val("checkoutCountry"),consents:{paidOrder:!!document.getElementById("consentOrder")?.checked,earlyService:!!document.getElementById("consentService")?.checked,immediateDigital:!!document.getElementById("consentDigital")?.checked},items:getCart().map(i=>({productId:i.id,advisorCode:i.advisorCode||"01"}))};
  }
  function cartValidate(body,lang){if(!body.name||!body.email||!body.street||!body.postal||!body.city||!body.country||!body.consents.paidOrder)return lang==="en"?"Please complete all required fields and confirm the binding order.":"Bitte fülle alle Pflichtfelder aus und bestätige die zahlungspflichtige Bestellung.";return""}
  async function setupCartCheckout(){
    const btn=document.getElementById('checkout'),box=document.querySelector('.checkout-box');if(!btn||!box)return;
    injectPaymentStyles();const lang=getLang(),cfg=await getPublicConfig();
    const html=`<div class="bd-payment-box" id="bdCartPayment"><h3>${lang==='en'?'Payment method':'Zahlungsart'}</h3><div class="bd-payment-choice"><label class="bd-pay-option"><input type="radio" name="bdCartPay" value="stripe" ${cfg.stripeEnabled?'checked':''} ${cfg.stripeEnabled?'':'disabled'}><span><strong>${lang==='en'?'Pay online':'Online bezahlen'}</strong><span>${lang==='en'?'Securely via Stripe · card / Apple Pay / Google Pay when available':'Sicher über Stripe · Karte / Apple Pay / Google Pay, wenn verfügbar'}</span></span></label><label class="bd-pay-option"><input type="radio" name="bdCartPay" value="invoice" ${cfg.stripeEnabled?'':'checked'}><span><strong>${lang==='en'?'Invoice / bank transfer':'Rechnung / Banküberweisung'}</strong><span>${lang==='en'?'PDF invoice · 14 days payment term':'PDF-Rechnung · 14 Tage Zahlungsziel'}</span></span></label></div><div class="bd-pay-note">${cfg.stripeEnabled?(lang==='en'?'Online payments are marked as paid automatically in the practice CRM.':'Online-Zahlungen werden im Praxis-CRM automatisch als bezahlt verbucht.'):(lang==='en'?'Stripe is not configured yet; invoice remains available.':'Stripe ist noch nicht konfiguriert; Rechnung bleibt verfügbar.')}</div></div>`;
    box.insertAdjacentHTML('beforeend',html);
    const updateButton=()=>{const method=document.querySelector('input[name="bdCartPay"]:checked')?.value||'invoice';const total=getCart().reduce((s,i)=>s+Number(i.price||0),0);btn.textContent=(method==='stripe'?(lang==='en'?'Pay securely online':'Sicher online bezahlen'):(lang==='en'?'Order on invoice':'Auf Rechnung bestellen'))+(getCart().length?' · '+new Intl.NumberFormat(lang==='en'?'en-IE':'de-AT',{style:'currency',currency:'EUR'}).format(total):'');const note=document.querySelector('.checkout-row + .note');if(note)note.textContent=method==='stripe'?(lang==='en'?'Secure online payment via Stripe · payment status is recorded automatically':'Sichere Online-Zahlung über Stripe · Zahlungsstatus wird automatisch verbucht'):(lang==='en'?'Invoice by bank transfer · 14 days payment term · payment QR on the PDF invoice':'Rechnung per Banküberweisung · 14 Tage Zahlungsziel · Zahlungs-QR auf der PDF-Rechnung')};
    document.querySelectorAll('input[name="bdCartPay"]').forEach(x=>x.addEventListener('change',updateButton));window.addEventListener('bd-cart-updated',()=>setTimeout(updateButton,0));updateButton();
    btn.onclick=async()=>{const body=cartFormBody(lang),msg=document.getElementById('checkoutMsg'),method=document.querySelector('input[name="bdCartPay"]:checked')?.value||'invoice',err=cartValidate(body,lang);if(err){msg.className='checkout-msg err';msg.textContent=err;return}btn.disabled=true;msg.className='checkout-msg';msg.textContent=method==='stripe'?(lang==='en'?'Opening secure payment …':'Sichere Zahlung wird geöffnet …'):(lang==='en'?'Creating access and invoice …':'Zugang und Rechnung werden erstellt …');try{const path=method==='stripe'?'/stripe/package-checkout':'/invoice-checkout';const r=await fetch(apiBase()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Checkout failed');if(method==='stripe'){location.href=x.url;return}window.BDCart.clear();try{sessionStorage.setItem('bd_package_customer',JSON.stringify({name:body.name,email:body.email}))}catch(e){}if(!x.emailSent)sessionStorage.setItem('bd_invoice_email_warning',lang==='en'?'Your access was created but the email could not be sent.':'Dein Zugang wurde erstellt, aber die E-Mail konnte nicht versendet werden.');location.href=(lang==='en'?'access.html?token=':'zugang.html?token=')+encodeURIComponent(x.accessToken)}catch(e){btn.disabled=false;msg.className='checkout-msg err';msg.textContent=e.message;updateButton()}};
  }

  function stripeReturnShell(title,text){const main=document.querySelector('main');if(!main)return;main.innerHTML=`<div class="bd-checkout-state"><h2>${esc(title)}</h2><p>${text}</p></div>`}
  async function handleStripeReturn(){const p=new URLSearchParams(location.search),status=p.get('stripe'),sessionId=p.get('session_id');if(!status)return false;injectPaymentStyles();const lang=getLang();if(status==='cancelled'){const el=document.getElementById('checkoutMsg')||document.getElementById('formMsg');if(el){el.className=(el.className||'')+' err';el.textContent=lang==='en'?'Payment was cancelled. Nothing was charged.':'Die Zahlung wurde abgebrochen. Es wurde nichts belastet.'}history.replaceState({},document.title,location.pathname);return false}if(status==='success'&&sessionId){stripeReturnShell(lang==='en'?'Payment received':'Zahlung erhalten',lang==='en'?'We are finalising your payment and access …':'Wir schließen Zahlung und Zugang gerade ab …');try{const x=await checkoutStatus(sessionId);if(x.kind==='package'){window.BDCart.clear();try{sessionStorage.setItem('bd_package_customer','{}')}catch(e){}const href=(lang==='en'?'access.html?token=':'zugang.html?token=')+encodeURIComponent(x.accessToken);stripeReturnShell(lang==='en'?'Payment successful':'Zahlung erfolgreich',`${lang==='en'?'Your package is paid and your invoice has been recorded automatically.':'Dein Package ist bezahlt und die Rechnung wurde automatisch als bezahlt verbucht.'}<br><br><a href="${href}">${lang==='en'?'Open my personal area →':'Zu meinem persönlichen Bereich →'}</a>`);setTimeout(()=>location.href=href,1600)}else if(x.kind==='booking'){const start=x.start?new Intl.DateTimeFormat(lang==='en'?'en-GB':'de-AT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Vienna'}).format(new Date(x.start)):'';const manage=x.manageToken?`<br><br><a href="termin.html?token=${encodeURIComponent(x.manageToken)}">${lang==='en'?'Manage appointment →':'Termin verwalten →'}</a>`:'';stripeReturnShell(lang==='en'?'Appointment paid & booked':'Termin bezahlt & gebucht',`${esc(start)}<br>${lang==='en'?'The payment and invoice were recorded automatically in the practice CRM.':'Zahlung und Rechnung wurden automatisch im Praxis-CRM verbucht.'}${manage}`)}return true}catch(e){stripeReturnShell(lang==='en'?'Payment received':'Zahlung erhalten',`${esc(e.message)}<br><br>${lang==='en'?'Please reload this page shortly.':'Bitte lade diese Seite in Kürze neu.'}`);return true}}return false}

  function bookingGlobals(){try{return {C:C,state:state,q:q,qa:qa,typeData:typeData,fmtLong:fmtLong,fmtTime:fmtTime,makeIcs:makeIcs,txt:txt,packageToken:typeof packageToken!=='undefined'?packageToken:'',L:typeof L!=='undefined'?L:getLang()}}catch(e){return null}}
  async function setupBookingPayments(){
    const form=document.getElementById('bookingForm'),submit=document.getElementById('submitBtn');if(!form||!submit)return;const g=bookingGlobals();if(!g||g.packageToken)return;injectPaymentStyles();const lang=getLang(),cfg=await getPublicConfig();
    const policy=form.querySelector('.booking-policy');if(!policy)return;
    policy.insertAdjacentHTML('afterend',`<div class="bd-payment-box"><h3>${lang==='en'?'Payment':'Zahlung'}</h3><div class="bd-payment-choice"><label class="bd-pay-option"><input type="radio" name="bdBookingPay" value="stripe" ${cfg.stripeEnabled?'checked':''} ${cfg.stripeEnabled?'':'disabled'}><span><strong>${lang==='en'?'Pay online':'Online bezahlen'}</strong><span>${lang==='en'?'Secure Stripe checkout':'Sicherer Stripe Checkout'}</span></span></label><label class="bd-pay-option"><input type="radio" name="bdBookingPay" value="invoice" ${cfg.stripeEnabled?'':'checked'}><span><strong>${lang==='en'?'Invoice':'Auf Rechnung'}</strong><span>${lang==='en'?'14 days payment term':'14 Tage Zahlungsziel'}</span></span></label></div><div class="bd-billing" id="bdBookingBilling"><label class="full">${lang==='en'?'Street & number':'Straße und Hausnummer'}<input id="bdBillStreet" autocomplete="street-address"></label><label>${lang==='en'?'Postcode':'PLZ'}<input id="bdBillPostal" autocomplete="postal-code"></label><label>${lang==='en'?'City':'Ort'}<input id="bdBillCity" autocomplete="address-level2"></label><label class="full">${lang==='en'?'Country':'Land'}<input id="bdBillCountry" value="${lang==='en'?'Austria':'Österreich'}" autocomplete="country-name"></label></div><div class="bd-pay-note" id="bdBookingPayNote"></div></div>`);
    const billing=document.getElementById('bdBookingBilling'),payNote=document.getElementById('bdBookingPayNote');
    const method=()=>document.querySelector('input[name="bdBookingPay"]:checked')?.value||'invoice';
    const fee=()=>Number(cfg.appointmentFees?.[g.state.type]||0);
    const ensurePriceRow=()=>{const summary=document.querySelector('.summary');if(!summary)return;let row=document.getElementById('bdBookingPrice');if(!row){row=document.createElement('div');row.id='bdBookingPrice';row.className='bd-price-row';const policy=summary.querySelector('.summary-policy');summary.insertBefore(row,policy||null)}const cents=fee();row.innerHTML=`<span>${lang==='en'?'Fee':'Honorar'}</span><b>${cents?moneyCents(cents,lang):(lang==='en'?'not configured':'noch nicht konfiguriert')}</b>`};
    const update=()=>{billing.classList.toggle('active',method()==='invoice');const cents=fee();payNote.textContent=!cents?(lang==='en'?'The appointment fee must still be configured in the Worker before paid booking can go live.':'Das Honorar muss im Worker noch konfiguriert werden, bevor die Zahlungsbuchung live gehen kann.'):(method()==='stripe'?(lang==='en'?'After successful payment the appointment, invoice and payment status are recorded automatically.':'Nach erfolgreicher Zahlung werden Termin, Rechnung und Zahlungsstatus automatisch verbucht.'):(lang==='en'?'You will receive a PDF invoice by email.':'Du erhältst die PDF-Rechnung per E-Mail.'));ensurePriceRow();submit.textContent=method()==='stripe'?(lang==='en'?'Continue to secure payment':'Weiter zur sicheren Zahlung'):(lang==='en'?'Book on invoice':'Auf Rechnung buchen')};
    document.querySelectorAll('input[name="bdBookingPay"]').forEach(x=>x.addEventListener('change',update));document.querySelectorAll('[data-type]').forEach(x=>x.addEventListener('click',()=>setTimeout(update,0)));update();
    form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const cents=fee();if(!cents){const fm=document.getElementById('formMsg');fm.className='notice err';fm.textContent=lang==='en'?'The fee is not configured yet. Please contact the practice.':'Das Honorar ist noch nicht konfiguriert. Bitte kontaktiere die Praxis.';return}const fd=new FormData(form),payload={lang,name:fd.get('name'),email:fd.get('email'),type:g.state.type,location:g.state.location,start:g.state.start,end:g.state.end};if(!payload.start){alert(lang==='en'?'Please choose an appointment first.':'Bitte zuerst einen Termin auswählen.');return}const m=method();if(m==='invoice'){payload.paymentMethod='invoice';payload.billing={street:String(document.getElementById('bdBillStreet')?.value||'').trim(),postal:String(document.getElementById('bdBillPostal')?.value||'').trim(),city:String(document.getElementById('bdBillCity')?.value||'').trim(),country:String(document.getElementById('bdBillCountry')?.value||'').trim()};if(!payload.billing.street||!payload.billing.postal||!payload.billing.city||!payload.billing.country){alert(lang==='en'?'Please complete the billing address.':'Bitte ergänze die Rechnungsadresse.');return}}
      submit.disabled=true;submit.textContent=lang==='en'?'Processing …':'Wird verarbeitet …';try{if(m==='stripe'){const r=await fetch(apiBase()+'/stripe/booking-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Checkout failed');location.href=x.url;return}const r=await fetch(apiBase()+'/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Booking failed');g.state.start=x.start||g.state.start;g.state.end=x.end||g.state.end;document.getElementById('step4').innerHTML=`<div class="done"><div class="tick">✓</div><h2>${lang==='en'?'Your appointment is booked.':'Dein Termin ist gebucht.'}</h2><p style="color:#5F504A;line-height:1.6">${g.fmtLong(g.state.date)} · ${g.fmtTime(g.state.start)}</p><p style="color:#5F504A">${lang==='en'?`Invoice ${esc(x.invoice?.invoiceNumber||'')} was created and sent by email.`:`Die Rechnung ${esc(x.invoice?.invoiceNumber||'')} wurde erstellt und per E-Mail versendet.`}</p>${x.manageToken?`<a class="ics" href="termin.html?token=${encodeURIComponent(x.manageToken)}">${lang==='en'?'Manage appointment →':'Termin verwalten →'}</a>`:''}</div>`;try{g.makeIcs(payload)}catch(err){}}
      catch(err){const fm=document.getElementById('formMsg');fm.className='notice err';fm.textContent=err.message;submit.disabled=false;update()}}
  }

  async function injectSingleSessionPrices(){
    // Offers pages already load cart.js. Keep displayed single-session prices in sync
    // with the Worker's public payment configuration.
    if(!document.querySelector('a[href*="booking.html?type="],a[href*="booking-en.html?type="]'))return;
    const cfg=await getPublicConfig(),lang=getLang();
    const entries=[['individual',Number(cfg.appointmentFees?.individual||9000)],['couple',Number(cfg.appointmentFees?.couple||16500)]];
    for(const [type,cents] of entries){
      const link=document.querySelector(`a[href*="booking${lang==='en'?'-en':''}.html?type=${type}"]`)||document.querySelector(`a[href*="?type=${type}"]`);
      const card=link?.closest('.card');if(!card||!cents)continue;
      if(card.querySelector(`[data-bd-session-price="${type}"]`))continue;
      const meta=card.querySelector('.meta');if(!meta)continue;
      const price=document.createElement('div');price.className='price';price.dataset.bdSessionPrice=type;price.textContent=(lang==='en'?'Fee ':'Honorar ')+moneyCents(cents,lang);meta.insertAdjacentElement('afterend',price);
    }
  }

  document.addEventListener("DOMContentLoaded",async()=>{updateBadges();bookingWaveFix();const handled=await handleStripeReturn();if(handled)return;await injectSingleSessionPrices();await setupCartCheckout();await setupBookingPayments()});
})();
