(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],API=(window.BD_BOOKING_CONFIG?.apiBaseUrl||'').replace(/\/$/,''),SESSION='bd_admin_session_v1';
let items=[],current=null,saveTimer=null,saving=false,lastSignature='';
const fields={title:$('#titleInput'),subtitle:$('#subtitleInput'),content:$('#contentEditor'),category:$('#categoryInput'),tags:$('#tagsInput'),author:$('#authorInput'),slug:$('#slugInput'),excerpt:$('#excerptInput'),visibleUntil:$('#visibleUntilInput'),seoTitle:$('#seoTitleInput'),seoDescription:$('#seoDescriptionInput'),sources:$('#sourcesInput'),links:$('#linksInput'),faq:$('#faqInput')};
function token(){return sessionStorage.getItem(SESSION)||''}
async function api(path,opt={}){const headers={...(opt.headers||{}),Authorization:'Bearer '+token()};if(opt.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(API+path,{...opt,headers,cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Anfrage fehlgeschlagen.');return x}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(v){return String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,96)}
function statusOf(item){if(item.status==='published'&&item.publishedAt&&new Date(item.publishedAt)>new Date())return'scheduled';return item.status}
function statusLabel(item){return({idea:'Idee',draft:'Entwurf',scheduled:'Geplant',published:'Veröffentlicht',archived:'Archiviert'})[statusOf(item)]||item.status}
function localValue(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function isoValue(value){return value?new Date(value).toISOString():null}
function linesToObjects(value,type='link'){return String(value||'').split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [left,...right]=line.split('|');return type==='faq'?{question:left.trim(),answer:right.join('|').trim()}:{label:left.trim(),url:right.join('|').trim()}}).filter(x=>type==='faq'?(x.question&&x.answer):(x.label||x.url))}
function objectsToLines(value,type='link'){return(value||[]).map(x=>type==='faq'?`${x.question} | ${x.answer}`:`${x.label||''}${x.url?' | '+x.url:''}`).join('\n')}
function showToast(message){const t=$('#toast');t.textContent=message;t.hidden=false;clearTimeout(t._timer);t._timer=setTimeout(()=>t.hidden=true,2600)}
function actionMessage(message,error=false){const node=$('#hubActionMessage');if(!node)return;node.textContent=message;node.classList.toggle('error',error)}
function saveState(text,error=false){const node=$('#saveState');node.textContent=text;node.style.color=error?'#a6382f':''}
function collect(){if(!current)return null;return{id:current.id,itemType:current.itemType,title:fields.title.value.trim(),subtitle:fields.subtitle.value.trim(),contentHtml:fields.content.innerHTML,category:fields.category.value.trim(),tags:fields.tags.value.split(',').map(x=>x.trim()).filter(Boolean),author:fields.author.value.trim(),slug:fields.slug.value.trim(),excerpt:fields.excerpt.value.trim(),visibleUntil:isoValue(fields.visibleUntil.value),seoTitle:fields.seoTitle.value.trim(),seoDescription:fields.seoDescription.value.trim(),sources:linesToObjects(fields.sources.value),internalLinks:linesToObjects(fields.links.value),faq:linesToObjects(fields.faq.value,'faq')};}
function signature(data){return JSON.stringify(data)}
async function save(force=false){if(!current||saving)return current;const data=collect(),sig=signature(data);if(!force&&sig===lastSignature)return current;saving=true;saveState('Speichert …');try{const x=await api('/admin/knowledge/save',{method:'POST',body:JSON.stringify(data)});current=x.item;const i=items.findIndex(v=>v.id===current.id);if(i>=0)items[i]=current;else items.unshift(current);lastSignature=signature(collect());saveState('Automatisch gespeichert');renderList();renderPlan();updateHeader();return current}catch(e){saveState('Speichern fehlgeschlagen',true);showToast(e.message);throw e}finally{saving=false}}
function scheduleSave(){saveState('Änderungen …');clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(()=>{}),900);updateSeoPreview()}
function filteredItems(){const q=$('#searchInput').value.trim().toLowerCase(),filter=$('#statusFilter').value;return items.filter(item=>(filter==='all'||statusOf(item)===filter)&&(!q||[item.title,item.subtitle,item.excerpt,item.category,(item.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)))}
function renderList(){const list=$('#itemList'),visible=filteredItems();list.innerHTML=visible.length?visible.map(item=>`<button class="item-card ${current?.id===item.id?'active':''}" data-id="${item.id}" type="button"><small><span class="status-dot ${statusOf(item)}"></span>${statusLabel(item)}${item.category?' · '+esc(item.category):''}</small><strong>${esc(item.title||'Unbenannte Idee')}</strong><small>${esc(item.excerpt||item.subtitle||'Noch ohne Beschreibung')}</small></button>`).join(''):'<p class="empty">Keine passenden Inhalte.</p>';list.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openItem(Number(b.dataset.id)))}
function renderPlan(){const rows=[...items].filter(x=>x.status==='published'||x.status==='draft').sort((a,b)=>new Date(a.publishedAt||a.updatedAt)-new Date(b.publishedAt||b.updatedAt));$('#editorialPlan').innerHTML=rows.length?rows.map(item=>`<button class="plan-row ${statusOf(item)}" data-plan-id="${item.id}" type="button"><small>${esc(item.publishedAt?new Date(item.publishedAt).toLocaleString('de-AT',{dateStyle:'medium',timeStyle:'short'}):'Noch ohne Termin')}</small><strong>${esc(item.title||'Unbenannter Entwurf')}</strong><small>${statusLabel(item)}</small></button>`).join(''):'<p class="empty">Noch keine Artikel im Plan.</p>';$$('[data-plan-id]').forEach(b=>b.onclick=()=>openItem(Number(b.dataset.planId)))}
function updateHeader(){if(!current)return;const state=statusOf(current);$('#itemBadge').textContent=statusLabel(current);$('#statusDisplay').value=statusLabel(current);$('#updatedLabel').textContent=current.updatedAt?'zuletzt '+new Date(current.updatedAt).toLocaleString('de-AT'):'';$('#articleAction').hidden=current.itemType==='article';$('#publishBtn').textContent=$('#publishMode').value==='scheduled'?'Veröffentlichung planen':'Veröffentlichen';$('#unpublishBtn').hidden=current.status!=='published';$('#archiveBtn').textContent=current.status==='archived'?'Wiederherstellen':'Archivieren';$('#publishBtn').hidden=current.status==='archived';updateSeoPreview()}
function openItem(id){clearTimeout(saveTimer);const item=items.find(x=>x.id===id);if(!item)return;current=item;$('#emptyEditor').hidden=true;$('#editorForm').hidden=false;$('#metaPanel').hidden=false;fields.title.value=item.title||'';fields.subtitle.value=item.subtitle||'';fields.content.innerHTML=item.contentHtml||'';fields.category.value=item.category||'';fields.tags.value=(item.tags||[]).join(', ');fields.author.value=item.author||'Theophil Kroller';fields.slug.value=item.slug||'';fields.excerpt.value=item.excerpt||'';fields.visibleUntil.value=localValue(item.visibleUntil);fields.seoTitle.value=item.seoTitle||'';fields.seoDescription.value=item.seoDescription||'';fields.sources.value=objectsToLines(item.sources);fields.links.value=objectsToLines(item.internalLinks);fields.faq.value=objectsToLines(item.faq,'faq');if(item.publishedAt&&new Date(item.publishedAt)>new Date()){$('#publishMode').value='scheduled';$('#publishDateInput').value=localValue(item.publishedAt);$('#publishDateWrap').hidden=false}else{$('#publishMode').value='now';$('#publishDateWrap').hidden=true}lastSignature=signature(collect());renderList();updateHeader();window.scrollTo({top:0,behavior:'smooth'})}
async function createItem(type='article',text=''){const title=text.trim().slice(0,120);const data={itemType:type,status:type==='idea'?'idea':'draft',title,excerpt:text.trim(),contentHtml:text?`<p>${esc(text)}</p>`:'',author:'Theophil Kroller'};saveState('Legt an …');actionMessage(type==='idea'?'Idee wird gespeichert …':'Artikelentwurf wird angelegt …');try{const x=await api('/admin/knowledge/save',{method:'POST',body:JSON.stringify(data)});items.unshift(x.item);$('#quickIdea').value='';renderPlan();openItem(x.item.id);const message=type==='idea'?'Idee wurde gespeichert.':'Artikelentwurf wurde angelegt.';actionMessage(message);showToast(message)}catch(e){actionMessage(e.message,true);showToast(e.message);saveState('Fehler',true)}}
async function action(name,extra={}){if(!current)return;await save(true);if(name==='delete'&&!confirm('Diesen Inhalt wirklich endgültig löschen?'))return;if(name==='archive'&&current.status!=='archived'&&!confirm('Diesen Inhalt archivieren?'))return;try{const x=await api('/admin/knowledge/action',{method:'POST',body:JSON.stringify({id:current.id,action:name,...extra})});if(x.deleted){items=items.filter(v=>v.id!==current.id);current=null;$('#editorForm').hidden=true;$('#metaPanel').hidden=true;$('#emptyEditor').hidden=false;renderList();renderPlan();showToast('Inhalt gelöscht.');return}current=x.item;const i=items.findIndex(v=>v.id===current.id);items[i]=current;openItem(current.id);showToast(name==='publish'?(statusOf(current)==='scheduled'?'Veröffentlichung ist geplant.':'Artikel ist veröffentlicht.'):'Änderung übernommen.')}catch(e){showToast(e.message)}}
function updateSeoPreview(){if(!current)return;$('#seoPreviewTitle').textContent=fields.seoTitle.value||fields.title.value||'Artikeltitel';$('#seoPreviewUrl').textContent='beziehungsdynamiken.at/wissen/'+(fields.slug.value||slug(fields.title.value)||'…');$('#seoPreviewDescription').textContent=fields.seoDescription.value||fields.excerpt.value||'Beschreibung des Artikels'}
function preview(){if(!current)return;const dlg=$('#previewDialog');$('#previewContent').innerHTML=`<h1>${esc(fields.title.value||'Unbenannter Artikel')}</h1>${fields.subtitle.value?`<p class="muted">${esc(fields.subtitle.value)}</p>`:''}<div>${fields.content.innerHTML}</div>`;dlg.showModal()}
async function load(){if(!token()){$('#authNotice').hidden=false;$('#captureIdea').disabled=true;$('#newArticle').disabled=true;actionMessage('Bitte zuerst im Praxis-CRM anmelden und den Hub über die schwarze Kopfleiste öffnen.',true);saveState('CRM-Anmeldung fehlt',true);return}try{const x=await api('/admin/knowledge/items');items=x.items||[];renderList();renderPlan();actionMessage('Mit dem Praxis-CRM verbunden.');saveState('Bereit')}catch(e){if(/Sitzung|session|Anmeld/i.test(e.message))$('#authNotice').hidden=false;$('#itemList').innerHTML=`<p class="empty">${esc(e.message)}</p>`;actionMessage(e.message,true);saveState('Nicht verbunden',true)}}
$('#captureIdea').onclick=()=>{const value=$('#quickIdea').value.trim();if(value)createItem('idea',value);else actionMessage('Bitte zuerst eine Idee eingeben.',true)};$('#newArticle').onclick=()=>createItem('article');$('#searchInput').oninput=renderList;$('#statusFilter').onchange=renderList;
Object.values(fields).forEach(node=>node.addEventListener('input',()=>{if(node===fields.title&&!fields.slug.value)fields.slug.value=slug(fields.title.value);scheduleSave()}));
$$('.toolbar button').forEach(button=>button.onclick=()=>{const command=button.dataset.command,value=button.dataset.value||null;if(command==='createLink'){const url=prompt('Zieladresse des Links (https://… oder /wissen/…):');if(!url)return;document.execCommand(command,false,url)}else document.execCommand(command,false,value);fields.content.focus();scheduleSave()});
fields.content.addEventListener('paste',event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'))});
$('#previewBtn').onclick=preview;$('#closePreview').onclick=()=>$('#previewDialog').close();$('#articleAction').onclick=()=>action('article');
$('#publishMode').onchange=()=>{$('#publishDateWrap').hidden=$('#publishMode').value!=='scheduled';updateHeader()};$('#publishBtn').onclick=()=>{let publishedAt=null;if($('#publishMode').value==='scheduled'){if(!$('#publishDateInput').value){showToast('Bitte Veröffentlichungsdatum wählen.');return}publishedAt=isoValue($('#publishDateInput').value)}action('publish',{publishedAt})};$('#unpublishBtn').onclick=()=>action('unpublish');$('#archiveBtn').onclick=()=>action(current?.status==='archived'?'restore':'archive');$('#deleteBtn').onclick=()=>action('delete');
$$('[data-meta-tab]').forEach(button=>button.onclick=()=>{$$('[data-meta-tab]').forEach(x=>x.classList.toggle('active',x===button));$$('[data-meta-panel]').forEach(x=>x.hidden=x.dataset.metaPanel!==button.dataset.metaTab)});
window.addEventListener('beforeunload',event=>{if(current&&signature(collect())!==lastSignature){event.preventDefault();event.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&current)save().catch(()=>{})});
load();
})();
