import {validateLeaders} from './workshop-leaders-core.mjs?v=14.15.6';
import {imagePresets,defaultImage,isPresetUrl} from './landingpage-images.mjs?v=14.15.5';
export {imagePresets,defaultImage};
import {brandVoice,offerReference} from './brand-voice.mjs?v=14.15.4';
export const fields={title:'Hero · Titel',subtitle:'Hero · Untertitel',recognition:'Kommt dir das bekannt vor?',change:'Was sich verändern kann',about:'Darum geht es',benefits:'Was du mitnehmen kannst',agenda:'Was dich erwartet',audience:'Für wen ist das?',facilitators:'Wer dich begleitet',faq:'Häufige Fragen',cta:'Buttontext',image_url:'Hero-Bild · URL (optional)',image_alt:'Bildbeschreibung',hero_image_brief:'Bildidee für die spätere Auswahl',newsletter_url:'Newsletter-Anmeldeseite (optional)',newsletter_text:'Newsletter-Hinweis',seo_description:'Beschreibung für Suchmaschinen'};
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validate(raw,id){if(!raw||raw.schema_version!==1||raw.workshop_id!==id||!raw.copy||typeof raw.copy!=='object'||Array.isArray(raw.copy))throw Error('Schema-Version oder Workshop-Kennung stimmt nicht. Bitte den Export dieses Workshops verwenden.');const copy={};for(const k of Object.keys(fields)){const v=raw.copy[k]??'';if(typeof v!=='string'||v.length>12000)throw Error('Ungültiges Textfeld: '+k);copy[k]=v.trim()}for(const k of ['image_url','newsletter_url'])if(copy[k]&&!(k==='image_url'&&isPresetUrl(copy[k]))&&!/^https:\/\/[^\s<>]+$/i.test(copy[k]))throw Error('Bitte eine vollständige HTTPS-Adresse für '+fields[k]+' verwenden.');return {schema_version:1,workshop_id:id,copy,leaders:validateLeaders(raw.leaders||[])}}
export function initial(w){return {schema_version:1,workshop_id:w.workshop_id,copy:Object.fromEntries(Object.keys(fields).map(k=>[k,k==='title'?w.title:k==='subtitle'?w.description:k==='audience'?w.target_group:k==='facilitators'?w.facilitators:k==='cta'?'Platz ansehen':k==='image_url'?defaultImage.url:k==='image_alt'?defaultImage.alt:k==='newsletter_text'?'Diesmal passt es nicht? Erfahre, wenn neue Workshops und Artikel erscheinen.':'']))}}
export function context(w,methods=[],program=null){return {schema_version:1,workshop_id:w.workshop_id,brand:{name:'Beziehungsdynamiken',scope:'Romantische, familiäre und berufliche Beziehungen; aktuell Schwerpunkt Paardynamik'},workshop:{title:w.title,description:w.description,topic:w.topic,target_group:w.target_group,date:w.date,start_time:w.start_time,duration_minutes:w.target_duration,location:w.location,facilitators:w.facilitators,capacity:w.participant_count,modules:w.blocks.map(b=>({title:b.title,type:b.block_type,duration_minutes:b.duration_minutes,purpose:methods.find(m=>m.method_id===b.method_id)?.fields?.purpose||''}))},booking:program?{title:program.title,location:program.locationLabel,sessions:program.sessions,capacity:program.maxCapacity,facilitators:program.staff,price_tiers:(program.priceTiers||[]).map(t=>({label:t.label,amount_cents:t.amountCents,starts_at:t.startsAt,ends_at:t.endsAt,quantity_limit:t.quantityLimit,seats_per_purchase:t.seatsPerPurchase,is_active:t.isActive}))}:null,output_template:initial(w)}}
export function prompt(w){return `Erstelle eine deutschsprachige Workshop-Salespage für Beziehungsdynamiken aus workshop_context.json. Gib ausschließlich JSON zurück, exakt nach output_template: schema_version 1, unveränderte workshop_id, copy mit den vorgegebenen Schlüsseln und ausschließlich Strings. Alle Textfelder dürfen bearbeitet werden. Verwende keine weiteren Felder.\nSchreibe konkret, emotional und lebensnah, mit klarer Einladung zur Buchung. Zeige Alltagssituationen und nachvollziehbaren Nutzen: Sell the sizzle, not the steak. Verrate keine Übungsanleitungen oder internen Methoden. Keine Heilungsversprechen, erfundenen Testimonials, Qualifikationen, Preise, Termine oder künstliche Verknappung. Fehlendes bleibt leer. Agenda beschreibt öffentlich geeignete Phasen, keine detaillierten Interventionen. FAQ als Frage/Antwort-Absätze. recognition und benefits als Zeilen mit jeweils einer Situation/einem Nutzen.\nTon: warm, direkt, menschlich, manchmal kantig. Kein generisches Coaching-Vokabular, keine rhetorischen Dreierserien, kein „Nicht X, sondern Y“. Überarbeite am Ende Rhythmus und Natürlichkeit. Die Marke kann auch Familien- und Arbeitsbeziehungen behandeln. hero_image_brief darf eine Bildidee enthalten; image_url und newsletter_url bleiben leer, sofern nicht bereitgestellt. Preise, Kapazität und Termine werden später verbindlich aus der Buchung geladen.\nWorkshop-Kennung: ${w.workshop_id}

${brandVoice}

${offerReference}

ANWENDUNG AUF DIE LANDINGPAGE
Die Referenzen zeigen ausschließlich den Schreibstil. Übernimm daraus keine biografischen Fakten, Beratungsleistungen oder Versprechen für diesen Workshop. Formuliere die vorgegebenen Landingpage-Felder in dieser Stimme. Behalte eine klare Einladung zur Buchung. Alltagsszenen vor abstrakten Begriffen. Keine Slogans wie „Raus aus X. Rein in Y.“; vermeide wiederholtes „Raum für“, „bewusst begegnen“ und „gemeinsamer Prozess“. Teilnahmebedingungen, Vorerfahrung, Vorbereitung und Vertraulichkeit nur nennen, wenn in den Workshop-Daten belegt. Fehlende Fakten leer lassen. Nach der abschließenden Sprachüberarbeitung weiterhin ausschließlich das vorgegebene JSON ausgeben.`}
export function render(copy,p={},preview=false,leaders=[]){copy={...copy,image_url:copy.image_url||defaultImage.url,image_alt:copy.image_alt||(imagePresets.find(p=>p.url===(copy.image_url||defaultImage.url))?.alt||'')};const para=s=>esc(s).replace(/\n/g,'<br>'),section=(title,key)=>copy[key]?`<section><h2>${title}</h2><p>${para(copy[key])}</p></section>`:'',dt=s=>s?new Intl.DateTimeFormat('de-AT',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Vienna'}).format(new Date(s)):'',money=c=>new Intl.NumberFormat('de-AT',{style:'currency',currency:'EUR'}).format(c/100);let booking=preview?'#rahmen':'angebote.html?program='+encodeURIComponent(p.slug||'')+'#gruppen';return `<header><a href="index.html">Beziehungsdynamiken</a><span>WORKSHOP · GEMEINSAM WEITERKOMMEN</span></header><main><div class="hero"><div><small>${esc(p.locationLabel||'Workshop')}</small><h1>${esc(copy.title)}</h1><p class="lead">${para(copy.subtitle)}</p><p>${esc(p.sessions?.[0]?.startsAt?dt(p.sessions[0].startsAt):'Termin siehe Rahmen')}</p><a class="cta" href="${booking}">${esc(p.soldOut?'Auf Warteliste eintragen':copy.cta||'Platz ansehen')}</a></div>${copy.image_url?`<img src="${esc(copy.image_url)}" alt="${esc(copy.image_alt)}">`:''}</div>${section('Kommt dir das bekannt vor?','recognition')}${section('Was sich verändern kann','change')}${section('Darum geht es','about')}${section('Was du mitnehmen kannst','benefits')}${section('Was dich erwartet','agenda')}${section('Für wen ist das?','audience')}${leaders.length?`<section><h2>Wer dich begleitet</h2><div class="lp-leader-grid">${validateLeaders(leaders).map(l=>`<article class="lp-leader-card">${l.photo_url?`<img src="${esc(l.photo_url)}" alt="${esc(l.name)}" loading="lazy">`:''}<div><h3>${esc(l.name)}</h3><small>${esc(l.role)}</small><p>${para(l.bio)}</p></div></article>`).join('')}</div></section>`:section('Wer dich begleitet','facilitators')}<section id="rahmen" class="frame"><h2>Termin & Rahmen</h2><p>${esc(p.locationLabel||'Ort noch offen')}</p>${(p.sessions||[]).map(s=>`<p>${esc(dt(s.startsAt))}${s.endsAt?' – '+esc(dt(s.endsAt)):''}</p>`).join('')}<p>${p.maxCapacity?esc(p.maxCapacity)+' Plätze insgesamt':''} ${p.spotsAvailable!==undefined?' · '+esc(p.spotsAvailable)+' aktuell frei':''}</p>${p.currentTier?`<h3>${esc(p.currentTier.label)} · ${money(p.currentTier.amountCents)}</h3>`:'<p>Preis wird im Angebot konfiguriert.</p>'}<a class="cta" href="${booking}">${esc(p.soldOut?'Auf Warteliste eintragen':copy.cta||'Platz ansehen')}</a><p><small>Aktuelle Preise, Verfügbarkeit und Anmeldebedingungen findest du bei der Buchung.</small></p></section>${section('Häufige Fragen','faq')}${copy.newsletter_url?`<section><p>${para(copy.newsletter_text)}</p><a href="${esc(copy.newsletter_url)}">Über Neues informiert werden →</a></section>`:''}</main><footer><a href="index.html">Mehr über Beziehungsdynamiken</a> · <a href="impressum.html">Impressum</a> · <a href="datenschutz.html">Datenschutz</a></footer>`}
export function chatgptText(w,methods=[],program=null){return prompt(w)+'\n\nWORKSHOP-DATEN (workshop_context.json):\n'+JSON.stringify(context(w,methods,program),null,2)}
export function parseReply(text,id){const value=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');if(!value)throw Error('Bitte die Antwort aus ChatGPT einfügen.');if(value.length>250000)throw Error('Die Antwort darf höchstens 250 KB groß sein.');let raw;try{raw=JSON.parse(value)}catch(e){throw Error('Die Antwort enthält kein gültiges JSON. Bitte die vollständige JSON-Antwort kopieren.');}return validate(raw,id)}
