import {defaultLeader,snapshot,validateLeaders} from './workshop-leaders-core.mjs?v=14.15.6';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const token=sessionStorage.getItem('bd_admin_session_v1');if(!token)throw Error('Bitte zuerst im Praxis-Dashboard anmelden.');const r=await fetch(window.BD_BOOKING_CONFIG.apiBaseUrl.replace(/\/$/,'')+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'}),x=await r.json();if(!r.ok||x.ok===false)throw Error(x.error||'Anfrage fehlgeschlagen. Prüfe Worker und Migration 14.15.6.');return x}
async function profiles(){return (await api('/admin/workshop-leaders')).profiles}
async function upload(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5000000)throw Error('Bitte JPG, PNG oder WebP bis 5 MB wählen.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Bild konnte nicht gelesen werden.'));reader.readAsDataURL(file)});const x=await api('/admin/program-media/upload',{filename:file.name,contentType:file.type,dataBase64:data,altText:''});if(!x.asset?.url)throw Error('Bildadresse fehlt.');return x.asset.url}
export async function manage(){let rows=[];const d=document.createElement('dialog');d.className='wl-dialog';d.innerHTML=`<header><div><small>WORKSHOP STUDIO</small><h2>Workshop-Leiterprofile</h2></div><button data-close>Schließen</button></header><p>Foto und Kurztext einmal hinterlegen, danach bei Workshops auswählen. Die Profile sind unabhängig von Benutzerkonten und Abrechnung.</p><p role="status" data-status></p><div class="wl-manager"><aside><div data-list></div><button data-new>+ Neues Profil</button></aside><form><label>Name<input name="name" maxlength="200" required></label><label>Rolle / Berufsbezeichnung<input name="role" maxlength="200"></label><label>Kurztext<textarea name="bio" rows="6" maxlength="4000"></textarea></label><img data-photo class="wl-photo" alt="Profilfoto" hidden><label>Foto-Adresse<input name="photo_url" maxlength="2000" placeholder="https://…"></label><label>Eigenes Foto hochladen<input data-upload type="file" accept="image/jpeg,image/png,image/webp"></label><small>JPG, PNG oder WebP bis 5 MB. Uploads werden öffentlich gespeichert.</small><label><input name="active" type="checkbox"> Zur Auswahl anbieten</label><button class="primary" type="submit">Profil speichern</button></form></div><p>Bereits veröffentlichte Workshops behalten ihren bisherigen Profiltext. Im jeweiligen Workshop kannst du das Profil gezielt aktualisieren und erneut veröffentlichen.</p>`;document.body.append(d);d.showModal();const form=d.querySelector('form'),status=d.querySelector('[data-status]');let id='',busy=false;
const showPhoto=()=>{const img=d.querySelector('[data-photo]');img.src=form.elements.photo_url.value;img.hidden=!form.elements.photo_url.value};
function fill(p){id=p.id;for(const k of ['name','role','bio','photo_url'])form.elements[k].value=p[k]||'';form.elements.active.checked=p.active!==false;showPhoto()}
function list(){const e=d.querySelector('[data-list]');e.innerHTML=rows.map(p=>`<button type="button" data-id="${esc(p.id)}">${esc(p.name)}${p.active?'':' · archiviert'}</button>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>fill(rows.find(p=>p.id===b.dataset.id)))}
async function reload(){rows=await profiles();list()}
const lock=v=>{busy=v;d.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=v)};
d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.querySelector('[data-new]').onclick=()=>fill({id:crypto.randomUUID(),active:true});form.elements.photo_url.oninput=showPhoto;
d.querySelector('[data-upload]').onchange=async e=>{const file=e.target.files[0];if(!file||busy)return;lock(true);status.textContent='Foto wird hochgeladen …';try{form.elements.photo_url.value=await upload(file);showPhoto();status.textContent='Foto hochgeladen. Jetzt das Profil speichern.'}catch(err){status.textContent=err.message}finally{lock(false);e.target.value=''}};
form.onsubmit=async e=>{e.preventDefault();if(busy)return;lock(true);try{const p={id,active:form.elements.active.checked};for(const k of ['name','role','bio','photo_url'])p[k]=form.elements[k].value;snapshot(p);await api('/admin/workshop-leaders/save',p);await reload();fill(p);status.textContent='✓ Profil gespeichert.';document.dispatchEvent(new Event('bd:workshop-leaders-updated'))}catch(err){status.textContent=err.message}finally{lock(false)}};
try{await reload();fill(rows.find(p=>p.id===defaultLeader.id)||rows[0]||{id:crypto.randomUUID(),active:true})}catch(e){status.textContent=e.message;fill({...defaultLeader});form.querySelector('button[type=submit]').disabled=true}
}
export async function mountSelection(host,getSelected,onChange,options={}){let rows=[],loaded=false;host.innerHTML='<p role="status">Leiterprofile werden geladen …</p>';function draw(){const selected=validateLeaders(getSelected()||[]);host.innerHTML=`<div class="wl-add"><select aria-label="Leiterprofil auswählen"><option value="">Person auswählen …</option>${rows.filter(p=>p.active&&!selected.some(x=>x.id===p.id)).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><button data-add>Hinzufügen</button><button data-manage>Profile verwalten</button></div><div class="wl-selected">${selected.map(p=>`<article data-id="${esc(p.id)}">${p.photo_url?`<img class="wl-photo" src="${esc(p.photo_url)}" alt="${esc(p.name)}">`:''}<h3>${esc(p.name)}</h3><label>Rolle in diesem Workshop<input data-role value="${esc(p.role)}" maxlength="200"></label><label>Kurztext für diesen Workshop<textarea data-bio rows="4" maxlength="4000">${esc(p.bio)}</textarea></label><button data-update>Aus Profil aktualisieren</button><button data-remove>Entfernen</button></article>`).join('')}</div><p class="lp-image-note">Workshop-Texte sind eigene Kopien. Änderungen hier verändern das gespeicherte Profil nicht.</p>`;
const commit=next=>{onChange(next);draw()};host.querySelector('[data-add]').onclick=()=>{const p=rows.find(p=>p.id===host.querySelector('select').value);if(p)commit([...selected,snapshot(p)])};host.querySelector('[data-manage]').onclick=manage;host.querySelectorAll('article').forEach(a=>{const p=selected.find(x=>x.id===a.dataset.id);a.querySelector('[data-role]').oninput=e=>{p.role=e.target.value;onChange(selected)};a.querySelector('[data-bio]').oninput=e=>{p.bio=e.target.value;onChange(selected)};a.querySelector('[data-remove]').onclick=()=>commit(selected.filter(x=>x.id!==p.id));a.querySelector('[data-update]').onclick=()=>{const fresh=rows.find(x=>x.id===p.id);if(fresh)commit(selected.map(x=>x.id===p.id?snapshot(fresh):x));else alert('Dieses Profil ist nicht mehr verfügbar.')}})}
async function refresh(){try{rows=await profiles();loaded=true;draw()}catch(e){host.innerHTML='<p role="status">'+esc(e.message)+'</p><button data-retry>Erneut laden</button>';host.querySelector('button').onclick=refresh}}
host._wlAbort?.abort();host._wlAbort=new AbortController();await refresh();if(options.defaultId&&loaded){const p=rows.find(p=>p.id===options.defaultId&&p.active);onChange(p?[snapshot(p)]:[]);draw()}const listener=()=>{if(host.isConnected)refresh();else document.removeEventListener('bd:workshop-leaders-updated',listener)};document.addEventListener('bd:workshop-leaders-updated',listener,{signal:host._wlAbort.signal});return {refresh,draw,profiles:()=>rows};}
