(()=>{'use strict';
const $=s=>document.querySelector(s),API=(window.BD_BOOKING_CONFIG?.apiBaseUrl||'').replace(/\/$/,''),params=new URLSearchParams(location.search),slug=params.get('slug');let items=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(value){const url=String(value||'').trim();if(url.startsWith('/')&&!url.startsWith('//'))return url;try{const parsed=new URL(url);return['https:','mailto:'].includes(parsed.protocol)?url:''}catch(_){return''}}
function safeHtml(value){const doc=new DOMParser().parseFromString(`<div>${value||''}</div>`,'text/html'),allowed=new Set(['P','BR','H2','H3','H4','STRONG','EM','B','I','UL','OL','LI','BLOCKQUOTE','A','HR']);[...doc.body.querySelectorAll('*')].forEach(node=>{if(node.tagName==='DIV'&&node.parentElement===doc.body)return;if(!allowed.has(node.tagName)){node.replaceWith(...node.childNodes);return}const href=node.tagName==='A'?safeUrl(node.getAttribute('href')):'';[...node.attributes].forEach(attr=>node.removeAttribute(attr.name));if(node.tagName==='A'&&href){node.setAttribute('href',href);node.setAttribute('rel','noopener noreferrer')}});return doc.body.firstElementChild?.innerHTML||''}
function date(value){return value?new Intl.DateTimeFormat('de-AT',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(value)):''}
function error(message){$('#knowledgeIndex').hidden=true;$('#knowledgeArticle').hidden=true;const box=$('#knowledgeError');box.hidden=false;box.innerHTML=`<h2>Diese Seite konnte nicht geladen werden.</h2><p>${esc(message)}</p><p><a href="./">Zur Artikelübersicht</a></p>`}
async function get(path){const pv=params.get('bd_preview'),u=new URL(API+path);if(pv)u.searchParams.set('bd_preview',pv);const r=await fetch(u.toString(),{cache:'no-store'}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Bitte versuche es später erneut.');return x}
function renderCards(category='Alle'){const visible=category==='Alle'?items:items.filter(x=>(x.category||'Weitere Themen')===category);$('#articleGrid').innerHTML=visible.length?visible.map(item=>`<a class="article-card" href="./?slug=${encodeURIComponent(item.slug)}"><span class="eyebrow">${esc(item.category||'Wissen')}</span><h2>${esc(item.title)}</h2><p>${esc(item.excerpt||item.subtitle||'')}</p><span class="meta">${esc(item.author||'Theophil Kroller')} · ${esc(date(item.publishedAt))}</span></a>`).join(''):'<div class="loading">In dieser Kategorie sind noch keine Artikel veröffentlicht.</div>'}
async function renderIndex(){const x=await get('/knowledge/public');items=x.items||[];const categories=['Alle',...new Set(items.map(x=>x.category||'Weitere Themen'))];$('#categoryFilters').innerHTML=categories.map((name,index)=>`<button class="${index===0?'active':''}" type="button" data-category="${esc(name)}">${esc(name)}</button>`).join('');$('#categoryFilters').querySelectorAll('button').forEach(button=>button.onclick=()=>{$('#categoryFilters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));renderCards(button.dataset.category)});renderCards()}
function updateMeta(item){document.title=`${item.seoTitle||item.title} · Beziehungsdynamiken`;const description=item.seoDescription||item.excerpt||'';document.querySelector('meta[name="description"]').setAttribute('content',description);const canonical=`https://www.beziehungsdynamiken.at/wissen/?slug=${encodeURIComponent(item.slug)}`;document.querySelector('link[rel="canonical"]').setAttribute('href',canonical);const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:item.seoTitle||item.title,description,author:{'@type':'Person',name:item.author||'Theophil Kroller'},datePublished:item.publishedAt,dateModified:item.updatedAt,mainEntityOfPage:canonical});document.head.appendChild(script)}
async function renderArticle(){const x=await get('/knowledge/article?slug='+encodeURIComponent(slug)),item=x.item;$('#knowledgeIndex').hidden=true;$('#knowledgeArticle').hidden=false;$('#articleCategory').textContent=item.category||'Wissen';$('#articleTitle').textContent=item.title;$('#articleSubtitle').textContent=item.subtitle||'';$('#articleSubtitle').hidden=!item.subtitle;$('#articleMeta').textContent=`${item.author||'Theophil Kroller'} · ${date(item.publishedAt)}`;$('#articleBody').innerHTML=safeHtml(item.contentHtml);const generic=new Set(['book','web','own','other','workshop','conversation','training','youtube','reddit','quelle','source','buch']);const seen=new Set(),sources=(item.sources||[]).map(x=>{const url=safeUrl(x.url||''),raw=String(x.label||'').trim(),label=generic.has(raw.toLowerCase())?(url?new URL(url,location.href).hostname.replace(/^www\./,''):''):raw||url;return{label,url}}).filter(x=>{const key=(x.url||x.label).toLowerCase();if(!x.label||seen.has(key))return false;seen.add(key);return true}),sourceBox=$('#articleSources');sourceBox.hidden=!sources.length;if(sources.length)sourceBox.querySelector('ul').innerHTML=sources.map(x=>`<li>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.label)}</a>`:esc(x.label)}</li>`).join('');const faq=(item.faq||[]).filter(x=>x.question&&x.answer),faqBox=$('#articleFaq');if(faq.length){faqBox.hidden=false;faqBox.querySelector('div').innerHTML=faq.map(x=>`<h3>${esc(x.question)}</h3><p>${esc(x.answer)}</p>`).join('')}updateMeta(item)}
(slug?renderArticle():renderIndex()).catch(e=>error(e.message));
})();
